### ISSUE TITLE
modules/pmg_tk/startup/apbs_tools.py needs fix

### ISSUE THREAD

**Issue by jwhowarth** [schrodinger/pymol-open-source#101]
I found while testing a build of the new pymol 2.4.0 release for MacPorts that the shipping modules/pmg_tk/startup/apbs_tools.py file needs a tweak due to string.split() finally being removed.

```
-    searchDirs.extend(string.split(os.environ["PATH"], ":"))
+    searchDirs.extend(os.environ["PATH"].split(":"))
```

With this change, the apbs tools works fine with the exception that externally generated pqr files have to be loaded for python3. This change also works fine when pymol 2.4.0 is built against python 2.7.

**Comment by speleo3** [comment]
Thanks Jack for the patch, fixed.

On a related note, we should probably remove `apbs_tools.py` from this repo in favor of  https://github.com/Pymol-Scripts/Pymol-script-repo/blob/master/plugins/apbsplugin.py
