### ISSUE TITLE
Gltf exporting bad spheres

### ISSUE THREAD

**Issue by azhx** [schrodinger/pymol-open-source#107]
Hi, with Pymol 2.4 shipping with GLTF support, exporting sticks works great, but spheres look like this:
![image](https://user-images.githubusercontent.com/29048249/85890276-0cd0cf80-b7bb-11ea-812f-69b28b9aab1f.png)

(I am using windows 3d viewer in that image)

To reproduce (with a simple methane pdb generated from pybel):
[test.pdb](https://cdn.discordapp.com/attachments/605946561821802532/726151502925922396/test.pdb)

```
from pymol import cmd, preset
cmd.load('test.pdb', 'mol')
preset.ball_and_stick(selection="all", mode=1)
cmd.save('test.gltf', 'mol')
```

pymol=2.4.0
collada2gltf=2.1.4

Is this an issue with pymol open source or with the collada2gltf conversion?

Thanks

**Comment by speleo3** [comment]
I don't know the final answer yet, but with [collada_geometry_mode](https://pymolwiki.org/index.php/Collada_geometry_mode) 1 the spheres look correct on https://gltf-viewer.donmccurdy.com/
```python
cmd.set("collada_geometry_mode", 1)
cmd.save('test.gltf')
```

**Comment by speleo3** [comment]
Looks like this upstream bug: https://github.com/KhronosGroup/COLLADA2GLTF/issues/106

**Comment by speleo3** [comment]
We now always set `collada_geometry_mode` before exporting glTF. See 9fb23390ac18c412601edc732d428d7f87a71cf1. Closing this case.
