### ISSUE TITLE
select_list strange behavior

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#109]
Hi, 
`cmd.select_list()` assumes an inconsistent behavior in a particular situation:

If i use a list of indices where any index inside that list isn't part of the target object and set `mode="index"`, it returns an empty selection as I would expect.

Instead, with `mode="id"` it returns a selection of the whole object (WRONG behavior)

**Comment by speleo3** [comment]
Thanks for the bug report!
