### ISSUE TITLE
Selection issue after coloring a molecule 

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#11]
Hi, I am using compiled pymol 2.2.0 on Ubuntu 16.04. After applying a color to a molecule (like `color red, myMol`) I have a strange issue trying to pick atoms in order select them (for both viewing and edit mode). When I pick an atom, pymol selects an other (wrong) atom. 
I also noticed that if I set `color red` without specifying an object, the selection isn't broken

It seems that this issue doesn't show up in compiled pymol 2.1 and before.

**Comment by speleo3** [comment]
I have seen this before under the following conditions:
- Setting `use_shaders=off`
- Some atoms shown as `lines` or `nonbonded` (e.g. water)

That means, picking would work again after either of the two commands:
- `set use_shaders` (if supported by graphics driver)
- `hide lines nonbonded`

Can you confirm that this is the same in your case?

**Comment by giagitom** [comment]
Hi Thomas,
yes I confirm, hiding nonbonded worked for me.
