### ISSUE TITLE
Installing two versions of pymol-open-source from conda on three Python versions fail on OSX, Linux due to Python version

### ISSUE THREAD

**Issue by picodase** [schrodinger/pymol-open-source#110]
Hello,

I'm attempting to install PyMOL-open-source from Conda on OSX and Linux and am running into some nonsensical errors. Depending on the environment, Conda claims these packages require different Python versions, which are different when installing with other Python versions, and all in all, preclude me from installing PyMOL from these channels. I suppose this might have been done because the package distribution is being deprecated _via_ Conda, but the errors confused me nonetheless. This occurs on two separate Conda channels (channel: https://anaconda.org/tpeulen/pymol-open-source and channel: https://anaconda.org/tpeulen/pymol-open-source) with similar results.

I could install Schrodinger's paid package (and have tried this; it installs flawlessly unlike the below cases, but requires a license) but I'm not prepared to buy the subscription version, and this version should work.

Here are the outputs from three such install attempts:

## **Channel: https://anaconda.org/tpeulen/pymol-open-source (PyMOL open source version 2.3.0)**

Common prefix to all following code snippets:
```
> conda install -c tpeulen pymol-open-source
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:
```

Common infix to insert at "...":

```
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.


> python --version
```

Inside a Python 3.7 environment:
```
  - pymol-open-source -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7
...
Python 3.7.7
```

Inside a Python 3.8 environment:
```
  - pymol-open-source -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.8
...
Python 3.8.3
```

Inside a Python 2.7 environment:
```
  - pymol-open-source -> python[version='>=3.7,<3.8.0a0']

Your python: python=2.7
...
Python 2.7.18 :: Anaconda, Inc.
```

## **Channel: https://anaconda.org/awacha/pymol-open-source (PyMOL open source version 2.4.0)**

Common prefix to all following code snippets:
```
> conda install -c awacha pymol-open-source
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:
```

Common infix to insert at "...":

```
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

> python --version
```

Inside a Python 3.7 environment:
```
  - pymol-open-source -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7
...
Python 3.7.7
```

Inside a Python 3.8 environment:
```
  - pymol-open-source -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8
...
Python 3.8.3
```

Inside a Python 2.7 environment:
```
  - pymol-open-source -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=2.7
...
Python 3.7.7
```

**Comment by itaneja2** [comment]
any updates on this?

**Comment by speleo3** [comment]
This might be the wrong bug tracker for your issue. You should contact the packagers (tpeulen or awacha) instead.

**Comment by rbf22** [comment]
I agree. I could not find an install that worked, the pymol webpage failed, Conda failed, homebrew failed. I really used to like pymol.

**Comment by 0ut0fcontrol** [comment]
### pymol 2.4
test env: macOS Big Sur 11.4
#### conda
```
conda create -n test_pymol -c tpeulen -c conda-forge pymol-open-source
conda activate test_pymol
pymol # works
```
#### homebrew
```
brew install brewsci/bio/pymol
pymol # works
```
### pymol 2.5
- brew https://github.com/brewsci/homebrew-bio/pull/1351
- conda-forge https://github.com/conda-forge/pymol-open-source-feedstock/pull/8

**Comment by JarrettSJohnson** [comment]
Closing this issue. As stated by Thomas H, we don't currently manage conda feedstocks for the open-source project. I would go to their respective bug trackers and submit issues there.
