### ISSUE TITLE
Error during compilation with setup.py

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#111]
Hi,
I am trying to build and install PyMol using `setup.py` like I have always done but I'm getting this syntax error
`
  File "setup.py", line 227
    out.write(f'set PYMOL_PATH={pymol_path}' + os.linesep)
                                           ^
SyntaxError: invalid syntax
`

**Comment by speleo3** [comment]
The `master` branch requires Python 3.6+ now, see https://sourceforge.net/p/pymol/mailman/message/37030746/

**Comment by giagitom** [comment]
ok thanks!

**Comment by danielcanals2017** [comment]
Hi
My system runs $ python --version
Python 3.7.6
However I have the same error message:
$ sudo python setup.py install --prefix=~/pymol --pymol-path=~/pymol/pymol_Data
  File "setup.py", line 233
    out.write(f'set PYMOL_PATH={pymol_path}' + os.linesep)
