### ISSUE TITLE
Support per-state cell rendering

### ISSUE THREAD

**Issue by speleo3** [schrodinger/pymol-open-source#114]
This is a feature request to render the unit cell (or simulation box) per state, not per object.

See also https://sourceforge.net/p/pymol/mailman/message/37060203/

**Comment by dkozuch** [comment]
This update does not always seem to work properly. I am running a quick script to load and generate some structures from a GROMACS xtc, and the cell is changing, just not to the right dimensions. My best guess is that something may be wrong with how the timestep is read from the xtc file.

Here's my script:

```
#set orthoscopic
set orthoscopic, 1
#load files
load memb_treh_eq4.gro
load memb_treh_npt_dt10ns.xtc, memb_treh_eq4
#show cell
show cell
#rotate
rotate x, -90, state=0
```

**Comment by speleo3** [comment]
That last line looks suspicious, the cell won't do the -90 degree rotation, only the atom coordinates will. Maybe you mean to turn the camera instead (`turn x, -90`)?

https://www.pymolwiki.org/index.php/Turn
https://www.pymolwiki.org/index.php/Rotate

**Comment by dkozuch** [comment]
> That last line looks suspicious, the cell won't do the -90 degree rotation, only the atom coordinates will. Maybe you mean to turn the camera instead (`turn x, -90`)?
> 
> https://www.pymolwiki.org/index.php/Turn
> https://www.pymolwiki.org/index.php/Rotate

Thanks so much, worked perfectly!
