### ISSUE TITLE
Issue coloring huge surface in batch mode

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#115]
Hi,
PyMol hangs forever when trying to color a huge surface  
This code should reproduce the problem 

```
from pymol import cmd
cmd.fetch("3j3q",async=0)
cmd.hide("everything")
cmd.set("gaussian_resolution",9.0)
cmd.set("gaussian_b_floor", 40)
cmd.map_new("map","gaussian",3.0,"all and name ca",18.0)
cmd.isosurface("iso","map",0.0)

##### coloring using ramp (comment out this part and it works)
rampName = "ramp"
cmd.ramp_new("ramp","3j3q",[0,200],["atomic","atomic"])
cmd.disable("ramp")
cmd.color("ramp","iso")
##################################################

cmd.png("./test.png",ray=1,width=400)
```

**Comment by giagitom** [comment]
Additional info, it works normally on PyMol version 2.2

**Comment by speleo3** [comment]
Confirmed with 1aon. PyMOL 2.4 takes 3x as long as PyMOL 2.3.

**Comment by speleo3** [comment]
@JarrettSJohnson before and after c4436fcae:

![test2](https://user-images.githubusercontent.com/1239490/87691218-a40dbf00-c78a-11ea-8c1b-bbc2c117fa00.png) ![test3](https://user-images.githubusercontent.com/1239490/87691240-aa9c3680-c78a-11ea-81eb-ee26f8dce0a1.png)

**Comment by speleo3** [comment]
Note: Picture on the right should only be the result with `set ray_color_ramps, on`

@giagitom You can significantly speed this up by using a shorter distance range, like 10 or 20 instead of 200. All surface points should be close to an atom (within `gaussian_resolution` range), so a short range should be sufficient.
```python
cmd.ramp_new("ramp", "3j3q", [0, 10], ["atomic", "atomic"])
```

**Comment by giagitom** [comment]
@speleo3 Thank you! This solves the problem. I found that b-factor and map buffer also influence the distance range. I need a range slightly bigger than `gaussian_resolution` to compensate this effect.
