### ISSUE TITLE
Dedent help messages

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#116]
https://github.com/schrodinger/pymol-open-source/blob/96afefbb7412d062c0135d11e1b1c9b3995954e5/modules/pymol/helping.py#L83

Maybe the line above could be:

```python3
textwrap.dedent(doc)
```

**Comment by speleo3** [comment]
Do you have an example for which this change would be an improvement?

**Comment by pslacerda** [comment]
The docstring don't need to be aligned to the first column:
https://github.com/schrodinger/pymol-open-source/blob/master/modules/pymol/creating.py#L81

It can be identend like:
https://github.com/rr-/docstring_parser/blob/c02f559f40e89512625f5975208e4e6eff612e1c/docstring_parser/parser.py#L8

But the help message will not show the indentation.

**Comment by pslacerda** [comment]
The line could be:
```python3
 print("\n" + textwrap.dedent(doc).strip() + "\n") 
```
and will not affect existing code.

**Comment by speleo3** [comment]
I see, thanks. Would you like to send a pull request?

**Comment by pslacerda** [comment]
Could be just a commit from you...
