### ISSUE TITLE
Issue mutating residue programmatically in Python

### ISSUE THREAD

**Issue by itaneja2** [schrodinger/pymol-open-source#124]
I'm attempting to mutate a residue via python as follows: 

```
residue = 213
cmd.get_wizard().set_mode('GLN')
cmd.get_wizard().do_select('resi ' + str(residue))
cmd.get_wizard().apply() 
```

However, I get the following error: 

```

 Picked!
 ExecutiveRMSPairs: RMSD =    0.010 (4 to 4 atoms)
 Mutagenesis: 16 rotamers loaded.
 Rotamer 11/16, strain=-27.14

File "/Users/ishan/Holehouse/ishan/protein_mutation_pymol/mutate_residue_helper_functions.py", line 125, in mutate_residue
    cmd.get_wizard().apply()
  File "/Users/ishan/opt/anaconda3/lib/python3.8/site-packages/pymol/wizard/mutagenesis.py", line 362, in apply
    state = cmd.get_object_state(new_name)
  File "/Users/ishan/opt/anaconda3/lib/python3.8/site-packages/pymol/querying.py", line 1548, in get_object_state
    raise pymol.CmdException('Invalid state %d for object %s' % (state, name))
pymol.CmdException:  Error: Invalid state 11 for object 2b3p
```

I did a further deep dive and it's due to a discrepancy between count_states(name) and the current state. The former equals 2 while the latter equals 11. The 11 stems from the residue selection while I believe the 2 stems from set_mode('GLN'). For some reason the current state is not getting updated internally or is just not selected even though the residue was successfully picked? Any thoughts or ideas? Have really been struggling with this for a few hours now.

**Comment by speleo3** [comment]
I can't reproduce this. Fetching `2b3p`, opening the mutagenesis wizard and entering your 4 lines of code works as expected for me.

Have you modified PyMOL? `cmd.get_object_state(new_name)` should be on [line 342](https://github.com/schrodinger/pymol-open-source/blob/c7095ec2f2a1e6015acb469e9daff9ff349dd3be/modules/pymol/wizard/mutagenesis.py#L342), not on line 362.

**Comment by itaneja2** [comment]
I did but I only added print statements. For reference I'm running pymol 2.4.0 installed via conda (so not the open source version). Which version were you using?

**Comment by speleo3** [comment]
Thanks for the update, glad you figured it out!
