### ISSUE TITLE
Auto-fix process for PDB file inconsistencies

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#125]
Hello

I am running across a couple of inconsistencies in the PDB files and different pieces of software seem to handle them differently.

pymol seems to be recognising and automatically fixing those errors. Would it be possible to provide some pointers on how are certain decisions taken to conclude with the displayed structure?

For a specific example of the kinds of errors I am talking about, please see [here](https://github.com/openbabel/openbabel/issues/2156). 

We can assume that the PDB file is not going to be pristine. However, I am not sure what sort of assumptions I can make to piece together those fragments.

A brute force solution would be to do an "all-to-all" distance estimation and then blindingly connect atoms that are closer than a specific threshold, but I am not sure that this is a generically applicable solution.

When I "fetch 6QWY; select bb, backbone;deselect;hide all; show sticks, bb", it appears as one continuous chain but I know that it is not continuous in the file because I am following the chain atom-to-atom, bond-to-bond and I can see that the chain is (not only asymetrically defined but also) inconsistent based on the data read from the file through openbabel.

How does pymol recover from PDB "errors" such as the one described here?

**Comment by speleo3** [comment]
PyMOL indeed creates bonds by atom distance, or more precisely by VDW overlap.

See also:
https://pymolwiki.org/index.php/Connect_mode
https://pymolwiki.org/index.php/Connect_cutoff

You might want to have a look at the MMTF format as a modern replacement for PDB. MMTF explicitly includes all bonds.
http://mmtf.rcsb.org/

I'm not sure what you mean by "error" and by "asymmetrically defined".

**Comment by aanastasiou** [comment]
@speleo3 Thank you very much, this is very clear. I guess that "distance-based bonding" step is unavoidable to get over these discrepancies I am coming across.

From a brief scan over MMTF's docs, I can see that I can instantiate it directly with a PDB id and it would handle the fetching and conversion (presumably). Would it, internally, go through this resolution of what is connected to what or simply mirror what it finds in that PDB?

Regarding errors, I am going to a little bit more detail in the link I provided but very briefly:

1. An "error" is a fragment that is supposed to be part of a chain but is not. If you run a query on the chain, the atoms are grouped under it. But if you try to start at the first atom and following the bonds, get to a given atom in question, it is unreachable. For example, given the usual sequence of NCaCO, you might come across a CaCO whose Ca is not connected to the N. Or worse even, the C is not the Ca but a C of a side chain that is not even connected to the Ca.

2. An assymetric connection is one where given two atoms A,B, you can hop from A->B following the bond data (and get information about that bond), as expected, but not A<-B. There is no directionality in these bonds and I would expect that having located an atom, I could just say "give me all the atoms it is connected to". But that is not always true. You can select an atom (say for example, "give me all the Cas") but one or more of those selections would only appear connected from the other atom, not from itself.

Both of these errors are of course through trying to work with the PDB data directly (and using the data structures of openbabel (for example)). I appreciate pymol might be offering some of this information already, but it also makes you ask "How does pymol sort it out?", hence this question :)

All the best

**Comment by speleo3** [comment]
The MMTF file stores all bonds in an explicit list, PyMOL will not do any auto-detection. Implementation can be found here: https://github.com/schrodinger/pymol-open-source/blob/master/layer2/MmtfMoleculeReader.cpp

I don't think that issue 2 exists in PyMOL. PyMOL has a primary Bond array were bonds are in arbitrary direction, and a secondary Neighbor data structure which is built from the Bond array and makes available bonded neighbors for each atom (in both directions). Accessing neighbors e.g. with the [bound_to](https://pymolwiki.org/index.php/Selection_Algebra) selection operator should always work bidirectional.

**Comment by aanastasiou** [comment]
@speleo3 MMTF on its own (as expected) would not solve this problem. But perhaps opening the file within pymol and saving it from there would. Unfortunately however, due to the issue with the hydrogens, even if the hydrogen bonds are detected, they are not included in the MMTF file at all. The hydrogens are simply added, each one in its own group. Does this sound right or did I forget a switch somewhere?

**Comment by speleo3** [comment]
https://pymolwiki.org/index.php/Connect_mode

PyMOL's mmCIF loader does not use `connect_mode` 0-2 (will fall back to 3).

**Comment by aanastasiou** [comment]
@speleo3 I see. So, the only robust solution to inferring connectivity of atoms is the distance based calculation, irrespectively of what sort of bonds the data may be specifying.
