### ISSUE TITLE
Hydrogens in queries

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#128]
Given:

* `delete all; fetch 1gcn;hide all;show sticks, 1gcn;h_add`

The following do not seem to behave as expected...or there is something I am missing about Hydrogens (?):

1. `indicate 1/` As expected, *all atoms* expected to be grouped under residue 1 are grouped under residue 1.
2. `indicate 1/ and elem H` As expected, *only* the hydrogens of residue 1 are now indicated (or similarly selected if using `select`).
3. `indicate 1/ and backbone` As expected, only 4 atoms belonging to the backbone are indicated.
4. `indicate 1/ and backbone and elem O` As expected, *only* the Oxygen is indicated.

5. `indicate 1/ and backbone and elem H` This indicates nothing. Replacing `indicate` with `select` shows `"sele" defined with 0 atoms"` (?)

**Comment by speleo3** [comment]
What I already wrote in https://github.com/schrodinger/pymol-open-source/issues/127#issuecomment-688393769

> `h_add` does not add hydrogens with standard PDB names, but simply names them "H01", "H02", etc. and the `backbone` selection only detects atoms with standard names.
