### ISSUE TITLE
What sort of data type is the result of `dist`?

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#129]
Given:

`delete all; fetch 1GCN; hide all; select bb, backbone; deselect; show sticks, bb; h_add`

The command `dist h_bonds, bb, bb, mode=2`, indicates the hydrogen bonds (with all assumptions described in [this Wiki article](https://pymolwiki.org/index.php/Displaying_Biochemical_Properties) ).

`h_bonds` is indicated in the user interface as a "selection". But, it does not behave as a selection. It is impossible to `select, iterate` on it and there do not seem to be any functions that would isolate the start, end point of each "dash", so that these parts could then become selections. The only command `h_bonds` participates with happily is `show/hide`.

Is it possible to work with the return result of `dist` in some way? What would it look like?

**Comment by speleo3** [comment]
Raw measurement data is unfortunately not very well exposed in the API. But you might be interested in this script: https://pymolwiki.org/index.php/Get_raw_distances

**Comment by aanastasiou** [comment]
Indeed. Thank you very much.
