### ISSUE TITLE
Failing to launch legacy plugins

### ISSUE THREAD

**Issue by carlosfamilia** [schrodinger/pymol-open-source#13]
Hi,

Have a pymol installation on a macOS Mojave, made through brew with python 2.2.
When launching any of the legacy plugins installed by default it will give an error.

apbs_tools:
``` 
Python[1028:58103] -[QNSApplication _setup:]: unrecognized selector sent to instance 0x7feee962efa0
```

remote_pdb_load:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/2.2.0/libexec/lib/python2.7/site-packages/pmg_tk/startup/remote_pdb_load.py", line 27, in fetchdialog
    root = plugins.get_tk_root()
  File "/usr/local/Cellar/pymol/2.2.0/libexec/lib/python2.7/site-packages/pymol/plugins/legacysupport.py", line 39, in get_tk_root
    return get_pmgapp().root
  File "/usr/local/Cellar/pymol/2.2.0/libexec/lib/python2.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 125, in root
    tkinter_init()
  File "/usr/local/Cellar/pymol/2.2.0/libexec/lib/python2.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 15, in tkinter_init
    raise RuntimeError('tkinter init failed')
RuntimeError: tkinter init failed
```

In the same computer have the binaries provided by Schrödinger and the legacy plugins run perfectly.
any idea?

**Comment by speleo3** [comment]
this is because Homebrew doesn't provide an X11 build of Tcl/Tk

**Comment by carlosfamilia** [comment]
Hi,

It makes sense to me that if Tkinter is able to generate windows and guis in python that it should be able to create the simple windows required for the legacy plugins. I know that PyQt and Tkinter don't really go well together, however in the PyMol code the it seems that they sort this problem by creating new threads to run the Tkinter apps.
I was trying to modify the code to have the legacy plugins to work with Tkinter with no X11 support, however I really need some expert opinion if it is feasible, and where should I begin. This because I have been looking to PyMOL code and debugging it, however I can manage to figure out the logic of plugin launching and tk() calls for the plugins.
Is there any document with the schematics of this? Like in UML or something like that?

Thanks
