### ISSUE TITLE
What could give rise to this discrepancy?

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#130]
Residue 59/ in 6QWY seems to be rendered twice, making it appear like it has double oxygens and double hydrogens in a V shape.

If this discrepancy is more likely to be because of the underlying data (rather than its interpretation and rendering by pymol) , what could be causing it?

![image](https://user-images.githubusercontent.com/1336337/92489074-3ceb1480-f1e7-11ea-91ea-f014d03aeacc.png)

This was generated via: 
`delete all;fetch 6QWY;select bb, backbone;select other, not bb;deselect;hide all;show sticks, bb;h_add bb;dist h_bonds, bb,bb,mode=2;indicate 59/`

Here is another view:

![image](https://user-images.githubusercontent.com/1336337/92490075-740df580-f1e8-11ea-81a8-1907ad93d718.png)

**Comment by speleo3** [comment]
See for example:
https://proteopedia.org/wiki/index.php/Alternate_locations
https://pymol.org/d/selection:altloc

**Comment by aanastasiou** [comment]
That is great, thank you very much @speleo3 .
