### ISSUE TITLE
Bended cylinders for alpha helices in cartoon representation

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#131]
This would be very nice, especially for structures having long alpha helices like the ATP Synthase below
![Screenshot 2020-09-11 16:45:15](https://user-images.githubusercontent.com/20627977/92939683-59d55100-f44e-11ea-94d0-268c2eac74a3.png)

**Comment by JarrettSJohnson** [comment]
@speleo3 recently worked on this and is now putting the finishing touches on PyMOL support for curved cartoon cylinder helices. Should be coming soon.

**Comment by speleo3** [comment]
This has been implemented, see updated PyMOLWiki description:
https://pymolwiki.org/index.php/Cartoon_cylindrical_helices

**Comment by giagitom** [comment]
Awesome! Thank you
