### ISSUE TITLE
install issue, fatal error: netcdf.h

### ISSUE THREAD

**Issue by jianhaoc** [schrodinger/pymol-open-source#132]
Hi, I came with a install issue that installation couldn't find netcdf.h. How can I install that lib? Thank you! 

$ python setup.py install --prefix=/home/zh/sw/pymol-open-source
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
running install
running build
running build_py
running build_ext
building 'pymol._cmd' extension
gcc -pthread -B /home/zh/soft/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -D_PYMOL_NO_MSGPACKC -D_PYMOL_NO_MAIN -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -I/home/zh/soft/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/zh/soft/anaconda3/include -I/home/zh/soft/anaconda3/include/freetype2 -I/home/zh/soft/anaconda3/include/libxml2 -I/home/zh/soft/anaconda3/include/python3.7m -c -MMD contrib/uiuc/plugins/molfile_plugin/src/netcdfplugin.c -o build/temp.linux-x86_64-3.7/contrib/uiuc/plugins/molfile_plugin/src/netcdfplugin.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3
g++ -pthread -B /home/zh/soft/anaconda3/compiler_compat -Wl,--sysroot=/ -std=c++11 -fPIC -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -D_PYMOL_NO_MSGPACKC -D_PYMOL_NO_MAIN -D_PYMOL_NUMPY -Iinclude -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -I/home/zh/soft/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/zh/soft/anaconda3/include -I/home/zh/soft/anaconda3/include/freetype2 -I/home/zh/soft/anaconda3/include/libxml2 -I/home/zh/soft/anaconda3/include/python3.7m -c -MMD layer4/Cmd.cpp -o build/temp.linux-x86_64-3.7/layer4/Cmd.o -Werror=return-type -Wunused-variable -Wno-switch -Wno-narrowing -Wno-char-subscripts -O3
contrib/uiuc/plugins/molfile_plugin/src/netcdfplugin.c:27:10: fatal error: netcdf.h: No such file or directory
 #include <netcdf.h>
          ^~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
$ which gcc
/usr/bin/gcc

**Comment by jianhaoc** [comment]
I tried to install pymol on CentOS with anaconda3.

**Comment by speleo3** [comment]
PyMOL requires libnetcdf. See https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL

**Comment by dslcc** [comment]
Has the problem been solved? I meet the same problem...So, is there a solution to it ?

**Comment by JarrettSJohnson** [comment]
Hi @dslcc . The issue reported here is not a problem. It's a dependency that you might not have installed. The link above shows you how to obtain the dependency or provide a flag to setup.py to omit features that require this dependency.
