### ISSUE TITLE
error loading .gro format using cmd.load_raw 

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#133]
I normally use ```load_raw``` to load structures from strings. 
This does not work with ```.gro``` extension though. Is there an other way of doing this?

**Comment by speleo3** [comment]
For now, writing the string to a temporary file is the only solution I think. The `.gro` format is handled by the [molfile plugins](https://github.com/schrodinger/pymol-open-source/tree/master/contrib/uiuc) and that API is file-based.

**Comment by giagitom** [comment]
Ok thanks, I'll use this method than

**Comment by giagitom** [comment]
Thanks!
