### ISSUE TITLE
Building with musl libc

### ISSUE THREAD

**Issue by ericonr** [schrodinger/pymol-open-source#135]
Hi! I'm packaging `pymol` for Void Linux, and we have a musl libc version. musl doesn't include `execinfo.h` as a part of itself, so it's necessary to use `libexecinfo` instead, like FreeBSD does. I simply replaced the freebsd check with `True` in order to build it, but ideally it would be nice if we could build it without changing the files. What possible solution do you see? Could perhaps a `NEED_EXECINFO` environment var be added, or is there some more elegant way of fixing this?

**Comment by speleo3** [comment]
Yes adding `NEED_EXECINFO` would be fine. Or you could just export `LDFLAGS="-lexecinfo"`.

**Comment by ericonr** [comment]
Exporting `LDFLAGS` didn't work! Somehow it got through linking, but the final library didn't have all the information to resolve the `backtrace` symbol.

**Comment by speleo3** [comment]
Before we come up with some sophisticated solution: I think we could also just remove the [print_trace](https://github.com/schrodinger/pymol-open-source/blob/master/layer0/GraphicsUtil.cpp#L15) function. I don't recall that this code has played any significant role for fixing bugs. Nothing that can't be done with a debugger and a breakpoint.
