### ISSUE TITLE
Save to png format from GUI produces TypeError invoked by pysideuic in release 2.4.0

### ISSUE THREAD

**Issue by rajatkrpal** [schrodinger/pymol-open-source#136]
With Qt, saving to PNG format from the GUI encountered the following error:
```
Traceback (most recent call last):
  File "/home/software/pymol2.4-qt/lib/python2.7/site-packages/pmg_qt/file_dialogs.py", line 574, in file_save_png
    form = parent.load_form('png')
  File "/home/software/pymol2.4-qt/lib/python2.7/site-packages/pmg_qt/pymol_qt_gui.py", line 523, in load_form
    form = pymol.Qt.utils.loadUi(uifile, widget)
  File "/home/software/pymol2.4-qt/lib/python2.7/site-packages/pymol/Qt/utils.py", line 289, in loadUi
    pysideuic.compileUi(uifile, stream)
  File "/usr/lib/python2.7/dist-packages/pysideuic/__init__.py", line 140, in compileUi
    pyfile.write(_header % (uifname, ctime(), __version__, PySide.__version__))
TypeError: unicode argument expected, got 'str'
```

Saving to png format from the command line interface does not show any errors.
I tried to look if it is an issue with "pysideuic" and after some search I found that the erro is an I/O error.

Solution that I tried:
After installing pymol 2.4.0, I changed a line in the `utils.py` file under `/lib/python2.7/site-packages/pymol/Qt`.

The is within in the `def loadUI(uifile, widget):` method

I changed the line  `stream =io.StreamIO()` to `stream = io.BytesIO()` . I guess "pysideuic" wants some variable in Unicode but Qt module within pymol is giving "pysideuic" a string variable instead.
This resolved the issue of saving to PNG from GUI.

I have not checked yet if this change affected some other functionalities. Please comment on this if anyone have faced similar issues with Pymol Qt GUI.

**Comment by speleo3** [comment]
Only affects Python 2 with PySide (maybe PySide2) as far as I can tell.

Workarounds:
- Use Python 3
- Use PyQt5
- Use PySide2 (maybe)

With PySide2, we should probably use `PySide2.QtUiTools.QUiLoader` to do this, instead of using `pyside2uic` or a `uic` subprocess.

**Comment by speleo3** [comment]
Fixed in the legacy `py2` branch.
https://github.com/schrodinger/pymol-open-source/tree/py2
