### ISSUE TITLE
pymol homebrew install broken by latest glew homebrew update

### ISSUE THREAD

**Issue by n-codina** [schrodinger/pymol-open-source#139]
from what I can tell, the latest update to the glew home-brew formula breaks pymol at runtime, glew was updated to version 2.2 15 days ago (https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/glew.rb) and pymol expects glew to be version 2.1:

```
$ pymol
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pymol/__init__.py", line 64, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pymol/__init__.py", line 580, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pymol/_cmd.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.1.dylib
  Referenced from: /usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pymol/_cmd.cpython-38-darwin.so
  Reason: image not found
```

**Comment by speleo3** [comment]
Shouldn't this be reported to homebrew instead?
https://github.com/Homebrew/homebrew-core/issues/new/choose

**Comment by YoshitakaMo** [comment]
I have upgraded the PyMOL formula yesterday (see https://github.com/brewsci/homebrew-bio/pull/1180). Try this one.

**Comment by JarrettSJohnson** [comment]
@n-codina Has this issue resolved for you?

**Comment by rbf22** [comment]
homebrew does not seem to have PyMOL as an install anymore. Tried to install from this repo and none of the menus work.

**Comment by JarrettSJohnson** [comment]
PyMOL 2.5 should have since been added to Brewsci/Bio. https://github.com/brewsci/homebrew-bio/pull/1351
