### ISSUE TITLE
Residue "sequence distance" operator?

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#141]
I wonder if there is a way to incorporate the sequence distance between two residues in a selection query (?). I am looking through [the selection algebra](https://pymolwiki.org/index.php/Selection_Algebra) and it does not look like there is an operator for this at the moment, but I would like to confirm that.

The use case is to evaluate the distance between two atoms as long as they are N residues apart.

**Comment by speleo3** [comment]
You're correct, such an operator does not exist. I guess it would be similar to the `extend` operator which goes along bonds. 

N residue distance is 3*N bond distance, so to select the neighboring 10 residues of `sele` you could actually do this:
```
select extend10res, byres ((byca sele) extend 30)
```
(This logic is not compatible with disulfide bonds or other cross-links...)

**Comment by aanastasiou** [comment]
@speleo3 Thank you, that's very helpful. I am doing it manually outside of pymol for the moment.

I guess, in terms of an operator, it would make sense to have a single "distance" followed by a qualifier (with a default option, such as euclidean for example).

So, something like:

```
    select some_atoms, elem N
    dist some_d_object, some_atoms, element N at [gap|euclidean] distance 10 from some_atoms, cutoff=3
```

Notice here of course that `cutoff` would have to be in the same units as the "qualified" distance.

All the best
