### ISSUE TITLE
Windows version of PyMOL Open Source has almost invisible structures on initialization

### ISSUE THREAD

**Issue by smkm** [schrodinger/pymol-open-source#15]
On my computer, I have installed both PyMOL 2.2.0 and 2.3.0a0 for Python 3.6 and 3.7 (one at a time) on Windows 10 and the problem below showed.  
(https://www.lfd.uci.edu/~gohlke/pythonlibs/#pymol)

However, like the image below, I can see that the structure is greatly dimmed and almost invisible. On another computer using the same procedures for installation, the structure is bright like other normal computers.  

![image](https://user-images.githubusercontent.com/8457324/49439888-9b5eb400-f805-11e8-8793-6b314d78015b.png)

If I type in `ray`, the below picture shows. 

![image](https://user-images.githubusercontent.com/8457324/49440133-348dca80-f806-11e8-85c0-6a29647e2b97.png)

And the structure goes back to the dimmed state if I move it. 

![image](https://user-images.githubusercontent.com/8457324/49440385-d6151c00-f806-11e8-8251-73bc12c47184.png)

However, if I click Reinitialize --> Original Settings, the structure becomes normal. 

![image](https://user-images.githubusercontent.com/8457324/49440053-014b3b80-f806-11e8-91e6-2c198fd005af.png)

If I click Reinitialize --> Everything and reload the file, it goes back to the first greatly dimmed state. 

This problem occurs on a different Python version installation, different PyMOL installation, and after reinstalling everything. The protein structure file input did not matter for this at all. On another computer with the exact same installation procedures, it is normal. The only difference was that the computer with this problem had the Commercial PyMOL installed before, but uninstalled after. 

What is wrong with the settings I have right now, and what should I do to get the default back to `Original Settings`, instead of having to do Reinitialize --> Original Settings every time?

I need the real solution of this problem, I know how to put `reinitialize original_settings` in pymolrc. This is not a pretty solution. 

@speleo3

**Comment by speleo3** [comment]
The issue was address in commit b97a53f64e6e5ddb3e846f34e1522b245930952d by blacklisting the driver version.

**Comment by smkm** [comment]
```
 Detected OpenGL version 4.5. Shaders available.
 Detected GLSL version 4.50.
 OpenGL graphics engine:
  GL_VENDOR:   Intel
  GL_RENDERER: Intel(R) HD Graphics 620
  GL_VERSION:  4.5.0 - Build 25.20.100.6444
```
Also causes this. Please reference.

**Comment by speleo3** [comment]
Thank you @smkm! We will add your driver version to the blacklist.
