### ISSUE TITLE
Png command within .pml scripts broken

### ISSUE THREAD

**Issue by rbf22** [schrodinger/pymol-open-source#150]
The png command is broken. When issuing draw command from within a script.pml the engine renders an image of the command prompt and not the view window or the object generated by draw. 

To reproduce:

Create file test.pml with the following lines:
fetch 1ubq 
draw
png test.png
quit

The resulting image will be black with white text

**Comment by gabrieldsuarez** [comment]
Same problem here, thanks in advance.

**Comment by speleo3** [comment]
@rbf22 We'll have a fix for this soon.

@gabrieldsuarez Your libpng issue is unrelated.
