### ISSUE TITLE
Increase accuracy/polygon count of exported meshes (VRML)

### ISSUE THREAD

**Issue by 21347** [schrodinger/pymol-open-source#152]
Currently, exported meshes (e.g. in VRLM) look quite "blocky" when imported in other software (e.g. Blender or Cura for 3D-Printing).

The image below shows a C<sub>60</sub> molecule with an additional volume - both are quite blocky.
![grafik](https://user-images.githubusercontent.com/2291273/101461006-9b38a800-393a-11eb-9102-2cd94b34cef9.png)

Or, to put it that way: is there already a way to change that? So far I didn't find any setting, neither in the Wiki nor by browsing the source.

**Comment by 21347** [comment]
Ok - sorry, I just realized that the source files for the volumes seem not to be of higher acuracy, obviously it's just not as "visible" in the shaded view of PyMold compared to Blender's display.

This basically only leaves atoms and sticks as possible candidate for improvement. If their acuracy is also dependent on the source file and cannot be improved by PyMol itself, this issue can be closed I think.

**Comment by speleo3** [comment]
You could try the `map_double` command: https://pymolwiki.org/index.php/Map_double

Stick quality seems fix for VRML export, but [COLLADA](https://pymolwiki.org/index.php/COLLADA) export takes settings like `stick_quality` into account. Note that for Blender, you might need to remove the `<unit>` tag from the `.dae` file before importing it.

**Comment by 21347** [comment]
Thank you, that increases the polygon count, yes. COLLADA export also creates higher quality representation of the sticks, though for some reason I cannot get the atoms displayed, too. I'll check with some low-atom count Molecule later, but that's maybe a different issue.

However, I found a work-around for the initial problem in Blender: Collapse all points of the individual meshes by distance (to remove duplicates created by exporting individual triangles), smooth and subdivide.

So, from that point of few: issue resolved, I have to learn how to get higher quality data.
