### ISSUE TITLE
Spectrum CGO

### ISSUE THREAD

**Issue by Gwynase** [schrodinger/pymol-open-source#161]
I have an issue when coloring the CGO (Compiled Graphics Objects) lines by continuous color spectrum. I wrote python scripts tried to color the cgo lines by function "cmd.load_cgo()". But no matter how I chenge the RGB value, the color of cgo lines generated by pyMOL is not continuous. Here's an example of my scripts to generate continuous color spectrum cylinder, and followed by the result generated by pymol. Here's an example of my scripts to generate continuous color spectrum cylinder, and followed by the result generated by pymol.
![image](https://user-images.githubusercontent.com/49516140/105155095-2bc2f480-5b45-11eb-950b-67e2d0571485.png)
![image](https://user-images.githubusercontent.com/49516140/105155112-2f567b80-5b45-11eb-9ac0-b243f04f6c6c.png)
Any idea about this? Thanks very much!

By the way, what I want is to virtualize the protein structural movement, just like
this. 
![image](https://user-images.githubusercontent.com/49516140/105155149-39787a00-5b45-11eb-83b2-a70d7e18c09d.png)
If you have any idea or know some scripts can do this, I'll be very appreciated.

**Comment by speleo3** [comment]
Color values are from 0 to 1, not from 0 to 255.

https://pymolwiki.org/index.php/CGOCylinder

**Comment by Gwynase** [comment]
Much appreciated! 
It works now!

> Color values are from 0 to 1, not from 0 to 255.
> 
> https://pymolwiki.org/index.php/CGOCylinder
