### ISSUE TITLE
error: command 'icpc' failed with exit status 4

### ISSUE THREAD

**Issue by hhhnano** [schrodinger/pymol-open-source#163]
Dear Pymol,
An error occurred when I install pymol-open-source according to the guide here, how to fix it?
Thank you in advance.

the detail installation is as follows: 
# CentOS
yum install gcc gcc-c++ kernel-devel python-devel tkinter python-pmw glew-devel \
  freeglut-devel libpng-devel freetype-devel libxml2-devel glm-devel \
  msgpack-devel netcdf-devel

git clone https://github.com/schrodinger/pymol-open-source.git
git clone https://github.com/rcsb/mmtf-cpp.git
mv mmtf-cpp/include/mmtf* pymol-open-source/include/
cd pymol-open-source

python setup.py install --prefix=/home/xzhfood/software/pymol

python is 3.8.5 version

layer0/Util2.h(109): error: no instance of overloaded function "pymol::string_format_detail::fwdArgs" matches the argument list
            argument types are: (int)
        fmt, string_format_detail::fwdArgs(std::forward<FmtArgs>(fmtargs))...);
             ^
          detected during instantiation of "std::string pymol::string_format(const char (&)[N], FmtArgs &&...) [with N=19UL, FmtArgs=<const char *&, int &, int &, int &, int &>]" at line 14144 of "layer3/Executive.cpp"

layer0/Util2.h(109): error: no instance of overloaded function "pymol::string_format_detail::fwdArgs" matches the argument list
            argument types are: (int)
        fmt, string_format_detail::fwdArgs(std::forward<FmtArgs>(fmtargs))...);
             ^
          detected during instantiation of "std::string pymol::string_format(const char (&)[N], FmtArgs &&...) [with N=19UL, FmtArgs=<const char *&, int &, int &, int &, int &>]" at line 14144 of "layer3/Executive.cpp"

compilation aborted for layer2/CifMoleculeReader.cpp (code 2)
compilation aborted for layer3/Executive.cpp (code 2)
compilation aborted for layer1/Text.cpp (code 2)
error: command 'icpc' failed with exit status 4

**Comment by speleo3** [comment]
We have no experience with the `icpc` compiler. Contributions welcome.

**Comment by speleo3** [comment]
To use a different compiler, you need to set `CC` and `CXX`. For example:
```bash
export CC=gcc
export CXX=g++
```

**Comment by hhhnano** [comment]
I try switch the other compiler, the error is still there

export CC=gcc
export CXX=g++

layer0/vla.h:37:45: error: expected primary-expression before ‘>’ token
   static_assert(std::is_trivially_copyable<T>::value, "");
                                             ^
layer0/vla.h:37:46: error: ‘::value’ has not been declared
   static_assert(std::is_trivially_copyable<T>::value, "");
                                              ^
In file included from layer1/Symmetry.h:26:0,
                 from layer1/PyMOLObject.h:27,
                 from layer2/ObjectMolecule.h:24,
                 from layer1/P.h:22,
                 from layer1/CGO.cpp:32:
layer0/vla.h:37:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
   static_assert(std::is_trivially_copyable<T>::value, "");
                 ^
layer0/vla.h:37:45: error: expected primary-expression before ‘>’ token
   static_assert(std::is_trivially_copyable<T>::value, "");
                                             ^
layer0/vla.h:37:46: error: ‘::value’ has not been declared
   static_assert(std::is_trivially_copyable<T>::value, "");
                                              ^
In file included from layer1/Symmetry.h:26:0,
                 from layer1/PyMOLObject.h:27,
                 from layer2/ObjectMolecule.h:24,
                 from layer1/P.h:22,
                 from layer4/PopUp.cpp:31:
layer0/vla.h:37:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
   static_assert(std::is_trivially_copyable<T>::value, "");
                 ^
layer0/vla.h:37:45: error: expected primary-expression before ‘>’ token
   static_assert(std::is_trivially_copyable<T>::value, "");
                                             ^
layer0/vla.h:37:46: error: ‘::value’ has not been declared
   static_assert(std::is_trivially_copyable<T>::value, "");
                                              ^
In file included from layer1/Symmetry.h:26:0,
                 from layer1/PyMOLObject.h:27,
                 from layer3/Executive.h:25,
                 from layer1/Text.cpp:27:
layer0/vla.h:37:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
   static_assert(std::is_trivially_copyable<T>::value, "");
                 ^
layer0/vla.h:37:45: error: expected primary-expression before ‘>’ token
   static_assert(std::is_trivially_copyable<T>::value, "");
                                             ^
layer0/vla.h:37:46: error: ‘::value’ has not been declared
   static_assert(std::is_trivially_copyable<T>::value, "");
                                              ^
error: command 'g++' failed with exit status 1

**Comment by speleo3** [comment]
Looks like gcc 4.8 doesn't have `std::is_trivially_copyable` even though it's supposed to have C++11 support. You can delete line 37 in `layer0/vla.h`, that should be sufficient to compile on CentOS 7 with gcc.
