### ISSUE TITLE
APBS avs output is getting deleted (?)

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#165]
Hello

If I add ``write charge avs "somepath"`` in the APBS ``in`` file, this does not appear in ``somepath``, is there an additional parameter I need to add or anything else to set before I can obtain that additional output? (I understand that pymol might not be using it but since I can run APBS from within pymol I would just like to obtain that additional output too).

**Comment by speleo3** [comment]
Good question. I see this output on the terminal (not in the PyMOL log window):
```
  Writing charge distribution to somepath.ucd
Sorry, AVS format isn't supported for uniform meshes yet!
```
The formats `flat` and `dx` work for me. Not sure what we'd need to change to support `avs` format.

**Comment by aanastasiou** [comment]
I just logged in to write exactly that, as I isolated a sample file and tried to run apbs on its own, independently of pymol. So, indeed, the AVS file is not written because apbs does not produce it. 

I just tried `flat` and the `charge` map comes out all zeros (but the ``pot`` does contain values), both within and out of pymol, so that might be something for apbs.

**Comment by speleo3** [comment]
You can export the scene as VRML (`.wrl`) or COLLADA (`.dae`). Hide all objects except the "prepared01" object which is shown as surface, then do `save surf.wrl`

**Comment by aanastasiou** [comment]
Fantastic, thank you @speleo3
