### ISSUE TITLE
fatal error: 'Python.h' file not found 

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#166]
Hi,

I'm using the provided Anaconda environment. However `pybel-tools` is refusing to be installed with `pip` because of missing Python.h.

What should I do?

**Comment by speleo3** [comment]
Try reinstalling Python first:
```
conda install --force-reinstall python
pip install pybel-tools
```

**Comment by pslacerda** [comment]
It worked!
