### ISSUE TITLE
spacenavigator does not load

### ISSUE THREAD

**Issue by JakobBerg** [schrodinger/pymol-open-source#170]
I just got back to the linux opensource version of pymol 2, so there is a chance this is not a bug, but I just missed something trivial, and this should have been asked in a different forum;

I have a usb 3D mouse space navigator from 3Dconnexion which I used with pymol 1.x - this was with the spnav plugin before python 3.  

At the current setup, I am using pop!_OS 20.04 LTS - and from apt-get installed libraries: libspnav0, libspnav-dev, and the daemon: spacenavd. From pip I collected the spnav.

I have tested both the pymol version from apt repository (2.3.0) as well as the version from snap (2.4.1) - neither of them tries to detect the USB device.

If I download and launch the Incentive version from miniconda, pymol (2.4.1) will confirm the Spacenavigator is detected and is usable when I proceed to evaluate the software.

**Comment by speleo3** [comment]
The SpaceNavigator support provided by Schrödinger is an Incentive PyMOL only feature and is not part of Open-Source PyMOL. Maybe you used a third-party plugin before, like https://pymolwiki.org/index.php/Spaceball_plugin?

**Comment by JakobBerg** [comment]
Thanks for clarifying Thomas, I will try to adapt the old third-party plugin to the new open-source pymol.

**Comment by JarrettSJohnson** [comment]
As mentioned, Incentive PyMOL provides this feature and is not available automatically in open-source. Closing the issue.
