### ISSUE TITLE
I create Flatpak for PyMOL

### ISSUE THREAD

**Issue by kevinsmia1939** [schrodinger/pymol-open-source#172]
Hello,

I have create Flatpak for PyMOL.

```
Flatpak is a utility for software deployment and package management for Linux. It is advertised as offering a sandbox environment in which users can run application software in isolation from the rest of the system.

Flatpak was developed as part of the freedesktop.org project (formerly known as X Desktop Group or XDG) and was originally called xdg-app.
```

https://www.flatpak.org/
https://github.com/kevinsmia1939/org.pymol.PyMOL

I would like to submit to Flathub as well.
https://flathub.org/home

Let me know what  you think.
Thanks.

**Comment by kevinsmia1939** [comment]
Hi @speleo3 

I just successfully build Flatpak package for PyMOL. Are you be interest to co-maintain the Flatpak repository?

**Comment by JarrettSJohnson** [comment]
Hi @kevinsmia1939 I haven't gotten around to testing the flatpak myself yet (I'm looking forward to giving it a shot!), but Schrodinger developers aren't typically involved with maintaining packages. There's many of them and do well being community-ran.

**Comment by kevinsmia1939** [comment]
> Hi @kevinsmia1939 I haven't gotten around to testing the flatpak myself yet (I'm looking forward to giving it a shot!), but Schrodinger developers aren't typically involved with maintaining packages. There's many of them and do well being community-ran.

Thanks @JarrettSJohnson 
I am fine with maintaining FLatpak PyMOL, but it would be nice to have more people to keep an eye on. Where can I reach out for more?

**Comment by kevinsmia1939** [comment]
It is now published.

https://flathub.org/apps/details/org.pymol.PyMOL
