### ISSUE TITLE
occasional utf-8 codec error in get_renderer

### ISSUE THREAD

**Issue by eimrek** [schrodinger/pymol-open-source#175]
Dear pymol community,

I am trying to automate some rendering tasks with a python library. This is the code I'm using to set up the `cmd` object:

```
import pymol

_stdouterr = sys.stdout, sys.stderr
pymol.finish_launching(['pymol', '-qc'])
sys.stdout, sys.stderr = _stdouterr

from pymol import cmd
```

This works well in most cases, but sometimes I am getting the following error

```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~/opt/anaconda3/envs/aiida/lib/python3.9/site-packages/pymol/__init__.py in adapt_to_hardware(self)
    305     cmd = self.cmd
    306 
--> 307     vendor, renderer, version = cmd.get_renderer()
    308 
    309     # Quadro cards don't support GL_BACK in stereo contexts

~/opt/anaconda3/envs/aiida/lib/python3.9/site-packages/pymol/querying.py in get_renderer(quiet, _self)
    862         '''
    863         with _self.lockcm:
--> 864             r = _cmd.get_renderer(_self._COb)
    865 
    866         if not int(quiet):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
```

I am at a loss regarding how to debug this. What could be the source of this error?

**Comment by speleo3** [comment]
@eimrek What's the exact PyMOL version (with git revision) you're using? If you compile from source, can you try latest `master`?

@JarrettSJohnson @TstewDev This might be another symptom of incorrect `CScene` initialization. In that case, it should be fixed with https://github.com/schrodinger/pymol-open-source/commit/703915d7937f01cfcab0f43214f226c0e6e3210b

**Comment by eimrek** [comment]
Thanks for the quick reply @speleo3.

I have been using v2.4.0 (exactly the tagged version). I will try with `master` as well 👍

**Comment by eimrek** [comment]
Okay, ran some tests and everything seems to work well with `master`. Thanks!
