### ISSUE TITLE
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMenu'

### ISSUE THREAD

**Issue by biotech70** [schrodinger/pymol-open-source#182]
Hi. I download  open source pymol and try to install it but get below error.
![11](https://user-images.githubusercontent.com/73783725/119400513-8c2e9200-bcef-11eb-8316-b3263920b9e8.png)

**Comment by JarrettSJohnson** [comment]
Which pyqt5 version are you using?

**Comment by biotech70** [comment]
The problem was solved.

**Comment by JarrettSJohnson** [comment]
Great. If you feel the solution is beneficial for others to know, feel free to leave it here. Otherwise, I'll close the issue.

**Comment by biotech70** [comment]
yes close the issue

**Comment by gaoxj1990** [comment]
Hi, how did you fix the problem.



> The problem was solved.

**Comment by skrhakv** [comment]
Hi @biotech70,
Could you share with us how did you solve the problem?

**Comment by vn-dohyeonkim** [comment]
Hello @biotech70,
How did you solve the problem?
I am having the same problem.

**Comment by vn-dohyeonkim** [comment]
> Hello @biotech70, How did you solve the problem? I am having the same problem.

I removed pymol with `pip uninstall pymol` and `conda uninstall pymol`.
Re-installed pymol with `conda install -c conda-forge pymol-open-source`

This worked for me! :)
