### ISSUE TITLE
request for reduced functionality apbs_gui for open source pymol

### ISSUE THREAD

**Issue by jwhowarth** [schrodinger/pymol-open-source#183]
Would it be possible to commit a reduced functionality version of the apbs_gui support from the inventive pymol release into the open source version which had the most bare bones apbs support by only allowing pdb2pqr preparation of the molecule? That would still leave a significant set of enhancements for the incentive version while maintaining some level of apbs support in the open source version.

**Comment by JarrettSJohnson** [comment]
Full APBS plugin available in Open Source 3.0 c33c916
