### ISSUE TITLE
Cgo plane hidden after ray tracing

### ISSUE THREAD

**Issue by smutao** [schrodinger/pymol-open-source#184]
Hello developers, I'm currently using some cgo plane for making figures of a structure by referring to "https://pymolwiki.org/index.php/Plane_Wizard". 

I found an issue with the colored planes that after ray tracing the planes in the behind will be hidden by the planes in the front. Is there any solution to this? 

Before ray tracing, I got:
![Screen Shot 2021-06-01 at 5 35 33 PM](https://user-images.githubusercontent.com/10540422/120398509-07033880-c300-11eb-9863-acbf89ecabd3.png)

After ray tracing, I got:
![Screen Shot 2021-06-01 at 5 35 41 PM](https://user-images.githubusercontent.com/10540422/120398520-0a96bf80-c300-11eb-954b-074f84a5a2a1.png)

Many thanks!

**Comment by JarrettSJohnson** [comment]
Sorry for the very long wait, but I believe I was able to recreate. `set transparency_mode, 3` to turn on multilayer transparency seemed to do the job.

**Comment by smutao** [comment]
Hi Jarrett, many thanks for the suggestion. This command solved my issue. 🤝
