### ISSUE TITLE
Segmentation fault on cmd.load_cgo on MacOS platform

### ISSUE THREAD

**Issue by AlessioDelConte** [schrodinger/pymol-open-source#191]
Hi all,
I found a bug on the implementation of the load_cgo function on the MacOS platform that is not present in Linux, at least on my testes.
Code to reproduce the segmentation fault:
```
from pymol import cmd

cmd.load_cgo([COLOR,1,1,0,SPHERE,3,0,0,1],name="test",state=2)
```
I found out that if you create a new object, in this case "test", that has no CGO on all the states antecedents to the one set on the state parameter, a segmentation fault occurs. I tested the same exact code on Linux and it works just fine. 
Pymol version seems to not matter, I tested it in three different versions installed from source, conda and downloaded from shrodinger website

**Comment by JarrettSJohnson** [comment]
Thanks for the report. I can reproduce and have identified where the problem is. Will fix in a moment.
