### ISSUE TITLE
Can not use "preset" in Embedded Pymol 

### ISSUE THREAD

**Issue by Bio-Otto** [schrodinger/pymol-open-source#192]
Hi! 

I am trying to use **preset > ligans_sites > cartoon** options in pymol embedded in pyside2  but giving error `NameError: name 'preset' is not defined
`

**Comment by JarrettSJohnson** [comment]
Thanks for the report. I can't seem to reproduce this issue. The preset works fine for me with PyMOL + PyQt5. Are there any other facilities from the menu that don't work for you?

**Comment by Bio-Otto** [comment]
I couldn't find any resources on this. Do you have a suggestion or solution for this @speleo3 ?

**Comment by speleo3** [comment]
`self._pymol.preset.ligand_sites` is not attached to the `cmd` object. That means you have to use the `_self` argument to pass in the correct `cmd` object.
```python
self._pymol.preset.ligand_sites(selection='all', _self=self._pymol.cmd)
```

**Comment by Bio-Otto** [comment]
Thank you so much for the clear explanation @speleo3. I appreciate it.
