### ISSUE TITLE
get_area treatement of solvent && flag ignore

### ISSUE THREAD

**Issue by brianosmith** [schrodinger/pymol-open-source#196]
Some time recently (possibly since v2.5 and the flag ignore fix [PYMOL-3052](https://github.com/schrodinger/pymol-open-source/commit/1659fde83d2a125f86cad13414cead6b8f74abe9)) the behaviour of get_area and dots representation changed with respect to solvent (water) molecules. The [documentation on pymolwiki ](https://pymolwiki.org/index.php/Get_Area) now needs to be made consistent with the current behaviour and/or the historical behaviour needs to be restored.

I'm happy to update pymolwiki if the current behaviour is the intended one.

Issue:
**previously** get_area (and dots representation) always ignored solvent molecules (at least when the mode was set to dot_solvent=1) even after issuing "flag ignore, none".
**currently** (v2.5.2, some time after v2.3.3) get_area (and dots) includes solvent molecules after issuing "flag ignore, none".

How to reproduce:
e.g. follow [this example](https://pymolwiki.org/index.php/Get_Area#Example_1_-_starting_with_a_complex_in_a_single_file) and get e.g. ~7614 A^2 for the alpha1 subunit (after issuing "flag ignore, none") vs ~7579 A^2 calculated with previous versions and/or with "flag ignore, none ; flag ignore, solvent"

Proposal:
the current behaviour is actually "better" (well, more flexible at least and the ignore flag is treated consistently) in that the user has the option to include solvent in a calculation if they so choose, but if that is the intended behaviour, we should update the wiki documentation to make this clear.

**Comment by JarrettSJohnson** [comment]
Thanks for updating the wiki! Closing.
