### ISSUE TITLE
Installation issue with ambertools

### ISSUE THREAD

**Issue by stefdoerr** [schrodinger/pymol-open-source#206]
Hi, sorry if this is a repost, I'm just not sure if the feedstock issues are being tracked by somebody or who I should report this issue to.
Practically it's currently impossible to install the latest versions of both ambertools and pymol in the same env. Seems like pymol is trying to downgrade libnetcdf (I think?).

You can find more details here.
https://github.com/conda-forge/pymol-open-source-feedstock/issues/12

If this is not the right issue tracker feel free to close the issue.

Many thanks!

**Comment by JarrettSJohnson** [comment]
Hi, @stefdoerr , Schrodinger doesn't maintain the conda-forge pymol feedstock. The issue you posted though should be the correct place.
