### ISSUE TITLE
VRML export of distance measurements broken

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#209]
The exporter returns always `radius 0.000000` for sphere and cylinder primitives, resulting in empty objects when loaded into blender

Here an example

```
Transform {
 translation -29.105999 24.090500 -0.028000
 rotation 0.982072 0.000000 0.188507 2.089593
 children [
  Shape {
   geometry Cylinder {
    radius 0.000000
    height 4.019477
    bottom FALSE
    top    FALSE
   }
   appearance Appearance {
   material Material { diffuseColor 1.0000 1.0000 0.0000 
                       specularColor 0.8 0.8 0.8 
                       shininess 0.8 }
   }
  }
  Transform {
   translation 0.0 2.009739 0.0
   children Shape {
    geometry Sphere { radius 0.000000 }
    appearance Appearance {
   material Material { diffuseColor 1.0000 1.0000 0.0000 
                       specularColor 0.8 0.8 0.8 
                       shininess 0.8 }
    }
   }
  }
  Transform {
   translation 0.0 -2.009739 0.0
   children Shape {
    geometry Sphere { radius 0.000000 }
    appearance Appearance {
   material Material { diffuseColor 1.0000 1.0000 0.0000 
                       specularColor 0.8 0.8 0.8 
                       shininess 0.8 }
    }
   }
  }
 ]
}
```

**Comment by JarrettSJohnson** [comment]
Hi, I can't seem to reproduce. Saving a CGO sphere or even a molecule with spheres correctly shows all spheres and contains a non-zero radius for each sphere primitive.

Details of what I used:
```
from pymol import cgobuilder as cb

builder = cb.CGOBuilder()

sphere = cb.Sphere(center=cb.Point(3, 3, 3),
                          radius=1.5,
                          color=cb.Color(1, 0.5, 0.0, 1))
builder.add(sphere)

builder.load("test")
```

```
fetch ala
as spheres
```

**Comment by JarrettSJohnson** [comment]
Ah, I misread the title. I assumed all spheres and cylinders were broken.

**Comment by JarrettSJohnson** [comment]
I still might need more information. When trying to export alanine with a distance measurement, they appear fine for me.

![image](https://user-images.githubusercontent.com/36459667/144647381-0c32ecfc-eb68-4cc4-ac03-a21476af1d6b.png)

**Comment by giagitom** [comment]
Ok I found the cause.
I was using a pse were dash_radius was set to 0 for some reason. With radius to 0 Dashed lines are still visible in real time but when exported to VRML they have 0 radius.

**Comment by JarrettSJohnson** [comment]
By chance does your dash lines show up when ray traced?

**Comment by giagitom** [comment]
Yes they appear when ray traced.

**Comment by JarrettSJohnson** [comment]
`dash_radius` is zero by default, so there's something else at play here. Can you email me a session file or reproduceable steps that shows this behavior?

**Comment by giagitom** [comment]
I'm unable to reproduce the issue in the same pse file..
Maybe something I have done in the middle but not saved it sadly.. 

If i find a way to reproduce it I will let you know

**Comment by JarrettSJohnson** [comment]
Thanks. I'll close this in the meantime. Feel free to reopen if something weird happens again.
