### ISSUE TITLE
Object named polymer warning

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#21]
Hi developers!

The `polymer.protein` and `polymer.nucleic` was the chosen class names instead of `protein` and `nucleic`, I imagine that was to avoid clashes with preexisting sessions and scripts.

So now could the warning about object named "protein" be removed? My analysis says 'WARNING protein...' thousand of times.

**Comment by speleo3** [comment]
Hi @pslacerda - you are right, the warnings can probably be removed.

You can use the `feedback` command to suppress the warnings for now:

```python
cmd.feedback("disable", "executive", "warnings")
```
