### ISSUE TITLE
Need to port from distutils to setuptools

### ISSUE THREAD

**Issue by adamjstewart** [schrodinger/pymol-open-source#217]
The `setup.py` for pymol still uses distutils. Distutils was [deprecated in Python 3.10 and will be removed in 3.12](https://docs.python.org/3/whatsnew/3.10.html#distutils). Package authors are encouraged to use setuptools (should contain identical functionality and more) or another build backend like flit/poetry.

Porting should be as simple as replacing all `distutils.sysconfig` with `sysconfig` and all other calls to `distutils` with `setuptools`. In fact, pip already does the latter automatically behind the scenes. In the case of pymol, `monkeypatch_distutils.py` seems to be messing up argument parsing, because a `pip install .` in the source directory crashes when some setuptools flags are used.

**Comment by TstewDev** [comment]
Hello Adam, we are aware of this issue and have a ticket for it already! I'll get back to you here once it's fixed and then close the issue.

**Comment by JarrettSJohnson** [comment]
`disutils` replacement via `sysconfig` & `cmake` by 74ffc07ea75fe2237b278de095ba95cf843d08c6 and #362 
And `pip` installation addressed by # #363
