### ISSUE TITLE
No module named 'pymol.cmd'

### ISSUE THREAD

**Issue by biotech70** [schrodinger/pymol-open-source#219]
Hi during the execution of Pymol I get the following error:

_Traceback (most recent call last):
  File "/home/proteininstitute/miniconda3/lib/python3.8/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "/home/proteininstitute/miniconda3/lib/python3.8/site-packages/pymol/__init__.py", line 558, in <module>
    import pymol._cmd
ModuleNotFoundError: No module named 'pymol._cmd'_

**Comment by JarrettSJohnson** [comment]
Was this self built? The pymol open-source conda forge package?

**Comment by biotech70** [comment]
No, I used your source code. I download it from Github and install it in ubuntu 20.04, but my bashrc file was deleted and after that, I get this error for Pymol execution.

**Comment by biotech70** [comment]
Of course, I tried again to install the Pymol using your source code, which shows this error, but the following error was displayed.
![pymol error](https://user-images.githubusercontent.com/73783725/151057497-63c7d4f1-207b-40a7-9315-351848ca1702.png)

**Comment by smiles724** [comment]
I met a similar issue, which reports it cannot find pymol_cmd.

Is there anyone who can provide any solution to tackle it? I would really appreciate it!
![image](https://user-images.githubusercontent.com/39299863/153347448-d32a24e6-562f-485f-b30b-83981101b8f3.png)

**Comment by speleo3** [comment]
@smiles724 try something like `sudo apt install libgl1`

Other packages which provide `libGL.so.1`: https://packages.ubuntu.com/search?suite=focal&arch=amd64&mode=exactfilename&searchon=contents&keywords=libGL.so.1

**Comment by smiles724** [comment]
Great thanks, it works!!!

**Comment by JarrettSJohnson** [comment]
Going to close. The issue from smiles724 is different than the original post and has been resolved. The image from biotech70 suggests that the python included in the environment does not match the platform config of what it's being ran on.

**Comment by marking2004** [comment]
> Hi during the execution of Pymol I get the following error:
> 
> _Traceback (most recent call last): File "/home/proteininstitute/miniconda3/lib/python3.8/site-packages/pymol/**init**.py", line 72, in import pymol File "/home/proteininstitute/miniconda3/lib/python3.8/site-packages/pymol/**init**.py", line 558, in import pymol._cmd ModuleNotFoundError: No module named 'pymol._cmd'_

I got the same error too. 
How can I tackle it?
