### ISSUE TITLE
Grouping and object names with comma (,)

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#22]
Hi developers!

Objects can't have `,` in their names because functions wouldn't work as intended. Seems that it should be deprecated with an warning. Should be replaced with `_` like as in `;`.

For instance:

```python3
>>> cmd.centerofmass('object,with,comma')
[...]
pymol.CmdException:  Error: mass is zero
 parser: matching commands:
  center        centerofmass
```

Of course it also doesn't works in PyMOL syntax:

```python3
> centerofmass object,with,comma
[...]
ValueError: invalid literal for int() with base 10: 'with'
```

Now a question, I want to have dots (`.`) both as group delimiter (explicit groups) and "regular" name. For instance:
    protein_name.origin.file.name

`protein_name` and `origin` are both groups, but `file.name` isn't. I messed with `set group_auto_mode`, tried to `cmd.group` explicitly and so on. Because of this I tried to replace some `.`s with `,`s.

**Comment by pslacerda** [comment]
Just a note: I spent days to figure out that my problem in grouping and (yes!) visualization was because of an `,`.

**Comment by speleo3** [comment]
Commas are replaced with underscore, at least in all cases I've tried. Do you have an example were it's not replaced? I agree that a warning should be printed if any characters got replaced.

The grouping you describe is absolutely possible:

```python
cmd.set('group_auto_mode', 1)
cmd.group('protein_name')
cmd.group('protein_name.origin')
cmd.fragment('ala', 'protein_name.origin.file.name')
```

See `group_auto_mode` documentation here: https://pymol.org/d/setting:group

**Comment by pslacerda** [comment]
Thank you for the answer and sorry for the noise. I meant `protein_name.ORIGIN.WITH.DOTS.filename`:

```python
set group_auto_mode 0
group protein_name
group protein_name.ORIGIN.WITH.DOTS
group protein_name, protein_name.ORIGIN.WITH.DOTS
```

**Comment by JarrettSJohnson** [comment]
This seems like a good approach to address your question. Are you coming across any other parsing issues?

**Comment by pslacerda** [comment]
I'm done. Closing this issue.

**Comment by pslacerda** [comment]
I replaced all `.`s with `_`s to have an way to know existing groups (splitting names from `cmd.get_object_list()`) on a big session of about 109 protein structures with 1694 objects.

I'm really needing to figure out existing groups. The `_` was needed to parse groups correctly.

**Comment by speleo3** [comment]
how about `cmd.get_names_of_type("object:group")`
https://pymolwiki.org/index.php/Get_names_of_type

**Comment by pslacerda** [comment]
Perfect! Is here the right place to ask such questions?

**Comment by speleo3** [comment]
@pslacerda the better place would actually be the pymol-users mailing list:
http://pymol.org/maillist

**Comment by pslacerda** [comment]
Thank you!
