### ISSUE TITLE
strange error that app/org.pymol.PyMOL/master is not installed

### ISSUE THREAD

**Issue by taraspinosa** [schrodinger/pymol-open-source#223]
![Screenshot 2022-02-15 19 48 26](https://user-images.githubusercontent.com/99774371/154175650-4d7ef8d8-8c58-4e83-a553-c83c0cecdf74.png)

I am using a Lenovo Chromebook Duet on ChromeOS v97.0.4692.102. The Termina is Debian 11 bullseye. This is an ARM device (some more info about graphics below).

![Screenshot 2022-02-15 20 01 49](https://user-images.githubusercontent.com/99774371/154176248-1d479af2-06eb-490f-b205-9c006f6fce90.png)

I have little experience with UNIX, nor any luck with finding help through Google, I apologize if this is not the right place.
(And before you ask why I didn't just use the version in the Debian repo, it's unusable. It has terrible flickering and freezing and graphical glitching.)

EDIT: I am stupid. Disabling GPU acceleration flag fixed the flickering in the Debian repo version.

**Comment by JarrettSJohnson** [comment]
Apologies for the late response, but I would approach the PyMOL flatpak package authors about this issue.
