### ISSUE TITLE
Pymol for mac not running python scripts

### ISSUE THREAD

**Issue by Adele-Williamson** [schrodinger/pymol-open-source#229]
Hello, I'm trying to run python scripts in Pymol but this does not work via the 'run' button (my .py script is greyed out and not selected) or via command-line (run color_h.py). I also cannot import it (import color_h gives me ImportError: No module named color_h).

Any suggestions? I'm using MacPyMOL: PyMOL v1.8.4.0 Enhanced for Mac OS X

Thanks!

**Comment by JarrettSJohnson** [comment]
Does the same occur with newer versions of PyMOL. We haven't supported that version in over several years.

**Comment by JarrettSJohnson** [comment]
Closing. Please use a more updated version if you haven't already.
