### ISSUE TITLE
How to get objects from selection?

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#23]
I need to get object names from a selection like `protein_name.*.method.site` . However I didn't found the name of a model object.

```python
model = cmd.get_model(sel)
print(dir(model))
print(dir(model.atom[0]))
```

Because iterate has exposed a `model` attribute, I'm using:

```python
stored.models = set()
cmd.iterate(sel, 'stored.models.add(model)')
```

I'm more into `get_model()` because `iterate` really don't sounds that good for it. I imagine that iterate don't pickle the function/lambda because the scope would be lost or messed, need to have some standard argument, or whatever. It doesn't matter that much because it sounds better for console than scripting.

Now the question: Is there an appropriated way? How to get the model attribute from an atom?

**Comment by speleo3** [comment]
I assume you already found [cmd.get_object_list()](https://pymolwiki.org/index.php/Get_object_list) (you mentioned it in https://github.com/schrodinger/pymol-open-source/issues/22#issuecomment-466164317 )
