### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MilesYyh** [schrodinger/pymol-open-source#232]
I was using python on the linux ,Could u help me how to make it "ImportError: libGL.so.1: cannot open shared object file: No such file or directory"???

Thank very much

Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pymol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymol/__init__.py", line 614, in <module>
    import pymol._cmd
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
>>>

**Comment by JarrettSJohnson** [comment]
You may have to grab a package that includes that library.

`sudo apt install libgl1` may do the trick.

**Comment by mlnance** [comment]
Posting to say that @JarrettSJohnson 's solution worked for me on an Ubuntu machine
