### ISSUE TITLE
Failed to download resource "pymol_bottle_manifest"

### ISSUE THREAD

**Issue by structuralcbh** [schrodinger/pymol-open-source#238]
Hello,

An error reported when I was trying to install pymol via Homebrew (brew install brewsci/bio/pymol).

Downloading https://ghcr.io/v2/brewsci/bio/pymol/manifests/2.5.0_1
curl: (22) The requested URL returned error: 404                              

Error: pymol: Failed to download resource "pymol_bottle_manifest"
Download failed: https://ghcr.io/v2/brewsci/bio/pymol/manifests/2.5.0_1

Anyone knows what's wrong?

Thanks a lot.

**Comment by ahmedaq** [comment]
Hi, I am facing the same problem on my MacBook Pro (with Monterey 12.4). Any solution for this will be highly appreciated.

**Comment by lbj70** [comment]
me too - same problem

**Comment by structuralcbh** [comment]
Try MacPorts. I was able to install it via it.

**Comment by ahmedaq** [comment]
Thanks a heap structuralcbh! Installing by MacPorts took some time but it worked! 

Briefly, the procedure is:

1. Download MacPorts for your Mac from https://www.macports.org/install.php <https://www.macports.org/install.php> 
2. Install it
3. Add MacPorts to your path by running the following command in the Terminal:
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
4. Install pymol using MacPorts using the following command in the Terminal:
sudo port install pymol

Hope this is helpful for all who are having difficulty in installing pymol on Mac.

-- Ahmed

**Comment by lucblassel** [comment]
Same error, 
on macos monterey. 
I was also able to install it with macports but it would be better if the URL was fixed so homebrew works.
