### ISSUE TITLE
fit error

### ISSUE THREAD

**Issue by schmalgo** [schrodinger/pymol-open-source#24]
Using the [wiki example ](https://pymolwiki.org/index.php/Fit) returns:
**ExecutiveRMS-Error: No atoms selected.**

PyMOL versions tested (linux): 2.1.0, 2.3.0, 2.3.0 (anaconda)

**Comment by speleo3** [comment]
Was missing `segi` altering.

Fixed: https://pymolwiki.org/index.php?title=Fit&diff=12893&oldid=10290
