### ISSUE TITLE
When exporting a gif movie, the colors become weird.

### ISSUE THREAD

**Issue by AustinApple** [schrodinger/pymol-open-source#240]
When I tried to export a gif movie, colors in some regions become weird.
Attached is an example
<img width="550" alt="Screen Shot 2022-06-23 at 9 12 53 PM" src="https://user-images.githubusercontent.com/42490261/175448623-98015732-9daa-40cc-a04d-6565872bbaf0.png">
.

**Comment by jrom99** [comment]
Same here, on Ubuntu 23.10 (GNOME 45 on Wayland)

**Comment by JarrettSJohnson** [comment]
Seems like it's an issue with ffmpeg. https://stackoverflow.com/questions/58832085/colors-messed-up-distorted-when-making-a-gif-from-png-files-using-ffmpeg

I've addressed it in the aforementioned commit.
