### ISSUE TITLE
Compatibility of sessions between PyMOL (<=) 2.3 and PyMOL 2.5

### ISSUE THREAD

**Issue by jr-marchand** [schrodinger/pymol-open-source#244]
Hi there,

I have observed a problem of compatibility between certain PyMOL sessions written with PyMOL 2.3 or earlier (display message: "loading version 2.001000 session") and trying to load them/modify them with PyMOL 2.5: segfault at session opening on Windows 10, segfault at session saving on Linux/CentOS7 (with diverse 2.5 packages, including the latest version 2.5.3). This seems to be a rather inconsistent problem, as I can open/edit/save some <= 2.3 sessions but not other sessions with >= 2.5. And also different behaviors between the Windows- and Linux-verse (ie can't open in Windows, can open but can't save in Linux). It may seem to be more frequent with sessions containing many objects rather than very light sessions, but that might be simple sampling bias.
I didn't find a ticket on this backwards compatibility of sessions in the repo.
Please let me know what additional information I can share to help, however, I can definitely not share the sessions of interest.

Best wishes,
JR

**Comment by JarrettSJohnson** [comment]
This is likely a bug and not due to session compatibility. Loading sessions partially may help, but if there's a session file that is shareable which also crashes feel free to email me at jarrett.johnson@schrodinger.com and I can take a look.
