### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by shaoqx** [schrodinger/pymol-open-source#250]
When I tried to install pymol as a library (`pymol-bundle`) using conda I found it limit python version to be <3.9. Is there any specific reason for this?

The reason I'm asking is that I wish to incorporate pymol's selection function in one of my enzyme modeling workflows but my workflow is written under python 3.9

All the Best,
QZ

**Comment by JarrettSJohnson** [comment]
There's no relevant reason for this anymore and should be upgraded. We're away for the next week but when we get back, I'll see about getting this in sooner than our next maintenance patch since we just did one a couple of days ago.

**Comment by shaoqx** [comment]
Any news about the next patch? No rush but if the next patch is far, could there be another way to remove such limitation by user?

**Comment by JarrettSJohnson** [comment]
I'm about a month behind of the a monthly patch so I hope to get this in by start of November. I'll have at least an update for you at the latest by then if it's not out yet. This is a very reasonable request to have supported ASAP.

**Comment by shaoqx** [comment]
Hope all is well! Need PyMol in another part of my workflow again haha. Just to check out how's it going.

**Comment by shaoqx** [comment]
Woohoo, it works! Thank you!
