### ISSUE TITLE
GLTF export support?

### ISSUE THREAD

**Issue by JimSEOW** [schrodinger/pymol-open-source#26]
https://sourceforge.net/p/pymol/mailman/message/36336504/

Like to learn if there is any interest on supporting GLTF export from pymol?

**Comment by JarrettSJohnson** [comment]
Hi @JimSEOW , we plan to have some GLTF export support by the release after end of summer.

**Comment by speleo3** [comment]
commit b9168c0ef1d12e5bdbb767ed44747d02acb10ce1 adds GLTF export, using [collada2gltf](https://github.com/KhronosGroup/COLLADA2GLTF) under the hood

**Comment by azhx** [comment]
This doesn't seem to be on the latest conda release. Was it meant to be? If not, when is it likely to be in a conda release?

**Comment by speleo3** [comment]
@azhx We don't have a target date for the final PyMOL 2.4 release yet, it will likely be a few more months.

Alpha builds are available, you can install them like this:
```
conda install -c schrodinger schrodinger/label/alpha::pymol collada2gltf
```
Export a GLTF file from PyMOL with:
```
save test.gltf
```

**Comment by JarrettSJohnson** [comment]
[PyMOL 2.4](https://pymol.org/dokuwiki/?id=media:new24) was released with glTF export support on May 20th. Closing this issue.
