### ISSUE TITLE
Not able to load partial pse using API

### ISSUE THREAD

**Issue by VonBoss** [schrodinger/pymol-open-source#266]
I am unable to merge two Pymol session files using the API. 

This works: 
load filename_1
load filename_2, partial=1

This does not work:
cmd.load('filename_1')
cmd.load('filename_2", 'partial=1')

The API command disregards the current session (filename_1) and replaces it with filename_2.

I am trying to merge several Pymol session files as part of a python program. 

Version 2.5.4

**Comment by JarrettSJohnson** [comment]
I believe you want
```
cmd.load('filename_2', partial=1)
```
where `partial` is a name argument and not part of the string literal.

**Comment by VonBoss** [comment]
That was simple. Works perfectly.
Thank you!

**Comment by VonBoss** [comment]
I am able to load multiple session files now but Pymol crashes with a segmentation fault when I try to save. Do you have any ideas what the issue might be?

**Comment by JarrettSJohnson** [comment]
Hard to tell without a stacktrace or anything. If you can provide that or a minimally reproduceable example, feel free to email me with it at jarrett.johnson@schrodinger.com
