### ISSUE TITLE
grid mode background color per grid cell

### ISSUE THREAD

**Issue by speleo3** [schrodinger/pymol-open-source#267]
_This is a feature request._ I would like a visual separation of the [grid_mode](https://pymolwiki.org/index.php/Grid_mode) grid cells. One way to do this could be alternating background colors. I already have some code for this and would be happy to make a pull request.

![grid_mode-backgrounds](https://user-images.githubusercontent.com/1239490/206849236-e534131c-bfe2-421e-8506-a34587d1d37b.png)

**Comment by TstewDev** [comment]
I think this is a great idea and I'll show it to the rest of the team!

**Comment by JarrettSJohnson** [comment]
Apologies for the late response--was gone for all of December. Commits merged. Thanks for the PR!

**Comment by speleo3** [comment]
No worries Jarrett, hope you had a great trip. Happy New Year! Thanks for merging :)
