### ISSUE TITLE
cannot find freemol package

### ISSUE THREAD

**Issue by richor** [schrodinger/pymol-open-source#27]
many .py file depends on freemol package, however, I cannot find it.
For example, in "computing.py", line98
```
        try:
            from freemol import mengine
```

**Comment by speleo3** [comment]
http://freemol.org/  (server seems down at the momemt)
https://www.bioinformatics.org/wiki/FreeMOL_Open-Source_Modeling_Platform
https://www.bioinformatics.org/cgi-bin/viewvc.cgi/freemol/trunk/
