### ISSUE TITLE
Stable release branch tags

### ISSUE THREAD

**Issue by mbanck** [schrodinger/pymol-open-source#273]
Looks like pymol is at 2.5.4 according to https://pymol.org/2/#download but in this repo only a 2.5.0 tag is available, this made us (Debian/Ubuntu) miss those bugs fixes.

Would it be possible to tag those point releases so users get bug fixes? Or am I missing something and either you're moving the tags forward (which would be pretty bad for reproducibility) or don't commit the stable branch fixes to github?

**Comment by cgohlke** [comment]
See #50.

**Comment by mbanck** [comment]
Yeah I figured in the meantime. Disappointing, but oh well.

I think there's no shame in having incentive builds that add on major feature, but it'd sure be nice to keep fixing bugs in the open source version.

**Comment by JarrettSJohnson** [comment]
Are there particular bug fixes that you see in incentive that are not in Open Source? Typically as soon as we find a bug fix, we will usually bring it to open source immediately or, at the latest, at the point where a minor version is released (to keep incentive and open-source synced). Open source will usually have bug fixes faster than incentive.

**Comment by mbanck** [comment]
Yeah, I'm talking about the bug fixes between incentive 2.5.0 an 2.5.4 that affect the open source codebase - I guess it'd be possible to backpatch those for an outside contributor who is interested in this, but I personally don't have the time for this (packaging pymol for Debian/Ubuntu as part of my spare volunteer time). Best we can do is keep an eye for new tags/release (this is being tracked automatically) and upload those, hence my wish for patch releases fixing bugs.

But no worry, I guess if you find a really catastrophic bug you'd issue a new open source release one way or the other, and let's keep it at that and see what maybe future changes bring.
