### ISSUE TITLE
ImportError: symbol not found in flat namespace '_PlugIOManagerFreeAll'

### ISSUE THREAD

**Issue by gauravdiwan89** [schrodinger/pymol-open-source#274]
Hello

I installed the latest version of pymol-open-source on my Macbook running Monterey 12.3.1 and Python 3.9

However, I run into an error while attempting to launch Pymol as follows

```
Traceback (most recent call last):
  File "/Users/gaurav/pymol/lib/python3.9/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "/Users/gaurav/pymol/lib/python3.9/site-packages/pymol/__init__.py", line 558, in <module>
    import pymol._cmd
ImportError: dlopen(/Users/gaurav/pymol/lib/python3.9/site-packages/pymol/_cmd.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_PlugIOManagerFreeAll'
```

I had a previously installed version of pymol-open-source. However, it was more than a year old and needed to be updated anyway. I deleted the folder for that installation. I hope that's fine.

Please let me know what I can do. Thanks!

**Comment by JarrettSJohnson** [comment]
Are you able to tell if "contrib/uiuc/plugins/molfile_plugin/src/PlugIOManagerInit.c" was compiled?

**Comment by JarrettSJohnson** [comment]
Closing as it's been well over a year and noone else has had this issue. Feel free to re-open if this is still occurring.
