### ISSUE TITLE
Doubt about selection algebra

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#275]
Dear Pymol developers, the 3AVZ structure contains a peptide which we cannot select. We tried "bymolecule  chain B and resi 1" however it keeps expanding for the hole protein plus peptide. It is a non standard one with ATOMs and HEATMs. What can we do to select only the peptide?

**Comment by Valdes-Tresanco-MS** [comment]
I think it would be like this to select the residue:
```select single_res, chain B and resi 1```
and like this to select the whole chain:
```select chain_B, bychain chain B and resi 1```

**Comment by pslacerda** [comment]
It would be, but we need something that also works for other 700 structures.

Some peptides are assigned the same chain as the protein, so it wouldn't
work.


Em ter., 31 de jan. de 2023 17:20, Mario Sergio Valdés Tresanco <
***@***.***> escreveu:

**Comment by Valdes-Tresanco-MS** [comment]
I don't think there is a command that allows selecting a peptide in the same chain as the protein through entity expansion. An option could be an iteration from the selected residue:

```python

from pymol import cmd

# create the selection with at least one residue
cmd.select("bbb", "resi 301")

# Exapand the selection
for x in range(cmd.count_atoms()):
    cmd.select("bbb", "byres bound_to bbb")
    if cmd.count_atoms() == cmd.count_atoms("bbb"):
        break
```
This will allow you to select the peptide only. However, in some cases, it may fail, for example in the posted PDB. For some reason, PyMOL interprets that the residue `A/CYS145` is bound to `B/HSV6` (distance `B/HSV6/C` and `A/CYS145/SG` = 2.2 A).
HTH!

**Comment by pslacerda** [comment]
There is, bymolecule works just fine for most cases.

Em ter., 31 de jan. de 2023 20:21, Mario Sergio Valdés Tresanco <
***@***.***> escreveu:

**Comment by pslacerda** [comment]
I'll check the distances and let you know. Anyway, any idea how the
www.pdb.org interpret them as different molecules?

Em ter., 31 de jan. de 2023 21:23, Pedro Lacerda ***@***.***>
escreveu:

**Comment by pslacerda** [comment]
I didn't understand your code and also don't know what bbb means.

**Comment by Valdes-Tresanco-MS** [comment]
Reviewing the documentation, I believe the code is a rudimentary version of bymolecule. "bbb" is a random name for the selection. I think the problem here is that pymol is interpreting the atoms I mentioned above as bonded.

**Comment by pslacerda** [comment]
Yes, C and S seems to be bonded in the 1.81~2.55 Å range. This render
bymolecule identification harder at least as you observed 2.2 Å between
B/HSV6/C and A/CYS145/SG.

As we here identified this single case so far (3AVZ) from 700 yet, we'll do
it manually.


Em ter., 31 de jan. de 2023 22:19, Mario Sergio Valdés Tresanco <
***@***.***> escreveu:

**Comment by pslacerda** [comment]
I tried all `connect_mode`s (including 1, that was supposedto respect the `CONNECT` records on the PDB file) but only load mmtf worked.
