### ISSUE TITLE
"ReadMOLFile-Error: bad atom count" on Pymol

### ISSUE THREAD

**Issue by terrilvallikalam** [schrodinger/pymol-open-source#277]
[SDF Files.zip](https://github.com/schrodinger/pymol-open-source/files/10582244/SDF.Files.zip)
<img width="632" alt="PyMol_window" src="https://user-images.githubusercontent.com/75184507/216691472-519ff92f-1ff5-4061-8886-e4543d85d5a4.png">

Hi,

I am running into this error on Pymol when opening a .sdf file. I have downloaded a large number of .sdf files from PubChem and wanted to check that they would open in Pymol. I opened the .sdf file in a text editor and copied the first conformer information in another text file and tried to open it in Pymol but it gave me "ReadMOLFile-Error: bad atom count". However, when I downloaded the .sdf file from Pubchem, the file opened on Pymol with no problem.

I compared both of the .sdf files on text edit and they looked exactly the same. Not sure why one file is opening and the other file is giving an error.

I've attached a zip of both the files. "237.sdf" is the one that is not opening and "Conformer3D_CID_237.sdf" is opening.

Any help would be appreciated!

**Comment by JarrettSJohnson** [comment]
This might be a issue with your text editor saving files. On top of 237.sdf I see this:

![image](https://user-images.githubusercontent.com/36459667/231913525-580cd14d-e52f-49d6-b771-def5fbb20a8b.png)

First line for reading these files should just be the number of atoms.

**Comment by JarrettSJohnson** [comment]
Closing this issue since I believe the image identifies the problem (non-standard SDF header).
