### ISSUE TITLE
Is this repository missing some release tags?

### ISSUE THREAD

**Issue by alerque** [schrodinger/pymol-open-source#280]
I'm the maintainer for the Arch Linux package. I've been having folks drop out of date flags on the package (which is at v2.5.0) saying that v2.5.4 is out, but I don't see any new tags or even commits with release info in them in this repository that could get packaged up as a specific version.

Are our users hallucinating versions that don't exist or are there tags missing from this repository or is there some other channel I should be reviewing?

**Comment by JarrettSJohnson** [comment]
See #50

**Comment by JarrettSJohnson** [comment]
We don't have release cycles for open-source PyMOL. This repository is just maintained and available openly. Open-source packages are currently currently managed by Schrodinger. Bug fixes that affect open-source are pushed to this repository relatively immediately after we have a fix before incentive PyMOL updates. In other words, open-source users would get the bug fixes before incentive users do.

As mentioned in the attached issue, we may reconsider how this is done in the future.
