### ISSUE TITLE
Receiving 2 errors during Installation

### ISSUE THREAD

**Issue by egmnb** [schrodinger/pymol-open-source#283]
Dear All,

If you have already experienced below issues, could you please kindly let me know how you solved them?

![First Issue](https://user-images.githubusercontent.com/121421379/231440414-d50c7b98-ccaa-4d14-8ce8-668ff3ea0e40.PNG)
![Second Issue](https://user-images.githubusercontent.com/121421379/231440859-706bc381-54df-479b-b1bb-d2f75762fdeb.PNG)

**Comment by JarrettSJohnson** [comment]
Unfortunately, the Open-Source PyMOL Github issue tracker doesn't provide support for installers on pymol.org. You would need to contact Schrodinger Support. You can also use the windows portable (.zip) file to evaluate PyMOL for 30 days which doesn't require installation.
