### ISSUE TITLE
Educational-Use-Only PyMOL Builds

### ISSUE THREAD

**Issue by brendenbarcellona** [schrodinger/pymol-open-source#284]
Whenever I try to sign up for educational license it doesn't let me. Anyone know anything to help or maybe could try getting an educational license to see whats up.

<img width="441" alt="Screenshot 2023-04-12 182505" src="https://user-images.githubusercontent.com/110497848/231599624-439da55b-27fb-41d1-a0dd-95b5e6b59b91.png">
<img width="285" alt="Screenshot 2023-04-12 182310" src="https://user-images.githubusercontent.com/110497848/231599629-bfb28f1a-2ecc-43c4-a106-ba18cf909333.png">

**Comment by JarrettSJohnson** [comment]
Issue might've been resolved last night. Can you try again?
