### ISSUE TITLE
Volume in different states ignore assigned color ramps

### ISSUE THREAD

**Issue by Finnem** [schrodinger/pymol-open-source#289]
Hi!
I ran into the following issue playing around with volumes: When using multiple states any volume but the volume at state 1 will be assigned a default color ramp and it seems impossible to change it.

```python
cmd.volume_ramp_new("test1_ColorRamp", [\
    0.008676594531528439, 0.19215686274509805,0.21176470588235294,0.5843137254901961, 0.03,\
    0.14422443906344906, 0.9999231064975009,0.9976163014225298,0.7454056132256824, 0.005,\
    0.27977228359536965, 0.6470588235294118,0.0,0.14901960784313725, 0.1,\
])
cmd.volume("test1", "RegularData_0_density", "test1_ColorRamp",  state = 1)    

cmd.volume_ramp_new("test2_ColorRamp", [\
    0.008676594531528439, 0.19215686274509805,0.21176470588235294,0.5843137254901961, 0.03,\
    0.14422443906344906, 0.9999231064975009,0.9976163014225298,0.7454056132256824, 0.005,\
    0.27977228359536965, 0.6470588235294118,0.0,0.14901960784313725, 0.1,\
])
cmd.volume("test1", "RegularData_0_density", "test2_ColorRamp",  state = 2)
```

Results in the following:
State 1:
![grafik](https://github.com/schrodinger/pymol-open-source/assets/15279480/a4848ecb-2fbc-4cc7-a9e0-ec7ab414c40d)
State 2:
![grafik](https://github.com/schrodinger/pymol-open-source/assets/15279480/5a8b127f-197b-4495-84e6-26897940e201)
 
The images should be the same (as test2_ColorRamp and test1_ColorRamp are the same) but they are obviously not.
The color ramp can also not be changed in the UI (also not through the panel interface and not to default color ramps such as fofc).

The full code to produce this outcome:
[volume_test.zip](https://github.com/schrodinger/pymol-open-source/files/11610900/volume_test.zip)

**Comment by JarrettSJohnson** [comment]
Thanks for the report. Let me know if this latest commit works for you.
