### ISSUE TITLE
Installation Issues in Google Colab

### ISSUE THREAD

**Issue by RafiBrent** [schrodinger/pymol-open-source#290]
I've been using PyMOL for a project in a Google Colab notebook, which previously worked well using the condacolab package to install PyMOL via the command `mamba install -c schrodinger pymol-bundle`. However, Colab recently updated to Python >3.10 (it currently runs version 3.10.11), and the above installation command no longer works (screenshot of error message attached below). How would you recommend that I resolve this issue? I'm using a relatively limited subset of PyMOL functionality so a more limited installation which is compatible with Python >3.10 would also be beneficial. I would be happy to provide more information if necessary, and I really appreciate your help with this.

<img width="860" alt="PyMOL_Installation_Error_Message" src="https://github.com/schrodinger/pymol-open-source/assets/105883594/095823ea-61af-477e-af6e-11e973f231ea">

**Comment by JarrettSJohnson** [comment]
Can you try now? They've been updated to support Python 3.10.

**Comment by RafiBrent** [comment]
Yes, the command works now. Thanks for your help
