### ISSUE TITLE
Python function calls are blocking in PymolConsole but not in system shell

### ISSUE THREAD

**Issue by duerrsimon** [schrodinger/pymol-open-source#292]
I am currently working on a plugin for PyMol that should continuously add new structures to the PyMol view while the function is running. 

This is some demo code: 
import time
from pymol import cmd

@cmd.extend
def custom_function(inp):
    for i in range(len(inp)):
        time.sleep(2)
        print(i) # here we would load the structures

However, this doesn't work. It prints in the system console just in time but not in the Pymol console (and if I call e.g cmd.load("somepdb") also the structure doesn't get added to the view) until the function has completed running. 

Is there a way around this ?

**Comment by speleo3** [comment]
You can run your code in a separate thread:
```py
import time
import threading
from pymol import cmd

def _custom_function(inp):
    for aa in inp.split():
        print(f"Loading {aa} in 2 seconds...")
        time.sleep(2)
        cmd.fragment(aa)

@cmd.extend
def custom_function(inp="ala gly his trp"):
    t = threading.Thread(target=_custom_function,
                         args=(inp,),
                         daemon=True)
    t.start()
```
