### ISSUE TITLE
The multiple PyMol version on Conda

### ISSUE THREAD

**Issue by shaoqx** [schrodinger/pymol-open-source#293]
I found there are at least 3 different pymol namings on Conda which leads to different versions I assume:
- `pymol-bundle` (from https://pymol.org/conda/)
- `pymol` (says older version from https://pymol.org/conda/ but seems a new version from https://anaconda.org/schrodinger/pymol)
- `pymol-open-source` (from https://anaconda.org/conda-forge/pymol-open-source.)

I wonder what are the differences between these different versions. 
When I try these on a Linux machine,
I found the `pymol-bundle` won't successfully install in a new conda environment right now. (Says "Killed" after solving the environment for 1 hour. It used to work for me.)
Also `pymol` gives me the following error when I try installing it in a new conda environment:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - pymol -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17
```
Only `pymol-open-source` installs smoothly. But I can't find it mentioned anywhere in the document besides searching in Conda.

All the Best,
QZ

**Comment by JarrettSJohnson** [comment]
`pymol` and `pymol-bundle` are both Schrodinger-managed and is the Incentive version. `pymol-open-source` builds from this repository. The former two was updated recently to support Python 3.10. Can you try again with that python version in a new environment?

**Comment by shaoqx** [comment]
Thank you for the info! It works!
