### ISSUE TITLE
Error saving PDB file

### ISSUE THREAD

**Issue by 404-xianjin** [schrodinger/pymol-open-source#294]
I have two pdb files, 4hkz and GSTP1, I use 4hkz's variable region "SRWGGDGFYAMDY" to combine with GSTP1's "DQGQSWKEEVVTVETWQE". 
as the picture shows,
![image](https://github.com/schrodinger/pymol-open-source/assets/47860060/2189dbbb-d593-47e0-a058-91f39b68168d)
I try to save this two pdb files as a new pdb file, but the pdb file I saved is like this.
![image](https://github.com/schrodinger/pymol-open-source/assets/47860060/eb26f721-514b-44e7-9da3-c4d0d40c7acb)
I'm not sure what is causing this and I need your help. Thank you so much
@JarrettSJohnson @TstewDev @pslacerda

**Comment by JarrettSJohnson** [comment]
Can you try this setting before saving the PDB: https://pymolwiki.org/index.php/Retain_order

**Comment by YaoYinYing** [comment]
These chain ids from pdbs are identical, try something like this before saving the merged pdb: 
```
alter prot_A and chain A, chain='A'
alter prot_B and chain B, chain='B'
save merged.pdb, (prot_A and chain A) or (prot_B and chain B)
```
