### ISSUE TITLE
Small molecule missing when loading mmtf file format

### ISSUE THREAD

**Issue by maabuu** [schrodinger/pymol-open-source#295]
When loading PDB entry 1X8X from the MMTF file in PyMol, the small molecule TYR does not show. When loading the same entry from the CIF or PDB file, TYR does show. 

To reproduce:
`fetch 1X8X, type=mmtf` does not show TYR.
`fetch 1X8X, type=pdb` does show TYR.

The MMTF file from the PDB does include the TYR molecule as shown here: https://www.rcsb.org/3d-view/ngl/1x8x

PyMol Version 2.5.0

**Comment by speleo3** [comment]
That's interesting. PyMOL's MMTF loader currently marks residues as HETATM if they don't have a single-letter code. But TYR does have a single letter code. I suppose the proper source for HETATM information is [entityList](https://github.com/rcsb/mmtf/blob/master/spec.md#entitylist) with `type != "polymer"`.
