### ISSUE TITLE
Error in background function

### ISSUE THREAD

**Issue by Lancespace** [schrodinger/pymol-open-source#299]
Hello everybody, I'm new around here and also new to all this console thing, but I'm now on my way to become a principal researcher and I need to start using some features that require me to extend my knowledge towards this field.

Let's cut through the cheese:

I'm trying to use OpenSource pymol, and after one day reading tutorials I finally made it through miniconda. I was so happy, but when I try to work with it, it instantly displays a pop up window named "Error in background function" that doesn't let me write in the console. It starts piling up continuosly similar errors until hundreds and just never goes away.

The thing is, the program works. I made it to fetch a protein and clean it up, but it becomes impossible to add more complex commands and work comfortably without pop ups continuosly showing up. Could you please help me with this? I provide the error code down below.

Thank you so much everybody in advance!

```
Error: 1
AttributeError Exception in Tk callback
  Function: <function Balloon.bind.<locals>.<lambda> at 0x000001B1892C02C0> (type: <class 'function'>)
  Args: (<Enter event focus=False x=159 y=18>,)
  Event type: EnterNotify (type num: 7)
Traceback (innermost last):
  File "C:\Users\User\miniconda3\envs\pymol\Lib\site-packages\Pmw\Pmw_2_0_1\lib\PmwBase.py", line 1776, in __call__
    return self.func(*args)
  File "C:\Users\User\miniconda3\envs\pymol\Lib\site-packages\Pmw\Pmw_2_0_1\lib\PmwBalloon.py", line 80, in <lambda>
    self._enter(event, w, sHelp, bHelp, 0))
  File "C:\Users\User\miniconda3\envs\pymol\Lib\site-packages\Pmw\Pmw_2_0_1\lib\PmwBalloon.py", line 256, in _enter
    self.showstatus(statusHelp)
  File "C:\Users\User\miniconda3\envs\pymol\Lib\site-packages\Pmw\Pmw_2_0_1\lib\PmwBalloon.py", line 204, in showstatus
    if isinstance(cmd, collections.Callable):
AttributeError: module 'collections' has no attribute 'Callable'
================================================
  Event contents:
    char: ??
    delta: 0
    focus: False
    height: ??
    keycode: ??
    keysym: ??
    keysym_num: ??
    num: ??
    send_event: False
    serial: 599
    state: 0
    time: 47728171
    type: 7
    widget: .!frame.!frame.!frame.!frame.!entry
    width: ??
    x: 159
    x_root: 222
    y: 18
    y_root: 197
```

**Comment by JarrettSJohnson** [comment]
Hello,

I don't think I've seen this issue yet, but it seems that you are using PMW instead of python Qt. Can I ask what your steps were to install pymol via conda?

**Comment by Lancespace** [comment]
Yes of o

> Hello,
> 
> I don't think I've seen this issue yet, but it seems that you are using PMW instead of python Qt. Can I ask what your steps were to install pymol via conda?

Yes of course:

1.- I installed miniconda3 Windows 64-bit
2.- I opened the console Anaconda prompt (miniconda3)
3.- I inserted the following lines of code:
```
conda create -n pymol
conda activate pymol
conda install -c conda-forge pip numpy pmw
pip install pipwin
pipwin install pymol
```
4.- It gave me an error regarding the cache, so I solved it by using `pipwin refresh` and then `pipwin install pymol` again. Then it worked.
5.- Then I just typed `pymol` in the console to open the program.

Thank you very much for the fast answer.

**Comment by JarrettSJohnson** [comment]
Thanks for the details.  It seems like from the earlier message, there may be some python version incompatibility with that installed package, but I have to double check. What I would suggest is instead use the pre-packaged open-source pymol from  the conda-forge channel:

```
conda create -n pymol_open
conda activate pymol_open
conda install -c conda-forge pymol-open-source
```
All of the required dependencies (including PyQt5) should automatically come with this package.

**Comment by Lancespace** [comment]
> Thanks for the details. It seems like from the earlier message, there may be some python version incompatibility with that installed pmw package, but I have to double check. What I would suggest is instead use the pre-packaged open-source pymol from the conda-forge channel:
> 
> ```
> conda create -n pymol_open
> conda activate pymol_open
> conda install -c conda-forge pymol-open-source
> ```
> 
> All of the required dependencies (including PyQt5) should automatically come with this package.

Excuse me, but I'm completely new to this and I'm struggling. Should I unninstall somehow what I did before writing those commands? or just execute them in my current status?

Thank you so much again

**Comment by JarrettSJohnson** [comment]
Each conda environment will manage its own installed packages. As long as you create and activate your new environment, you won't need to worry about uninstalling packages you installed into another environment. If this new environment works, you're more than free to remove the `pymol` environment you made and continue to use the `pymol_open` environment that I used in my instructions.

**Comment by Lancespace** [comment]
> Each conda environment will manage its own installed packages. As long as you create and activate your new environment, you won't need to worry about uninstalling packages you installed into another environment. If this new environment works, you're more than free to remove the `pymol` environment you made and continue to use the `pymol_open` environment that I used in my instructions.

You are my savior. It works up to perfection. Thank you so so so much. I'm really lost in this coding stuff.

**Comment by JarrettSJohnson** [comment]
No worries. Glad you have it working. Let me know if you need anymore assistance.
