### ISSUE TITLE
Reading of multiple .xyz files does not work in some cases.

### ISSUE THREAD

**Issue by tranas-open** [schrodinger/pymol-open-source#30]
the line 3176 in .../layer2/ObjectMolecule.cpp prevents the reading of multiple .xyz files if the number of atoms is printed not from the beginning of the line, but from position 7 or more.

**Comment by speleo3** [comment]
do you have an example file?

**Comment by tranas-open** [comment]
Hi Thomas,

in attachment.

I shifted "9" from position 8 to position 5 for the first 26  
configurations and after that can see first 26 configurations.

The line in the code is "ncopy(cc, p, 6);".

Best,
Dmitry




Zitat von Thomas Holder <notifications@github.com>:

> do you have an example file?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/schrodinger/pymol-open-source/issues/30#issuecomment-494848452



-- 
Dmitry A. Ryndyk
http://quantranspro.org

Institute for Materials Science
TU Dresden

TraNaS OpenSuite - Integrated open software suite for multiscale modeling
http://tranas.org/opensuite

**Comment by tranas-open** [comment]
ah, sorry. It is done. Thank you.
