### ISSUE TITLE
ImportError: libvtkm_cont-1.5.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by universvm** [schrodinger/pymol-open-source#304]
I'm out of luck installing pymol. For various reasons I won't go into, I cannot use conda. I have been trying to install with apt-get or using the precompiled binaries. I have been stuck at this error and cannot seem to find anything on google:

"ImportError: libvtkm_cont-1.5.so.1: cannot open shared object file: No such file or directory"

I tried looking it up in the repository here as well and yet I cannot find anything. Here's the full dump:

```
PyMOL failed to start, dumping diagnostics...

Operating System:
Linux-5.4.0-1104-azure-x86_64-with-glibc2.35
#110~18.04.1-Ubuntu SMP Sat Feb 11 17:41:21 UTC 2023
PyQt5 5.15.9 (Qt 5.15.2)

Python:
3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
prefix=/opt/{REDACTED}/.venv
executable=/opt/{REDACTED}/.venv/bin/python
filesystemencoding=utf-8

Qt, Python and PyMOL Environment Variables:
LANG=C.UTF-8
PYDEVD_USE_FRAME_EVAL=NO
PYMOL_DATA=/opt/pymol/share/pymol/data
PYMOL_PATH=/opt/pymol/share/pymol
PYTORCH_NVML_BASED_CUDA_CHECK=1
QT_API=pyqt5
QT_XKB_CONFIG_ROOT=/opt/{REDACTED}/.venv/lib

PATH:
/opt/{REDACTED}/.venv/bin:/opt/{REDACTED}/bin:/opt/c
onda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/root/.local/bin:/usr/local
/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Traceback (most recent call last):
  File "/opt/pymol/lib/python3.10/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "/opt/pymol/lib/python3.10/site-packages/pymol/__init__.py", line 620, in <module>
    import pymol._cmd
ImportError: libvtkm_cont-1.5.so.1: cannot open shared object file: No such file or directory

```

Things that I've tried:

- `!apt-get install -y -q python3-vtk7`
- `!pip install vtk`

**Comment by JarrettSJohnson** [comment]
Do you need VTK-m? If not, then you can add `--use-vtkm="no"` to your setup arguments.

**Comment by minsu1794** [comment]
I also have same problem, and tried --use-vtkm="no" but still same error occur.

**Comment by JarrettSJohnson** [comment]
> I also have same problem, and tried --use-vtkm="no" but still same error occur.

I can't seem to reproduce this error. And this is with a clean build? `--use-vtkm` is also `no` by default.

**Comment by minsu1794** [comment]
I have used : conda install -c schrodinger pymol
to setup the conda environment. 





So here`s my log:
PyMOL failed to start, dumping diagnostics...
pymol-2.5.7-py39had9a3ec_0.json
conda build: py39had9a3ec_0 https://conda.anaconda.org/schrodinger/linux-64

Operating System:
Linux-3.10.0-1127.10.1.el7.x86_64-x86_64-with-glibc2.17
#1 SMP Wed Jun 3 14:28:03 UTC 2020
PyQt5 5.15.10 (Qt 5.15.2)

Python:
3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)
[GCC 12.3.0]
prefix=/home/mcho43/anaconda3/envs/crispro
executable=/home/mcho43/anaconda3/envs/crispro/bin/python
filesystemencoding=utf-8

Qt, Python and PyMOL Environment Variables:
LANG=en_US.UTF-8
PYMOL_DATA=/home/mcho43/anaconda3/envs/crispro/share/pymol/data
PYMOL_PATH=/home/mcho43/anaconda3/envs/crispro/share/pymol
QT_API=pyqt5
QT_XKB_CONFIG_ROOT=/home/mcho43/anaconda3/envs/crispro/lib

PATH:
/home/mcho43/anaconda3/envs/crispro/bin:/home/mcho43/anaconda3/condabin:/home/
mcho43/cellranger/cellranger-5.0.1:/home/mcho43/bin:/usr/local/bin:/usr/bin:/u
sr/local/sbin:/usr/sbin:/home/mcho43/.local/bin:/home/mcho43/bin

Traceback (most recent call last):
  File "/home/mcho43/anaconda3/envs/crispro/bin/crispro", line 4, in <module>
    __import__('pkg_resources').run_script('crispro==1.0.2', 'crispro')
  File "/home/mcho43/anaconda3/envs/crispro/lib/python3.9/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mcho43/anaconda3/envs/crispro/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1561, in run_script
    exec(code, namespace, namespace)
  File "/home/mcho43/anaconda3/envs/crispro/lib/python3.9/site-packages/crispro-1.0.2-py3.9.egg/EGG-INFO/scripts/crispro", line 27, in <module>
    import crispro.crispro_structures as crispro_structures
  File "/home/mcho43/anaconda3/envs/crispro/lib/python3.9/site-packages/crispro-1.0.2-py3.9.egg/crispro/crispro_structures.py", line 21, in <module>
    import pymol
  File "/home/mcho43/anaconda3/envs/crispro/lib/python3.9/site-packages/pymol/__init__.py", line 620, in <module>
    import pymol._cmd
ImportError: libvtkm_cont-1.5.so.1: cannot open shared object file: No such file or directory









I`ve been trying to install vtkm 1.5 through this link : https://gitlab.kitware.com/vtk/vtk-m/-/releases?after=eyJyZWxlYXNlZF9hdCI6IjIwMjEtMTItMDggMTM6NDg6MTUuNjI2MjkwMDAwIC0wNTAwIiwiaWQiOiIxMjUyIn0

All the 1.5 version I tried however didn`t have specific libvtkm_cont-1.5.so.1.

**Comment by JarrettSJohnson** [comment]
` conda install -c schrodinger pymol`

installs Incentive PyMOL, which is a separate python package from this repo's open-source. Use a new environment and try either:

`conda install -c conda-forge pymol-open-source` if you need to install open source

or

`conda install -c conda-forge -c schrodinger pymol` (note the inclusion of conda-forge channel first) if you need to install the Incentive PyMOL conda package. See https://pymol.org/conda/ for more info.

**Comment by skrhakv** [comment]
I had a similar issue:
```
ImportError: libvtkm_cont-1.5.so.1: cannot open shared object file: No such file or directory
```
It was resolved by using `conda install -c conda-forge pymol-open-source` which @JarrettSJohnson suggested.

Thanks!

**Comment by minsu1794** [comment]
Thank you!
The suggestion did resolve my issue.

**Comment by JarrettSJohnson** [comment]
No worries. I assume that the OP's issue will be solved with this too. Closing.

**Comment by iland24** [comment]
Thank you, I was facing the same issue but `conda install -c conda-forge pymol-open-source` worked.

**Comment by universvm** [comment]
Hi @JarrettSJohnson 

As I mentioned in the post, I cannot use conda, so unfortunately the issue is not solved unfortunately.

**Comment by JarrettSJohnson** [comment]
Can you inform which method you installed PyMOL to get the error above? Was this from the installers from the website? If so, there may be a fix coming for it this week.

**Comment by universvm** [comment]
> JarrettSJohnson

This was from compiling from source

**Comment by JarrettSJohnson** [comment]
If I'm not mistaken, diagnostics dumping upon opening PyMOL only occurs from our incentive product (which is not abled to be compiled from source). So even if you're compiling open-source, it may be trying to open incentive?

**Comment by universvm** [comment]
Apologies, I'm not sure what the incentive product is and perhaps I mistakenly remembered that I got that error installing this repository (pymol-open-source). 

From your message it sounds like this should not be happening using this repository but rather only when using another version (perhaps a pre-compiled one)?
