### ISSUE TITLE
Incompatiblity of pymol with python 3.9

### ISSUE THREAD

**Issue by robertoimuno** [schrodinger/pymol-open-source#314]
Hello,

I've been attempting to install Pymol on a Conda environment running Python 3.9 and encountered the following error:

`UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - pymol -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31`

Based on my research, it seems that Pymol might not be compatible with Python 3.9. Is this information accurate, and if so, are there any plans to address this compatibility issue in the near future?

Thank you in advance for your assistance.

Best regards,
Roberto

**Comment by JarrettSJohnson** [comment]
It's compatible with 3.9 and 3.10; I believe something else is amiss. I've seen this error before when there's a mix of conda-forge packages against non-conda-forge ones. Have you tried a fresh conda-forge python 3.9 environment with only the pymol package?

**Comment by JarrettSJohnson** [comment]
Feel free to comment here if it's still an issue. I haven't heard of any other reports of this failing with Python 3.9.
