### ISSUE TITLE
Conda package segfaults on WSL running Ubuntu

### ISSUE THREAD

**Issue by BobbyLangan** [schrodinger/pymol-open-source#32]
I'm running Ubuntu 18.04 on WSL. Python version 3.7.3.  I installed PyMol using `conda install -c schrodinger pymol` - however when I enter the `pymol` command to launch the application I get a segfault before any windows open.  I have OpenGL libraries in my env and running VcXsrv on Windows (unchecked 'Native opengl' when configuring VcXsrv to force use of Linux OpenGL).

Is this an issue with WSL specifically, how it handles opening windows? I am able to open other X-window based applications.  A work around would be greatly appreciated - I can copy PDBs to C: and open the windows pymol download, but my workflow productivity suffers

Output pasted here, though not super helpful:
```
PyMOL(TM) 2.3.2 - Incentive Product
 Copyright (C) Schrodinger, LLC

 This Executable Build integrates and extends Open-Source PyMOL.
[1]    24738 segmentation fault (core dumped)  pymol
```

**Comment by lorton** [comment]
Hi @BobbyLangan - are you an incentive PyMOL purchaser?  If so you will likely get more speedy support from `help@schrodinger.com`.  If not, then you will be able to get support from [the PyMOL mailing list](https://pymolwiki.org/index.php/PyMOL_mailing_list) for the open source version (Conda installs the incentive version, which you can try temporarily without a license).
