### ISSUE TITLE
Pymol crashes when i am trying to split states on M3 chip

### ISSUE THREAD

**Issue by venzera** [schrodinger/pymol-open-source#327]
I've got PyMOL installed via "brew install pymol" on MacBook on M3 chip OS Sonoma. 
And when i load (this step is fine) structure with multiple states and try to split states it immediately crushes with "segmentation fault". 
What should i do to solve that kind of issue?
I did try to reinstall it multiple times. 
And seems like no one hasn't experienced such a problem.

**Comment by samuelhoover** [comment]
I had a similar issue where loading a GROMAC coordinate file (2.2 MB) caused my Homebrew-installed PyMOL to crash with a segmentation fault. I had no problem loading a 107 KB PDB file though.

M1 MacBook Pro on macOS Sonoma 14.2.1.

<img width="315" alt="image" src="https://github.com/schrodinger/pymol-open-source/assets/56448170/2eb184f7-e965-42ef-a376-c66f6c81ed21">

**Comment by venzera** [comment]
@JarrettSJohnson it does with any structures with multiple states inluding 1nmr

**Comment by JarrettSJohnson** [comment]
Thanks for confirming; I've checked with homebrew on an older Intel Mac, I think I only have an M1 around.

**Comment by samuelhoover** [comment]
@venzera I haven't found a solution, it seems to work with smaller files and fails on bigger files. My only guess is it's some memory issue. My friend on a Linux machine was able to open both files without problem, but their Intel Mac did crash with the coordinates file. They used pacman to install PyMOL.

@JarrettSJohnson `fetch 1nmr` works for me too. I'll link the coordinates file (which causes a segmentation fault) and the PDB file (which does *not* cause an issue) here.
.gro file: https://github.com/samuelhoover/gromacs-tutorials/blob/main/lysozyme-in-water/MD/md_0_1.gro
PDB file: https://github.com/samuelhoover/gromacs-tutorials/blob/main/lysozyme-in-water/1AKI_clean.pdb

**Comment by samuelhoover** [comment]
@venzera Looks like Homebrew maintainers updated the formula. Uninstall PyMOL and then reinstall with the`--HEAD` option for it to work. If you just do `brew install pymol` like I did initially, it will crash as before.

@JarrettSJohnson In case you notified the Homebrew maintainers, thanks!

**Comment by JarrettSJohnson** [comment]
I haven't contacted the maintainers yet. I'm guessing `--HEAD` just pulls the head commit and builds it itself?

**Comment by samuelhoover** [comment]
Correct, I noticed when I did `brew install pymol` that it had the same errors from #321.

**Comment by venzera** [comment]
@samuelhoover @JarrettSJohnson that indeed worked very well. Thank you very much for help. 

P.S. I almost started to use ChimeraX instead 😄
