### ISSUE TITLE
apbs plugin issue 

### ISSUE THREAD

**Issue by Vcald** [schrodinger/pymol-open-source#328]
I have installed open source pymol on windows 11 through conda (Miniconda_latest) and with cctbx with the following command:
conda.exe create -n opensource -c conda-forge cctbx pymol-open source

After successful installation I have installed apbs plugin, then apbs and pdb2pqr.
When trying to use the plugin I get the following error:
Any hint?

PyMOL>fetch 1rmz
TITLE     Crystal structure of the catalytic domain of human MMP12 complexed with the inhibitor NNGH at 1.3 A resolution
 ExecutiveLoad-Detail: Detected mmCIF
 CmdLoad: ".\1rmz.cif" loaded as "1rmz".
GENERATING PQR FILE via PDB2PQR
Erasing contents of C:\Users\Vito\AppData\Local\Temp\pymol-generated.pdb in order to generate new PDB file
TESTING
DONE TESTING
args are now converted to string:  C:\Miniconda3_latest\envs\opensource\Scripts\pdb2pqr30.exe --ff=AMBER C:\Users\Vito\AppData\Local\Temp\pymol-generated.pdb C:\Users\Vito\AppData\Local\Temp\pymol-generated.pqr
b''
b'Traceback (most recent call last):\r\n  File "<frozen runpy>", line 198, in _run_module_as_main\r\n  File "<frozen runpy>", line 88, in _run_code\r\n  File "C:\\Miniconda3_latest\\envs\\opensource\\Scripts\\pdb2pqr30.exe\\__main__.py", line 4, in <module>\r\n  File "C:\\Miniconda3_latest\\envs\\opensource\\Lib\\site-packages\\pdb2pqr\\__init__.py", line 10, in <module>\r\n    from .main import main\r\n  File "C:\\Miniconda3_latest\\envs\\opensource\\Lib\\site-packages\\pdb2pqr\\main.py", line 21, in <module>\r\n    from . import debump\r\n  File "C:\\Miniconda3_latest\\envs\\opensource\\Lib\\site-packages\\pdb2pqr\\debump.py", line 11, in <module>\r\n    from . import io\r\n  File "C:\\Miniconda3_latest\\envs\\opensource\\Lib\\site-packages\\pdb2pqr\\io.py", line 12, in <module>\r\n    from . import cif\r\n  File "C:\\Miniconda3_latest\\envs\\opensource\\Lib\\site-packages\\pdb2pqr\\cif.py", line 12, in <module>\r\n    import pdbx\r\nModuleNotFoundError: No module named \'pdbx\'\r\n'
PDB2PQR's mainCommand returned 1
In show error 2

**Comment by speleo3** [comment]
How did you install `pdb2pqr`? Installing it with `pip` or `conda` should automatically install the `mmcif_pdbx` dependency.

**Comment by Vcald** [comment]
I installed it with conda and verified that mmcif_pdbx was installed as
well. But still it does not work.
Can it be because of a space between my name and surname in the temp
directory?

Il giorno dom 21 gen 2024 alle ore 12:24 Thomas Holder <
***@***.***> ha scritto:

**Comment by Vcald** [comment]
I have deleted everything and reinstall from scratch...pmw does not work at the beginning (pmw2.0.0). I have to uninstall it and install pmw2.1.1 for getting the apbs plugin window working.
After this tweak...it works.
