### ISSUE TITLE
bond and cmd.bond() are very slow

### ISSUE THREAD

**Issue by brisvag** [schrodinger/pymol-open-source#33]
When creating a large number of bonds with a python script that uses the API, the bad performance of the `cmd.bond()` command really show up. As stated here:

https://github.com/schrodinger/pymol-open-source/blob/f2f3dbb74622cbc3bfbf150f5d487f73acfe1227/layer2/ObjectMolecule.cpp#L4492-L4493

the performance issue is due to full table scans when looking for the atom selections.

A possible workaround would be a (API only?) function that accepts a list of atom indexes instead and directly creates a bond between the two, bypassing the slowness of evaluating selections.

**Comment by speleo3** [comment]
We've added a new function: `cmd.add_bond()` (check for `help(cmd.add_bond)` for details).

Example:
```python
from pymol import cmd, stored

pdbid = '2xwu'
cmd.fetch(pdbid)
bonds = cmd.get_bonds(pdbid)
stored.indexmap = []
cmd.iterate_state(1, pdbid, "stored.indexmap.append(index)")

cmd.unbond('*', '*')

if 0:
    # slow
    for (atm1, atm2, order) in bonds:
        cmd.bond('{}`{}'.format(pdbid, stored.indexmap[atm1]),
                 '{}`{}'.format(pdbid, stored.indexmap[atm2]), order)
else:
    # fast
    for (atm1, atm2, order) in bonds:
        cmd.add_bond(pdbid, stored.indexmap[atm1],
                            stored.indexmap[atm2], order)
```

See https://github.com/schrodinger/pymol-testing/commit/332ba67fa1f863f05105e7054fae72c43ee8e3fb for another example.

**Comment by brisvag** [comment]
Hi Thomas,

Great job! It does exactly what I needed: now my script takes less than a
second, compared to the minutes it took before.

Thank you!
Lorenzo

Il giorno mer 19 giu 2019 alle ore 10:58 Thomas Holder <
notifications@github.com> ha scritto:
