### ISSUE TITLE
PyMOL Open-Source 3.0 tracking & tagging

### ISSUE THREAD

**Issue by jwhowarth** [schrodinger/pymol-open-source#343]
The open source release is missing a tag for the current pymol 3.0 source code release.

**Comment by JarrettSJohnson** [comment]
Thanks. We're still in the middle of deploying our 3.0 release (started last night) for incentive and we still need to transfer some things to open source before we add the tag.

**Comment by JarrettSJohnson** [comment]
Going to finish up merging [nucleic acid building support](https://pymolwiki.org/index.php/Builder) + [fnab](https://pymolwiki.org/index.php/Fnab)  from Incentive sometime this week and that should be it for 3.0.

**Comment by JarrettSJohnson** [comment]
Tag added: https://github.com/schrodinger/pymol-open-source/releases/tag/v3.0.0
