### ISSUE TITLE
Nested grouping failing

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#346]
Something is wrong at the objects sidebar.

![image](https://github.com/schrodinger/pymol-open-source/assets/149358/afd195f3-4fb6-4c46-86a3-27dacde09ad8)

[session.pze.zip](https://github.com/schrodinger/pymol-open-source/files/14630340/session.pze.zip)

**Comment by JarrettSJohnson** [comment]
Hi Pedro,

AFAIK, there are still some limitations with the contents panel (seems like this session includes nested groups which are currently not supported in PyMOL3 Incentive: see https://pymol.org/support.html? )

For incentive-only features, we ask that you go through help@schrodinger.com

**Comment by pslacerda** [comment]
There is an way to enable the legacy contents panel and disable the new one programatically?

**Comment by pslacerda** [comment]
I missed `set internal_gui, off`.

**Comment by JarrettSJohnson** [comment]
There's no way to programmatically toggle the new contents panel, but I think it's been recently discussed for future consideration? Also, nested groups should also be addressed for 3.1. @TstewDev can probably chime in better on both of these.

**Comment by TstewDev** [comment]
Yes I'm currently working on nested groups and targeting 3.1! As far as toggling the new contents panel, this may be introduced in the future to allow the workspace to be larger and reduce clutter. Currently it's only hidden when there's an error in the process of populating/drawing the panel, so it wouldn't make sense have an option to show it again until I put some more thought into how to properly reinitialize and deal with these errors gracefully.

**Comment by pslacerda** [comment]
Never used, but [Qt support for CSS](https://doc.qt.io/qt-6/stylesheet-syntax.html) may be an option to reduce clutter. Have a good job doing this panel!
