### ISSUE TITLE
oligonucleotides - command 'fnab' in PyMol 2.5?

### ISSUE THREAD

**Issue by smoe** [schrodinger/pymol-open-source#351]
For the quick generation of nucleotides I found https://wiki.pymol.org/index.php/Fnab with a mention to be available for version 2.3. I checked out the Open Source version but cannot find that command, also checked the source tree, which references it as one of the tests but I do not see it implemented. Where shall I look?

Many thanks!

**Comment by JarrettSJohnson** [comment]
Apologies, it should have probably been made a bit clearer that it was released for Incentive PyMOL 2.3. This feature is currently not yet open-source. I'll bring it up for consideration though for Open-Source PyMOL 3.0 (as we did with the APBS electrostatics plugin), which will be tagged relatively soon.

**Comment by smoe** [comment]
Thank you (and Schrödinger at large) for your efforts. I have found https://github.com/dacase/nabc to help me out.  I was impressed by this software, which kind of cries out loud to get an interface to PyMOL :) .

**Comment by JarrettSJohnson** [comment]
`fnab` added in 246e0a4c2d2d05bf2736dbb57e1694617d96c13d
