### ISSUE TITLE
cannot build - glm::translate not found

### ISSUE THREAD

**Issue by james-yj** [schrodinger/pymol-open-source#356]
OS: Alamlinx 8.7
Prolem: Cannot build
when I ran "python3 setup.py install", some error messages came out as below:
----------------------------------------------------------------------------------------------------------------------------
layer1/SceneView.cpp: In member function ‘glm::mat4 SceneView::toWorldHomogeneous() const’:
layer1/SceneView.cpp:88:27: error: ‘translate’ is not a member of ‘glm’
   glm::mat4 matrix = glm::translate(glm::mat4(1.0f), m_pos);
                           ^~~~~~~~~
layer1/SceneView.cpp:88:27: note: suggested alternative: ‘transpose’
   glm::mat4 matrix = glm::translate(glm::mat4(1.0f), m_pos);
                           ^~~~~~~~~
                           transpose
layer1/SceneView.cpp:90:15: error: ‘translate’ is not a member of ‘glm’
   return glm::translate(matrix, -m_origin);
               ^~~~~~~~~
layer1/SceneView.cpp:90:15: note: suggested alternative: ‘transpose’
   return glm::translate(matrix, -m_origin);
               ^~~~~~~~~
               transpose
layer1/SceneView.cpp: In static member function ‘static SceneView SceneView::FromWorldHomogeneous(const mat4&, SceneView)’:
layer1/SceneView.cpp:98:39: error: ‘translate’ is not a member of ‘glm’
   glm::mat4 invOriginTranslate = glm::translate(glm::mat4(1.0), ori);
                                       ^~~~~~~~~
layer1/SceneView.cpp:98:39: note: suggested alternative: ‘transpose’
   glm::mat4 invOriginTranslate = glm::translate(glm::mat4(1.0), ori);
                                       ^~~~~~~~~
                                       transpose
layer1/SceneView.cpp: In member function ‘glm::vec3 SceneView::worldPos() const’:
layer1/SceneView.cpp:110:19: error: ‘translate’ is not a member of ‘glm’
   auto mat = glm::translate(glm::mat4(1.0f), m_pos);
                   ^~~~~~~~~
layer1/SceneView.cpp:110:19: note: suggested alternative: ‘transpose’
   auto mat = glm::translate(glm::mat4(1.0f), m_pos);
                   ^~~~~~~~~
                   transpose
layer1/SceneView.cpp:112:14: error: ‘translate’ is not a member of ‘glm’
   mat = glm::translate(mat, -m_origin);
              ^~~~~~~~~
layer1/SceneView.cpp:112:14: note: suggested alternative: ‘transpose’
   mat = glm::translate(mat, -m_origin);
              ^~~~~~~~~
              transpose
layer3/Executive.cpp: In function ‘pymol::Result<> ExecutiveMoveCameraOnCurve(PyMOLGlobals*, ObjectCurve&, float)’:
layer3/Executive.cpp:16887:19: error: ‘lookAt’ is not a member of ‘glm’
   auto tfx = glm::lookAt(pos, pos + dir, glm::vec3(0.0f, 1.0f, 0.0f));
                   ^~~~~~
layer3/Executive.cpp: In function ‘pymol::Result<> ExecutiveCameraLookAt(PyMOLGlobals*, pymol::CObject&)’:
layer3/Executive.cpp:16927:19: error: ‘lookAt’ is not a member of ‘glm’
   auto tfx = glm::lookAt(cam.worldPos(), *target, glm::vec3(0.0f, 1.0f, 0.0f));
                   ^~~~~~
error: command 'g++' failed with exit status 1
----------------------------------------------------------------------------------------------------------------------------

**Comment by JarrettSJohnson** [comment]
What version is your glm?

**Comment by james-yj** [comment]
> What version is your glm?
 glm-devel-0.9.8.5-2.el8.noarch is installed on my computer.

**Comment by james-yj** [comment]
glm-devel-0.9.8.5-2.el8.noarch is installed on my computer.

**Comment by james-yj** [comment]
> glm-devel-0.9.8.5-2.el8.noarch is installed on my computer.



> What version is your glm?

glm-devel-0.9.8.5-2.el8.noarch is installed on my computer.

**Comment by james-yj** [comment]
> What version is your glm?


glm-devel-0.9.8.5-2.el8.noarch is installed on my computer.

**Comment by JarrettSJohnson** [comment]
Added `<glm/gtc/matrix_transform.hpp>` in 6d9ddd4bd3eaf31b96b33a557b6f7c101bb2cebe as suggested by other repos with similar issues. Can anyone who's had this issue confirm if this works for them?

**Comment by JarrettSJohnson** [comment]
If the compilation error still exists, feel free to let us know and we'll reopen the issue.
