### ISSUE TITLE
relationship between this repo and the official PyMOL 3

### ISSUE THREAD

**Issue by Youngerkind** [schrodinger/pymol-open-source#357]
I successfully setup the Version 3.1.0a0, but I find that the GUI is barely the same to Version 2.6.0a0 and much different from the [official one](https://learn.schrodinger.com/public/pymol/2023-4/Content/pymol/pymol_home.htm). For example, I can't find the new timeline panel.

I setup this repo following [Linux Install PymolWiki](https://pymolwiki.org/index.php/Linux_Install). Are there anything I take it wrong? Or this is just the reality?

**Comment by JarrettSJohnson** [comment]
Most of the new features, including the revamped UI and panels are currently only available in the 3.0 Incentive Version and are not available here in open-source. Typically, we do migrate features from Incentive to open-source over time. Incentive builds are available for evaluation on our official conda channels or on pymol.org
