### ISSUE TITLE
Fantom atom when selecting a missing residue

### ISSUE THREAD

**Issue by chmnk** [schrodinger/pymol-open-source#359]
In `pymol-open-source` `2.5` and `3.0`, when I load the [1c1v](https://www.rcsb.org/structure/1C1V) PDB file and try to select a missing residue,

```
fetch 1c1v
select ch_r150, chain H and resi 150
```

I get a 1-atom selection, and that atom does not have coordinates. Is it done like that by design?

**Comment by JarrettSJohnson** [comment]
Depends on the file that PyMOL parses the structure data from. From the `1c1v` `.cif` file, there is a residue provided by the structure file at residue position 150, and I assume we just insert a "non-physical" atom there that lacks coordinates. For the `1c1v` `.pdb` file, the missing residues are skipped.

**Comment by speleo3** [comment]
You could remove those atoms which don't have coordinates by:
```
remove not present
```
Before:
![image](https://github.com/schrodinger/pymol-open-source/assets/1239490/90c2a117-991d-42c8-a574-87f47febb9ae)
After:
![image](https://github.com/schrodinger/pymol-open-source/assets/1239490/ba942f7f-09ff-4c63-9962-b9657bbf262e)
