### ISSUE TITLE
load_mtz

### ISSUE THREAD

**Issue by AssmannG** [schrodinger/pymol-open-source#365]
Hi All, 
I just recently installed v3.0.0 on a cluster and get the error when calling the function **load_mtz** in the GUI: 
```
PyMOL>load_mtz lyso_38_2_ccp4_94P42212.mtz
 Incentive-Only-Error: "load_mtz" is not available in Open-Source PyMOL
    Please visit http://pymol.org if you are interested in the
    full featured "Incentive PyMOL" version.
    
 ```
 Is this correct or did I do something wrong with the installation (I installed with --use-msgpackc=no and --no-vmd-plugins)? Has anyone experienced the same / has a solution? Has this something to do with the two flags during the installation ( as I do see the function mtz_load in the source code? 
 
 Thanks for any help!

**Comment by JarrettSJohnson** [comment]
The message you received is correct; this is not currently available on the Open-source version.
