### ISSUE TITLE
`cmd.set_property` on maps

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#366]
Please support `cmd.set_property` on map objects?

**Comment by JarrettSJohnson** [comment]
Hi, can you submit this as a Schrodinger ticket? Properties are not available on open-source.

**Comment by pslacerda** [comment]
How do I do it?

**Comment by JarrettSJohnson** [comment]
help@schrodinger.com

**Comment by pslacerda** [comment]
I don't have an Schrodinger account and use it without a license file (but for academic purposes). 

Can you upgrade this command to open-source?

**Comment by JarrettSJohnson** [comment]
I'll file it internally for incentive support, but at the moment and likely for the foreseeable future, properties will remain incentive-only (I'll echo it up to others who are about to make that choice).
