### ISSUE TITLE
pymol install linux

### ISSUE THREAD

**Issue by lzygitk7** [schrodinger/pymol-open-source#367]
Can I use Pymol on a remote Linux server **without** GUI installed?

My server is Ubuntu 22.04, without any GUI installed.
Try to install Pymol via `pip install pymol‑2.5.0a0‑cp37‑cp37m‑win_amd64.whl`, the install process is smooth but when I try to activate Pymol via `$pymol`. I don't get any results.
If anyone has an idea about this, thank you in advance.

**Comment by pslacerda** [comment]
Yes, it's possible. You will need to use the API. For example:

```python
from pymol import cmd as pm
pm.fetch('1GXF')
```

Also check [this wiki](https://pymolwiki.org/index.php/Launching_PyMOL).
