### ISSUE TITLE
Custom menu colors?

### ISSUE THREAD

**Issue by wblankenfeldt** [schrodinger/pymol-open-source#383]
Hello,

I am using the new 3.x versions of PyMol and found a small inconvenience in the updated color scheme that the object menu (and some other menus) in Pymol3 uses: 

- the grey for inactive objects is simply too dark and almost blends into the black background, making it difficult to find/click objects to switch on
- the brighter grey for active objects could also be brighter / more white.

Can these colors be customized or would you care to brighten them up in one of the next releases?

Thank you!

Wulf

**Comment by TstewDev** [comment]
Hello @wblankenfeldt, 

Would you mind attaching a screenshot of what these grays look like on your system? I have a suspicion that they are appearing slightly differently for certain setups and I'm not sure if this due to PyMOL itself or something else like monitor settings.

I'm going to close this issue since the 3.X interface is not part of the open source repo, but know that we are aware of this feedback and will hopefully have some solution in a future release.

**Comment by wblankenfeldt** [comment]
Hi Thomas,
thanks for getting back to me - I will post a screenshot when I am back at the PC where I have this problem.
In the meantime: your suspicion about the setup may be correct - I am one of these elderly people who still insist on using shutter glasses and quad buffered stereo, meaning I have to work with outdated Nvidia hardware and drivers. My feeling is that the monitor (one of these old Asus gemstones that have a built-in emitter for the glasses) has a relatively dark mode to it and it gets even worse when I am wearing the glasses. I remember that I did not have this problem under PyMol2.x, though.
I'll see if I can boost brightness of the monitor - the colors look ok to me on other systems I work with (some Macs), still they seem to be darker than in the older PyMol.
Cheers,
Wulf

**Comment by TstewDev** [comment]
Hello again Wulf,

Luckily we have some similar hardware here in the office that we can test, so the screenshots are probably not even necessary. The colors are slightly more subtle in PyMOL 3.0 but the goal is certainly to have everything still be visible. Maybe we can add some additional settings or automatically boost the colors in quad buffered stereo? We'll look at a few different options and try to improve things in a future patch.

Thank you for raising this issue!
Thomas

**Comment by wblankenfeldt** [comment]
Hello,
just had a quick look at this again: the vanishing grey indeed seems to be a problem of the monitor/shutter glasses combination. I can improve it slightly by setting Nvidia Lightboost and contrast to maximum, but when I am using the shutter glasses, the greyed-out objects are quite difficult to read in the objects menu.
It would indeed be great if the grey could be made a little bit brighter.
Thanks!
Wulf
