### ISSUE TITLE
`mouse_selection_mode` setting interface

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#390]
Hi,

Just noted that the `mouse_selection_mode` interface isn't easy available. Where is it in PyMOL3?

Another quirk is that the green icon on left side of each object at contents panel is redundant to object/selection name color. When the object/selection is vanished, the icon is also. It isn't needed, so I think it should not be there.

**Comment by JarrettSJohnson** [comment]
Can you send a query to help@schrodinger.com? This pertains only to Incentive PyMOL.

**Comment by pslacerda** [comment]
The mouse selection mode  was a feature present in open source PyMOL 2.x but was removed in 3.x, so it is sensible to reintroduce it on the open source version.

The feature is important for many analysis.

**Comment by pslacerda** [comment]
So may be I that is confused. Where is the interface on 3.x on the GUI as it was on 2.x?

**Comment by pslacerda** [comment]
![image](https://github.com/user-attachments/assets/655d599f-8d2f-4070-ad31-e7771df57868)

**Comment by JarrettSJohnson** [comment]
Yeah, this is Incentive PyMOL 3.X (current master on this repo is Open-Source 3.X). The mouse selection mode is moved to the top left where your picture currently says "Segments". The `X-button-Controls` are at the bottom right where your image says `3-Button Viewing`.

**Comment by pslacerda** [comment]
Thank you, I see now!

But this definitly should be in open source too and I feel dumb to try to implement a feature that is already on incentive.

**Comment by TstewDev** [comment]
What feature are you trying to implement that's already in incentive?

**Comment by pslacerda** [comment]
The mouse selection mode interface is already on open source?

Sorry by the confusion.

**Comment by TstewDev** [comment]
No worries! The mouse selection mode toggle is the same as clicking on "Selecting" in the older version of the interface that open-source uses.
<img width="223" alt="Screenshot 2024-08-15 at 12 48 18 PM" src="https://github.com/user-attachments/assets/8d0450ea-81f5-4bb8-867b-26e864a5864f">
