### ISSUE TITLE
Unable to open pymol after successful installation

### ISSUE THREAD

**Issue by dyodyo121** [schrodinger/pymol-open-source#392]
I am currently running Ubuntu 22.04 and trying to install PyMol open source. I have successfully installed it but I cannot open the program. Can you help me with my problem?

**Comment by dyodyo121** [comment]
Hello,

There's no error message. I successfully installed pymol and check if it was placed in usr/bin which it was. It's just that the program is not opening at all.


________________________________

**Comment by ye11owSub** [comment]
Hmm, that sounds strange. Could you please tell me more about how you installed and ran it?

**Comment by dyodyo121** [comment]
Here were the following approaches that I did:


  1.
followed the git clone instructions (https://wiki.pymol.org/index.php/Linux_Install)
  2.
installed via conda-forge (https://anaconda.org/conda-forge/pymol-open-source) --> I installed it through conda base
  3.
installed through pip (https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL)


I used to successfully download pymol-open-source by using git clone when I was on Ubuntu 20.04 LTS so I also found it strange. When I installed Ubuntu 22.04 on a new system, all of my software essentially messed up big time due to backward compatibility issues. I assumed that pymol-open-source would not cause issues because the latest version is already written in python 3.



________________________________

**Comment by ye11owSub** [comment]
> installed through pip (https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL)

Could you please provide me with the logs that were generated after you ran the `pip install -v .` command in the pymol directory?

**Comment by dyodyo121** [comment]
Hi,

I could not locate the folder which was the installation path for pip install. I tried installing it using Ubuntu software (pymol-oss) and it worked. I am not sure what is wrong with the pip install function.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ye11owSub** [comment]
@dyodyo121 

To install the pymol project to any path you choose, you will need to specify the path using the `--prefix` flag

![изображение](https://github.com/user-attachments/assets/aaa132bc-6f59-44ce-9c16-7c14ebd5e57e)

Without the `--prefix` flag, pymol will be installed to your python site-packages directory (like any other python package installed using pip). You can verify this by running the `pip list` command.

![изображение](https://github.com/user-attachments/assets/b4f5c934-bd1e-43d7-b171-935383220771)

**Comment by ye11owSub** [comment]
@dyodyo121 try simply running `pymol` command in your terminal

**Comment by ye11owSub** [comment]
@JarrettSJohnson I assume this ticket can be closed
