### ISSUE TITLE
Error when using ray tracing

### ISSUE THREAD

**Issue by sbembenek18** [schrodinger/pymol-open-source#393]
I get the following errors when using the ray tracing and I change the from the default resolution of 150 to 300 --> 

`PyMOL>ray 1616, 1024, async=1
 Ray: render time: 0.37 sec. = 9722.5 frames/hour (0.37 sec. accum.).
Traceback (most recent call last):
  File "/data/Apps/anaconda3/envs/pymol_env/lib/python3.12/site-packages/pymol/Qt/utils.py", line 60, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/Apps/anaconda3/envs/pymol_env/lib/python3.12/site-packages/pmg_qt/pymol_qt_gui.py", line 694, in update_pixels
    form.input_width.setValue(width / factor)
TypeError: setValue(self, val: int): argument 1 has unexpected type 'float'`

It still renders the ray tracing but it is unclear if it doing it at the higher resolution.

**Comment by JarrettSJohnson** [comment]
I must've missed this one. Thanks for the issue report. It should still be rendering at the correct resolution; if there's any uncertainty, you could use the command that it provides directly.

**Comment by sbembenek18** [comment]
Many thanks for the quick reply!

I made that changes you showed and it seems to render correctly, but I still get this error --> 

`PyMOL>ray 1895, 1015, async=1
Traceback (most recent call last):
  File "/data/Apps/anaconda3/envs/pymol_env/lib/python3.12/site-packages/pmg_qt/pymol_qt_gui.py", line 936, in update_feedback
    self.update_progress()
  File "/data/Apps/anaconda3/envs/pymol_env/lib/python3.12/site-packages/pmg_qt/pymol_qt_gui.py", line 928, in update_progress
    self.progressbar.setValue(progress * 100)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

and

`Qt: Session management error: None of the authentication protocols specified are supported`
`

**Comment by JarrettSJohnson** [comment]
Thanks just pushed 11325a6014565700be9673236c9b7b6c856ea6d9 . Python 3.12 + PyQt are much stricter with these types

...for better or for worse :)

**Comment by sbembenek18** [comment]
Thanks. Looks like that fixed it. 

Yeah, I don't see anything happening as a result of that second error -- I'll let you know if otherwise.
