### ISSUE TITLE
can not find _cmd.py file

### ISSUE THREAD

**Issue by amina11** [schrodinger/pymol-open-source#394]
I tried to load the pymol, but it seems the \-cmd.py file is missing from the source code

**Comment by ye11owSub** [comment]
Hi @amina11, There is no _cmd.py file like this in the project. 
The `_cmd.py` module is built from C code. 
To work with this module, you will first need to build pymol project (command `pip install .`)

**Comment by ye11owSub** [comment]
@amina11 Also, [this link](https://github.com/schrodinger/pymol-open-source/blob/d82b626b60ef4382a49bbbf3b0327bad8d59e9e0/layer4/Cmd.cpp#L6241-L6542) to the source code of the _cmd module

**Comment by ye11owSub** [comment]
@JarrettSJohnson I assume this ticket can be closed

**Comment by amina11** [comment]
Hi @ye11owSub, thank you, yes, I actually first tired to build pymol  on my mac and did not succeed, so I thought maybe I could work with the source code, but now I managed the installation through the wiki page. thank you
