### ISSUE TITLE
Failing to split states

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#401]
There is a bug with the split states option rendering it unusable. The split objects doesn't appear neither on the new panel and neither on the legacy panel. Sample file attached.

I'm using  PyMOL(TM) 3.0.3 - Incentive Product.

Please, when will the new object panel be done?

[2bq0_A_rec_5f74_amp_lig_tt_docked.sdf.gz](https://github.com/user-attachments/files/17121124/2bq0_A_rec_5f74_amp_lig_tt_docked.sdf.gz)

**Comment by JarrettSJohnson** [comment]
Can you try `set hide_underscore_names, off` after doing the split states?

**Comment by pslacerda** [comment]
Thank you, sorry for the inconvenience!

I confused versions. I'm using Educational PyMOL, when will the new GUI support nested groups and sorting objects?

**Comment by TstewDev** [comment]
Nested groups will be supported in the upcoming 3.1 release (likely sometime next month). Reordering of groups (and objects within groups) will also be supported in 3.1. For objects not in groups, drag reordering is already possible by holding down the right mouse button.
