### ISSUE TITLE
map_set copy operator crash always 

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#41]
Hi, 

Doing ```map_set map_name, copy, my_map``` always crashes PyMol. Is there a bug? 
I am on Ubuntu using PyMol2.2

**Comment by JarrettSJohnson** [comment]
Hello,

Thanks for submitting an issue. I cannot reproduce on either linux or windows. Can you provide a minimum, complete example that can reproduce your bug?

Thank you.

**Comment by giagitom** [comment]
Hi Jarrett, try executing this lines 
```
fetch 1c0k, async=0
map_new map, gaussian, 4, 1c0k
map_set mapCopy, copy, map
```
i get ```Segmentation fault (core dumped)```

**Comment by JarrettSJohnson** [comment]
Thanks. I can now reproduce the crash.

**Comment by giagitom** [comment]
Thanks Jarrett, now it don't crush, but if I try to load the map i attached and then copy it, it results in a messed up map.  
here the map: https://www.dropbox.com/s/37abshy1w2zfbop/map_issue.ccp4?dl=0
here the same map copied: https://www.dropbox.com/s/a4g7i7o5dns1jja/map_issue_copied.ccp4?dl=0

**Comment by JarrettSJohnson** [comment]
Thanks! We can give it a look. In the meantime, can you open a new ticket since it's a different issue. I'm guessing not many people seem to use this functionality. :)

**Comment by giagitom** [comment]
Sure, thanks!
