### ISSUE TITLE
Selection by mouse does not work with NVIDIA driver installed from repo

### ISSUE THREAD

**Issue by SamuelHomberg** [schrodinger/pymol-open-source#415]
Installing PyMOL, either via 
`mamba install pymol-open-source` 
or the commercial version via 
`conda install -c conda-forge -c schrodinger pymol-bundle` 
don't allow the selection of anything by clicking in the 3-button viewing mode on my workstation. I tested different python versions (3.9, 3.12). 
A fresh install of open source PyMOL on Ubuntu via WSL does not have this problem, but I have no other machines to test this on.
Selecting via the select command is still possible.

Machine details:
- Rocky Linux 9.5 (Blue Onyx)
- 128 GB Memory
- AMD Ryzen threadripper pro 5975wx 32-cores
- Nvidia GeForce RTX 3090

**Comment by SamuelHomberg** [comment]
I wanted to use Chimera instead of PyMOL, but currently Chimera struggles with the repo install of the nvidia drivers (following the instructions [here](https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/index.html#rhel-rocky-installation)), so I reinstalled the driver manually from the `.run`-file. This also fixed the issue with selecting not being available by  clicking. 

Please let me know if this is of interest or if I should close the issue.

**Comment by JarrettSJohnson** [comment]
Thanks for the report. Yes, feel free to close if your issue's resolved. I haven't heard of any driver issues like this lately. I'd ask if you could snag the NVIDIA driver name and version that didn't work so we can make note, but if your system works currently, then I wouldn't worry about it.

**Comment by SamuelHomberg** [comment]
All right, thanks for the response. I'll add the driver Version tomorrow.

**Comment by SamuelHomberg** [comment]
Installed driver version from `.run` file is `550.135`, this is the one that worked for me.

**Comment by JarrettSJohnson** [comment]
By chance do you know which version _didn't_ work?

**Comment by SamuelHomberg** [comment]
Ah, sorry I misread (and now learned about the `dnf history`). This is the driver version:
```
    Removed nvidia-driver-3:565.57.01-1.el9.x86_64           @@System
```

**Comment by JarrettSJohnson** [comment]
Thanks, as of today, it seems that version `565.77` seems to be their beta/non-production one. So there may be some bugs they're still ironing out first. I'll revisit it when this version becomes their main, recommended one.
