### ISSUE TITLE
Issue copying map

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#43]
Hi, I'm getting an issue coping a map. 
If I try to load the map i attached and then copy it, it results in a messed up map.  
here the map: https://www.dropbox.com/s/37abshy1w2zfbop/map_issue.ccp4?dl=0
here the same map copied: https://www.dropbox.com/s/a4g7i7o5dns1jja/map_issue_copied.ccp4?dl=0

**Comment by speleo3** [comment]
Just to clarify, I assume this is the recipe to show the issue:
```
load map_issue.ccp4
isomesh mesh1, map_issue                     ;# correct
map_set map_issue_copied, copy, map_issue
isomesh mesh2, map_issue_copied              ;# not correct

**Comment by giagitom** [comment]
Yep, exactly

**Comment by speleo3** [comment]
Looks like `map_set` can't handle the transformation matrix (skew matrix from CCP4 file)

**Comment by giagitom** [comment]
I understand. Is there a way to fix this?

**Comment by speleo3** [comment]
I've added map support to `cmd.copy()` in 9ad33a3734a611ff23c45205e2d7ffaafa5fb52c. Can you use that?
```
copy map_issue_copied, map_issue
```

**Comment by giagitom** [comment]
Now it works, but there is an other problem (probably related to this). The image shows two isosurfaces and a spheres representation colored by element. The lower isosurface uses the map generated normally using ```cmd.map_new(map_original,.....)``` and has a correct ramp coloring. The upper isosurface has been created by copying the original map with ```cmd.copy(map_copied,map_original)``` and then transforming the map using ```cmd.transform_object(map_copied,matrix,transpose=1)```. The transformation of the map is wrong, because the isosurface should be exactly in the same position of the spheres representation. Also the isosurface coloring should be the same of the lower one.
![Screenshot 2019-07-01 17:36:16](https://user-images.githubusercontent.com/20627977/60449257-85906080-9c27-11e9-9436-4e3d15edab9e.png)

**Comment by giagitom** [comment]
@speleo3, should i open a new issue for the last problem?

**Comment by speleo3** [comment]
yes this is a separate problem, please open a new issue. Thanks.

**Comment by giagitom** [comment]
No need to open a new issue. There was an issue on my side I solved. Thanks again for the help!
