### ISSUE TITLE
load_traj's option `selection` does not work for xtc format

### ISSUE THREAD

**Issue by brisvag** [schrodinger/pymol-open-source#44]
I tried to use `load_traj filename.xtc, objectname, selection=somestuff` to only load a specific subset of atoms from the trajectory.

After raising the issue on the mailing list it turns out that, apparently, this is only implemented for AMBER `.trj` files.

Is there any plan to extend this functionality to other formats such as `.xtc` in the future?
I imagine this is a tough cookie, but I'll throw it here as a feature request nonetheless.

**Comment by speleo3** [comment]
For reference: https://sourceforge.net/p/pymol/mailman/message/36702612/

@brisvag for your use case, would the following be equivalent?
```
remove objectname and not somestuff 
load_traj filename.xtc, objectname
```

**Comment by brisvag** [comment]
@speleo3 I also thought it would be equivalent, but that second command actually results in an error. 
For example, in my system:
```
ObjectMolecule: plugin 'xtc' cannot open file because the number of atoms in the object (5434) did not equal the number of atoms in the 'xtc' (11011) file.
```

If the `plugin 'xtc'` was able to overcome this problem and just load the common subset of atoms, I suppose it would be equivalent.

**Comment by speleo3** [comment]
Your **xtc** file has more atoms than your object? In that case, the selection argument wouldn't help because it selects within the object, not within the trajectory file. The **xtc** file has no topology information, it's simply a list of coordinates that matches the number and ordering of atoms in a corresponding topology file.

May I ask: Why don't you have a matching topology file for the trajectory? And do you know what that difference in atom count is? Could be hydrogens?

**Comment by brisvag** [comment]
I think we may be referring to different things. What were you trying to achieve with:
```
remove objectname and not somestuff 
load_traj filename.xtc, objectname
```
if not removing part of the system before loading the trajectory?

I will explain with a use case to make sure my problem is clearer:
Let's say I have a trajectory file containing a protein and a lipid bilayer in water. However, water is quite useless for most purposes, and loading everything **but* water would make loading the trajectory significantly quicker and lighter on the memory usage.

One solution to this problem is to operate on the trajectory with an external tool to get rid of the waters and then deal with that. This is slow (need to wait for trajectory conversion) and takes up disk space.

My current solution is to load everything anyways and only **after** the command is done, delete all the waters. This is obviously not a good solution.

What I was hoping to do with `load_traj`, is to select only part of the system **before** loading it, which would solve all my problems.

As far as `xtc` files not having topology information: topology information is already present in pymol because a system needs to be loaded before the trajectory. Wouldn't that be enough? Pymol knows which atom ids are part of selection `somestuff`, and those should correspond to those loaded into pymol. Unless somehow the correspondence is coordinate-based or something else I'm missing?

**Comment by speleo3** [comment]
Thanks, this makes perfect sense now! And the misunderstanding was on my side, the selection argument for AMBER `trj` files works exactly like you're describing.
