### ISSUE TITLE
PREFIX_PATH not auto-detected with virtual environment

### ISSUE THREAD

**Issue by drewsilcock** [schrodinger/pymol-open-source#46]
The `get_prefix_path()` function in `setup.py` used to determine the path for include folders fails to correctly determine the prefix when using Python within a virtual environment. The relevant code is:

```python
if sys.platform == 'darwin':
    for prefix in ['/sw', '/opt/local', '/usr/local']:
        if sys.executable.startswith(prefix):
            return [prefix] + X11
```

For me, when running outside of the virtual environment, `sys.executable == "/usr/local/opt/python/bin/python3.7"`. This means that the function gives prefix path `"/usr/local"` which means that include folders like `/usr/local/include/freetype2`.

However, when running inside a venv, the `sys.executable` gives a different value:

```sh
$ python -m venv .env
$ source .env/bin/activate
$ python -c "from sys import executable; print(executable)"
> /path/to/working/directory/.env/bin/python
```

This means that the`get_prefix_path()` doesn't find the necessary include headers in `/usr/local/include/freetype2` and other directories and the compilation fails with errors like:

```sh
> clang++ -std=c++11 -D_PYMOL_LIBPNG -D_PYMOL_FREETYPE -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS -D_PYMOL_NO_MSGPACKC -D_PYMOL_NO_MAIN -D_PYMOL_OSX -D_PYMOL_NUMPY -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/molfile_plugin/src -I/Users/drew/.../.env/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/Users/drew/.../.env/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c layer1/TypeFace.cpp -o build/temp.macosx-10.14-x86_64-3.7/layer1/TypeFace.o -Wno-narrowing -Wno-char-subscripts -ffast-math -funroll-loops -O3 -fcommon -fno-strict-aliasing
> layer1/TypeFace.cpp:25:10: fatal error: 'ft2build.h' file not found
> #include <ft2build.h>
>          ^~~~~~~~~~~~
> 1 error generated.
> error: command 'clang++' failed with exit status 1
```

**Comment by speleo3** [comment]
`get_prefix_path()` is a heuristic, tailored to get common environments (like MacPorts, Homebrew, Fink, Conda) right. If your environment is something custom, you'll need to set the `PREFIX_PATH` variable (see [INSTALL](https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL) or [PyMOLWiki](https://pymolwiki.org/index.php/Linux_Install#Libraries_in_non-standard_places)). In your case, try:
```sh
export PREFIX_PATH=/usr/local
```
Of course we're open to suggestions how to improve `get_prefix_path()`.

**Comment by drewsilcock** [comment]
Thanks for pointing out `PREFIX_PATH`, just tried this in my venv and it works a charm.

Using virtual environments to locally install packages is in my experience a very common use case ("It is always recommended to use a virtual environment while developing Python applications." - [Installing packages using pip and virtual environments](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)) so being able to handle this automatically definitely seems valuable.

I imagine that if you're on macOS, the chances of you using Homebrew to install header dependencies in `/usr/local/include` are pretty high, even if you're not using a Python interpreter provided by Homebrew - would there be any harm in just adding this folder to the prefix path if you're on macOS regardless?
