### ISSUE TITLE
how do you load an mmtf file that's been loaded from python3?

### ISSUE THREAD

**Issue by danpf** [schrodinger/pymol-open-source#49]
If I have a script that reads in an mmtf file, is there a way to get pymol to read that without dumping it to a file?

currently I believe it is broken due to the way bytes are handled.

error:
```
Error in MMTF_unpack_from_msgpack_object: the entry encoded in the MMTF is not a map.
```

I'm pretty sure in the conversion from python -> c++ is keeping the `b'`, so it's unable to read and thinks it is broken, I could be wrong though!

**Comment by speleo3** [comment]
good catch, yes this doesn't work. Definitely something we want to support and need to fix.

**Comment by speleo3** [comment]
I pushed a fix, now the following should be correct:
```python
contents = open('example.mmtf', 'rb').read()
cmd.load_raw(contents, 'mmtf')
```

**Comment by danpf** [comment]
thanks @speleo3 !

**Comment by danpf** [comment]
Hey @speleo3 , would you happen to know how soon will this be in the conda repo?

**Comment by speleo3** [comment]
> would you happen to know how soon will this be in the conda repo?

I'll work on a bugfix release shortly.

> is there a way with this to now load 2 mmtf as states to the same object?

This should be correct:
```python
cmd.load_raw(contents1, 'mmtf', "foo1")
cmd.load_raw(contents2, 'mmtf', "foo2")
cmd.create("foo1", "foo2", 0, -1) # append all foo2 states to foo1
cmd.delete("foo2")
```

**Comment by speleo3** [comment]
>> would you happen to know how soon will this be in the conda repo?

> I'll work on a bugfix release shortly.

We've uploaded version 2.3.3 to anaconda.org ([release notes](https://pymol.org/dokuwiki/?id=media:new23#pymol_v2.3.3_maintenance_release_august_21_2019))

**Comment by danpf** [comment]
Wow that was fast! Thank you so much!
