### ISSUE TITLE
Changes 1.9 to 2.3 which would break shaders?

### ISSUE THREAD

**Issue by mathog** [schrodinger/pymol-open-source#5]
The last time I built Pymol open source version it was 1.9 on 32 bit linux and windows 7 (in mingw32 environment).  It ran the same in both places, as far as I could tell.  Yesterday I tried to build what was current on github, which when built identifies itself as "2.3.0a" on the same machines/environments.  It works on linux still,  but not windows.   The failure mode is just a bunch of error messages, the display is still fine.  

The incentive builds are now only 64 bits and I'm wondering if maybe there is now a problem with 32 bits in some situations?  Probably not, but thought I'd ask.

The other change I noticed is that the OpenGL code started using the newer 2.0 and up includes, which 1.9.0 didn't.  As you can see below, the one machine I have which identifies itself as having GL >2 is the one which now emits the error messages.   The case 2 (problem) machine has confusing messages at start, where it says shaders are available, then geometry shaders are not available.   Are there two different types of shaders? 

These machines are all hardware identical other than that the one running W10 has 4Gb of RAM and the others only 2Gb.  I checked and pymol_path has the same shaders contents in the same places in all contexts, which is .../site-packages/pymol/pymol_path/data/shaders.   Yesterday's builds all used "git clone" to download the source tree, the 1.9.0 builds were svn from sourceforge.  Test file 1du0.cif has some cylinders displayed, and that triggers the messages.

Edit:  I just realized that none of the ones which work without error messages have any shaders available.  So I con't say that 2.3.0 broke shaders, since I have never seen them work.  Need to try an older incentive build (32 bit) on the W7 machine with OpenGL >2.

Case 1:
Linux build, 32 bits, 2.3.0.0 code (yesterday, from github)
 Detected OpenGL version 1.4. Shaders and volumes unavailable.
 OpenGL graphics engine:
  GL_VENDOR:   NVIDIA Corporation
  GL_RENDERER: Quadro FX 1400/PCIe/SSE2/3DNOW!
  GL_VERSION:  1.4 (2.1.2)

  load 1du0.cif and it displays without warnings.  So all good.

----
Case 2:  (the problem)
Windows 7, MINGW 32 bit build,  2.3.0.0 code (yesterday, from github)
 Detected OpenGL version 2.1.  Shaders available.
 Geometry Shaders not available.
 Detected GLSL version 1.2.0
  OpenGL graphics engine:
  GL_VENDOR:   NVIDIA Corporation
  GL_RENDERER: Quadro FX 1400/PCIe/SSE2/3DNOW!
  GL_VERSION:  2.1.2
  
  load 1du0.cif and it displays with lots of warnings, scrolling by without stop.  These are:

GL_ERROR : 0x0502
CShaderPrg_Link-Error: Shader program failed to link name='cylinder'; GL_MAX_VARYING_FLOATS=32 log follows.
Fragment info
-------------
0(45) : error C5041: cannot locate suitable resource to bind parameter "color1"
0(46) : error C5041: cannot locate suitable resource to bind parameter "color2"

At top of run it says (when in either a mingw32 or cmd.exe window)
Qt not available, using GLUT/Tk interface
 PyMOL(TM) Molecular Graphics System, Version 2.3.0a0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.

Case 3,  Same machine, the older build:
Windows 7, MINGW32 32 bit build, v 1.9.0.0
 Detected OpenGL version 2.0 or greater.  Shaders available.
 Detected GLSL version 1.2.0

 load 1du0.cif and it displays with no warnings. Display looks just like 2.3.0.

Case 4:
Windows 10 64 bit. 2.2.0.0 Incentive build.
 Detected OpenGL version 1.1.  Shaders and volumes unavailable.
 OpenGL graphics engine
   GL_VENDOR Microsoft Corporation
   GL_RENDERER GDI Generic
   GL_VERSION 1.1.0
   
 load 1du0.cif and it displays with no warnings. Display looks just like 2.3.0.

Unfortunately Nvidia never wrote a W10 driver for this graphics card, and it falls back to GL 1.1.  Have not yet been able to test the 2.3.0a mingw32 binary on this system because it is missing some dll's which keep it from running right.  Once that is solved it will be tested there too.  I expect though that it will run normally, since it will see only the lower GL.

**Comment by mathog** [comment]
Used 1.8.2.1 incentive on same machine as Case 2 (Windows 7, 32 bit).  It has very similar problems to 2.3.0a on this machine.

startup messages:

```
PyMOL(TM) 1.8.2.1 - Incentive Product
 Copyright (C) Schrodinger, LLC

 This PyMOL Executable Build is available only to PyMOL Power, Casual, and
 Developer Users who have a valid license to use this software product. Any
 other usage is specifically prohibited and may constitute a violation of
 United States and international copyright laws.

 This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 2.0 or greater. Shaders available.
 Geometry shaders not available
 SMAA not available
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   NVIDIA Corporation
  GL_RENDERER: Quadro FX 1400/PCIe/SSE2/3DNOW!
  GL_VERSION:  2.1.2
 Adapting to Quadro hardware.
 Detected 2 CPU cores.  Enabled multithreaded rendering.
 ExecutiveLoad-Detail: Detected mmCIF
 CmdLoad: "C:\Temp\1du0.cif" loaded as "1du0".

```
Loaded 1du0 and NO cylinders are visible when loaded.  Not sure why, maybe the cif was made on 1.9 and has some backwards compatibility issue with 1.8.  The molecule and waters are visible though.  Turn on "show as cartoon" and it emits a very large number of these

```
CShaderPrg_Link-Error: Shader program failed to link name='cylinder'; GL_MAX_VARYING_FLOATS=32 log follows.
Fragment info
-------------
0(44) : error C5041: cannot locate suitable resource to bind parameter "color1"
0(45) : error C5041: cannot locate suitable resource to bind parameter "color2"

```
It stops sending these eventually.  The 2.3.0a build keeps sending them forever.  Other than that the number of messages is finite here the two versions seem equally broken, shaderwise.

**Comment by speleo3** [comment]
I understand that you're using a rather old graphics card which only supports the [minimum number of 32 varyings](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGet.xhtml), which would be the memory aligned equivalent of 8 `vec4`. The current version of the cylinder shader doesn't consider this limitation. The [previous version](https://github.com/schrodinger/pymol-open-source/commit/f21c61958ed6dc0777679c5d16534a310cacdbcb#diff-34ebad10333fb6d5d014f713d123e618) indeed tried to reduce the number by packing some varyings together (I'm still counting 9 though, maybe bgTextureLookup was optimized out because it wasn't used).

Try this patch: https://pymol.org/tmp/cylinder-shader-32-varying-floats.patch

**Comment by mathog** [comment]
Applied it - made no difference.  Exactly the same problem.  Thanks for the patch anyway.

I did discover that if 1du0 (in cif or PDB) is loaded by default PyMol makes a cartoon of it and the messages start running away, if I then do in the top PyMol window:

`file ->reinitialize -> current settings`
the messages stop immediately.  The display looks more or less the same (except bars for the DNA bases appear, but the cylindrical parts are still there, and those bars are themselves cylindrical).  The right pane in the viewer window is finally drawn, which it is not while the messages roll by.

Which is all very odd.  Why would the cylindrical portions cause problems sometimes and not others if this is a shader issue?

I think the 1.8.2.1 incentive version is actually having very much the same issues.  The running away messages in the 2.3.0 version are seen in the CMD window where the bat starts and also in the top Pymol window.  However, the number of messages in the top window is finite in both program versions.  1.8.2.1 hides or does not have the CMD window, so any messages sent there are never visible.  If they are running away, I would never know it.  The other symptom though, while this is going on, is that the right pane (the part that says "mouse mode" and has a summary of the molecules loaded, mouse button actions, etc.)  in the bottom (viewer) window is not drawn.  That is also the case for 1.8.2.1.  Trying to reinitialize 1.8.2.1 the same way crashes it.

**Comment by mathog** [comment]
1bnz and 1du0 both have DNA in them.  Load either one and it starts the cascade of messages.  Use the reinitialize trick.  Then load the other.  No more messages appear.  So there is some issue the first time PyMol starts up and sees a structure with DNA in it related to this cylinder business.

Start PyMol, use the reinitialize trick, then load 1bnz or 1du0 also avoids the endless cylinder messages.  In fact no such messages appear at all.  The same is true for the 1.8.2.1 incentive build.

Why would a reinitialize do that?  Doesn't pymol "initialize" when it starts?  How does reinitialize differ from initialize, because apparently it does.

**Comment by speleo3** [comment]
So with the patch, you still get the `GL_MAX_VARYING_FLOATS=32` error?

There is no `file ->reinitialize -> current settings`.
There is `File > Reinitialize > Original Settings`, and it will disable shaders ("Original" [value is off](https://github.com/schrodinger/pymol-open-source/blob/master/layer1/SettingInfo.h#L747)), because shaders have been enabled when OpenGL 2.x was detected during launching. So all you're describing makes sense, you have error messages and incomplete graphics while `use_shaders=on`, and no errors while `use_shaders=off`.

Loading a session does not change the `use_shaders` setting (it's [blacklisted](https://github.com/schrodinger/pymol-open-source/blob/master/layer1/Setting.cpp#L639)).

If you install PyQt5, it will be used instead of Tcl/Tk/GLUT. Compile PyMOL with `--no-glut` to disable the GLUT (and thus Tcl/Tk) fallback.

**Comment by mathog** [comment]
That is correct, the message didn't change at all.

The exact same 32 bit 2.3.0a binary was tried last night on my home W7 (64) machine.  It started and loaded 1du0  with no problems whatsoever.  It describes graphics as:

 Detected OpenGL version 3.3. Shaders available.
 Geometry shaders not available
 Detected GLSL version 3.30.
 OpenGL graphics engine:
  GL_VENDOR:   Intel
  GL_RENDERER: Intel(R) HD Graphics 4000
  GL_VERSION:  3.3.0 - Build 8.15.10.2725
 Detected 8 CPU cores.  Enabled multithreaded rendering.
Plugin 'lightingsettings_gui' only available with PyQt GUI.

The DNA base "spokes" are visible in the initial rendering here.  Those are not
visible on the original W7 32 bit machine whenever it is having "cylinder" problems.  That seems
to be the graphics element which is triggering this.  The DNA backbone looks like it might be composed of cylindrical sections, but it is rendered either way.

Is there anything between use_shaders=on and use_shaders=off?  In this case the cylinder shader breaks, with some other old card or in an unusual environment some other shader might break.  Is there anything in the code that would allow shaders to be disabled by class (as when an error is seen) or must all shaders go away together?

Thanks for explaining the reinitialize business.  I think I must have subconsciously merged the "store current settings" and "Original Settings" options.

**Comment by speleo3** [comment]
> Is there anything between use_shaders=on and use_shaders=off?

you can try:
```
set render_as_cylinders, off
set use_shaders
```

We automatically do this if compilation of the cylinder shader fails at run time. In your case, compilation succeeds, but linking the shader program fails I think.

**Comment by mathog** [comment]
Those commands did the trick.  It opened 1du0 without any problems.

Thanks!

**Comment by speleo3** [comment]
Closing this. `render_as_cylinders=off` is the suggested workaround.
