### ISSUE TITLE
Installed without error but keep report 'Segmentation fault' when I ran it

### ISSUE THREAD

**Issue by IndigoMad** [schrodinger/pymol-open-source#51]
Here is the error:
[indigomad@localhost pymol-open-source-2.3.0]$ pymol
/usr/bin/pymol: line 3:  2882 Segmentation fault      (core dumped) "/usr/bin/python" "/usr/lib64/python2.7/site-packages/pymol/__init__.py" "$@"

I will be appreciate if anyone can help.

**Comment by speleo3** [comment]
This is very incomplete information. Which operation system? Can you run this with gdb and obtain a stack trace?
