### ISSUE TITLE
Debug PyMOL scripts

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#56]
How to debug PyMOL scripts? Could the `cmd` import check be removed now in 2.x?

When I try to debug with `breakpoint()` or `import pdb; pdb.set_trace()` it fails with:

>  pymol.CmdException:  Error: use "from pymol import cmd" instead of "import cmd"

The relevant bits are

https://github.com/schrodinger/pymol-open-source/blob/27014c9e936b15a56ec8f5ae689127b2a0cc7b1d/modules/pymol/__init__.py#L582-L590

Seems that simply delete these lines would erradicate the issue. The issue https://github.com/schrodinger/pymol-open-source/issues/18 is related to this.

EDIT: just deleted and pdbpp started to work.

**Comment by speleo3** [comment]
The exception was already removed in 2.3 (now only prints a warning).

**Comment by pslacerda** [comment]
Thank you. I was looking at master, isn't it the upstream?
