### ISSUE TITLE
pymol w/ PyQt5 fails to switch to quad-buffered stereo mode

### ISSUE THREAD

**Issue by hsk17** [schrodinger/pymol-open-source#57]
i have installed pymol 2.3.0 using "python3 setup.py install", no errors / warnings.
in it's drop down menu, pymol offers "Quad-Buffered Stereo" display mode.
when starting on our nvidia quadro equipped linux boxes, it seems to recognize the graphics hardware and says "Adapting to Quadro hardware" in it's start up messages; but when clicking Display -> Stereo, it switches to side-by-side stereo; manually choosing Display -> Stereo Mode -> Quad-Buffered Stereo gives message "stereo_mode set to 1" (i.e. quad-buffer) but goes back to normal display mode.
then, i re-installed pymol using "python3 setup.py --glut install" and found that "pymol -w pmg_tk" behaves as expected, i.e., clicking Display -> Stereo activates quad-buffered stereo display.
any way to get quad-buffered stereo working in pyqt5-pymol?  as the tk-interface version seems to have other problems and has other drawbacks.

**Comment by speleo3** [comment]
Short answer: Launch PyMOL with `-S`:
```
pymol -S
```
Long answer: Stereo auto-detection only works properly with Qt 5.6. With later versions, the attempt to auto-detect stereo hardware messes up systems which don't have stereo, that's why we currently skip the auto-detection with those Qt versions.

**Comment by hsk17** [comment]
thanks, this works
