### ISSUE TITLE
 MacPyMOL-v1.3r1-edu.tar.bz2 did not work for the new mac system

### ISSUE THREAD

**Issue by Huihuimu** [schrodinger/pymol-open-source#58]
MacPyMOL-v1.3r1-edu.tar.bz2 did not work for the new mac system

**Comment by speleo3** [comment]
How about using the latest version of PyMOL?

**Comment by Huihuimu** [comment]
i will try. I downloaded the newest version, but I saw the Mac version on the tutorial site. Thanks
