### ISSUE TITLE
dump verbose option

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#62]
Hi,

The dump option could have a verbose option.

Seems that ExecutiveDump, ObjectMeshDump and ObjectSurfaceDump should be modified to have such option.

**Comment by pslacerda** [comment]
I expect the option so the message `" ObjectMeshDump: %s written to %s\n"` doesn't get written.

https://github.com/schrodinger/pymol-open-source/blob/bd75bae3926fc1e499ca1d6f4437d00e123817cc/layer2/ObjectMesh.cpp#L358

**Comment by speleo3** [comment]
Got it, thanks. Pull request welcome!

You can also disable "actions" feedback before calling dump:
```
feedback disable, objectmesh, actions
feedback disable, objectsurface, actions
```

**Comment by pslacerda** [comment]
I'll get time to do it this week.

Just one question. Is `State.Matrix.data()` the transform matrix (the same as `cmd.get_object_matrix()`)? I didn't figured out where are map coordinates if any.
