### ISSUE TITLE
spectrumany - better interpolation than RGB

### ISSUE THREAD

**Issue by smsaladi** [schrodinger/pymol-open-source#68]
If I understand this correctly, `spectrumany` does a linear interpolation of R, G, B primaries in the (RGB space):

https://github.com/schrodinger/pymol-open-source/blob/724064767b1e8955c7296e9507112f3cb55662a1/modules/pymol/viewing.py#L2200-L2201

At least for 2D plotting, it's nice to choose colors that are perceptually uniform, keeping luminosity constant across the palette being a first pass at this. However, lerping in RGB doesn't keep luminosity constant.

It would be nice to have a more detailed interpolation for `spectrumany` as well. Would you be open to such a PR?

**Comment by speleo3** [comment]
Thanks for the suggestion. Yes we would be open to a PR. Though I think I already have the code ready :-) See here: https://github.com/schrodinger/pymol-open-source/commit/067ab6a8ac55d265f6961656de6418842b8e88d3

Would this satisfy your feature request?

**Comment by smsaladi** [comment]
Cool!! This is sweet!
