### ISSUE TITLE
Mesh construction code location

### ISSUE THREAD

**Issue by nyue** [schrodinger/pymol-open-source#7]
Hi,

  I'd like to experiment with changing the mesh (currently they look like tri-mesh) that gets constructed when a PDB file is loaded.

  May I know where in the code are the mesh constructed so I can see how they are constructed?

Cheers

**Comment by JarrettSJohnson** [comment]
Passing through some older tickets. This one hasn't been addressed yet, but the answer isn't really as straightforward. Our intermediate graphics representations are generated/serialized at the rep (sticks, cartoons, spheres, etc...) level and are translated to OpenGL (or other). Most of the fundamental geometry calculations can likely be found in layer2/Rep*.cpp (https://github.com/schrodinger/pymol-open-source/blob/master/layer2/RepCartoon.cpp#L2410 as an example for cartoon). There's a lot of code to sift through, but for anyone who's curious, there it is.
