### ISSUE TITLE
Containerised deployment option

### ISSUE THREAD

**Issue by CharlieLaughton** [schrodinger/pymol-open-source#72]
Hi,

As part of a project for the [UK Biomolecular simulation community](http://ccpbiosim.ac.uk) we are developing a library of containerised popular applications, and would like to include a "scripting-only" version of Open Source Pymol in this (i.e., delivering the "pymol -cq" command only). The library system is called *pinda* and you can see more [here](https://bitbucket.org/claughton/pinda). In essence, it's a bit like Conda or pip, but based on Docker/Singularity containers. We believe this lies within your licensing conditions but please let us know if you think there may be an issue.

Regards, Charlie

**Comment by speleo3** [comment]
Hi Charlie,

Yes this lies withing our licensing conditions. We only ask that you don't name your package "pymol" to avoid any confusion with official packages (and to comply with the trademark notice, see [LICENSE](https://github.com/schrodinger/pymol-open-source/blob/master/LICENSE)). Any other name should be fine (looks like you want to use "pymolqc"? That works. "pymol-open-source" works as well of course).

Thomas

**Comment by CharlieLaughton** [comment]
Many thanks - "pymolqc" will indeed be its name.
