### ISSUE TITLE
ObjectMolecule: plugin 'netcdf' failed to read atoms

### ISSUE THREAD

**Issue by cgohlke** [schrodinger/pymol-open-source#73]
Hello,

I am trying to get the recently added netcdf molfile plugin to work on Windows. 

The current master branch compiles and links with netcdf-c-4.7.3 but opening any nc file fails with `ObjectMolecule: plugin 'netcdf' failed to read atoms.` The files seem to open correctly with ncdump. I also tried to rebuild netcdf4-c with `USE_NETCDF4=OFF` to force netcdf3 format to no avail. 
Any idea what could be wrong?

**Comment by speleo3** [comment]
Have you tried using the [load_traj](https://pymolwiki.org/index.php/Load_traj) command? Looks like *nc* files can also contain structures, not only trajectories, so using the `load` command in PyMOL will go for the structure (and fail if there is none). Logic to load structure and trajectory in one go is currently not implemented.

**Comment by cgohlke** [comment]
Thank you! That worked with the `USE_NETCDF4=OFF` version of netcdf-c-4.7.
