### ISSUE TITLE
Bug: cmd.get_atom_coords() fails silently if atom does not exist

### ISSUE THREAD

**Issue by jaredsampson** [schrodinger/pymol-open-source#74]
I came across this in tracking down a [bug](https://github.com/Pymol-Scripts/Pymol-script-repo/issues/108) in `elbow_angle.py` in the script repo.

The problem is that `cmd.get_atom_coords()` fails to provide a return value if the atom specified by the selection doesn't exist, and as far as the Python session is concerned, it appears as though the command weren't issued at all.

```
reinitialize
fab A, ala

# Works with existing atom
ca = cmd.get_atom_coords('n. CA')
print('CA coords:', ca)
## CA coords: [-0.0009000778081826866, 0.06370003521442413, -0.49050000309944153]

# Fails silently (i.e. no exception, but no value is assigned to cz)
cz = cmd.get_atom_coords('n. CZ')
print('CZ coords:', cz)
## NameError: name 'cz' is not defined
```

If the atom doesn't exist, I would hope for either a warning or error printed to the console, and expect at least the return value to be `None`.

This should be addressed in `CmdGetAtomCoords()`, perhaps something similar to the following (completely untested) patch (sorry, haven't built Open-Source Python in a while and having dependency issues...):

```diff
diff --git a/layer4/Cmd.cpp b/layer4/Cmd.cpp
index e5ca0e6f..69513114 100644
--- a/layer4/Cmd.cpp
+++ b/layer4/Cmd.cpp
@@ -4905,6 +4905,10 @@ static PyObject *CmdGetAtomCoords(PyObject * self, PyObject * args)
     if(ok) {
       return PConvFloatArrayToPyList(vertex, 3);
     }
+    else {
+      PyObject *result = NULL;
+      return APIAutoNone(result);
+    }
   }
   return APIFailure(G);
 }
```

**Comment by jaredsampson** [comment]
I can confirm that the above patch builds returns `None` when the selected atom doesn't exist.  However, it also returns `None` when more than one atom is contained in the selection.

```
cz = cmd.get_atom_coords('n. CZ')
print('CZ coords:', cz)
## CZ coords: None
print(cmd.get_atom_coords('ala'))
## None
```

So it may be necessary to check the number of atoms in the selection as well.

**Comment by speleo3** [comment]
Thanks for the bug report Jared. The function raises `pymol.CmdException` if the atom doesn't exist. And I think your [pull request](https://github.com/Pymol-Scripts/Pymol-script-repo/pull/109) correctly takes that into account.

What's silent is the PyMOL command line, that should be improved. We could add a message to the exception, then it won't be silent. An exception with an appropriate error message is better than returning None I think.

**Comment by speleo3** [comment]
I think a patch like this would help:
```patch
diff --git a/layer4/Cmd.cpp b/layer4/Cmd.cpp
index e5ca0e6fc..561d3da0a 100644
--- a/layer4/Cmd.cpp
+++ b/layer4/Cmd.cpp
@@ -4894,19 +4894,25 @@ static PyObject *CmdGetAtomCoords(PyObject * self, PyObject * args)
   OrthoLineType s1;
   float vertex[3];
   int ok = false;
+  const char* error = nullptr;
   API_SETUP_ARGS(G, self, args, "Osii", &self, &str1, &state, &quiet);
   APIEnter(G);
   {
     ok = (SelectorGetTmp(G, str1, s1) >= 0);
     if(ok)
       ok = ExecutiveGetAtomVertex(G, s1, state, quiet, vertex);
+    else {
+      error = "invalid selection";
+    }
     SelectorFreeTmp(G, s1);
     APIExit(G);
     if(ok) {
       return PConvFloatArrayToPyList(vertex, 3);
+    } else if (!error) {
+      error = "must select exactly one atom";
     }
   }
-  return APIFailure(G);
+  return APIFailure(G, error);
 }
 
 static PyObject *CmdFit(PyObject * self, PyObject * args)
```
FYI: We're also working on automatic error propagation with `pymol::Result` return values, but the selector code needs some more refactoring before selection errors can be handled that way.

**Comment by jaredsampson** [comment]
Ok, yeah, that would be helpful.  I didn't see anything in the console, which made me think nothing was being raised.  As I mention in comments on that pull request, I catch the exception from `cmd.id_atom()` because I thought I wasn't getting any response from `get_atom_coords()` (i.e. return value or exception):

```
PyMOL>fab A, ala
PyMOL>print(cmd.get_atom_coords('n. CZ'))
PyMOL>print(type(cmd.get_atom_coords('n. CZ')))
```

but saw clear indication of the error with `id_atom()`:
```
PyMOL>cmd.id_atom('n. CZ')
cmd-Error: atom n. CZ not found by id_atom.
PyMOL>print(type(cmd.id_atom('n. CZ'))) 
cmd-Error: atom n. CZ not found by id_atom.
```

Thanks for looking into it.

**Comment by JarrettSJohnson** [comment]
I submitted an internal review that uses `pymol::Result` to handle automatic error propagation which addresses the issue. If we don't use my approach, anything mentioned here can work as well.

**Comment by jaredsampson** [comment]
Thanks, Jarrett--that sounds great.  Nice to have something reusable and automatic, looking forward to seeing that roll out.  I suspect this means we should probably hold off on the PR for the elbow angle script until your fix comes through.

**Comment by JarrettSJohnson** [comment]
Hi @jaredsampson , commit https://github.com/schrodinger/pymol-open-source/commit/b9b5a06ecb4d75b288d04d7a067a272ac0ef9933 is in now. Does this work for you?

**Comment by speleo3** [comment]
Error is not silent anymore:
```
PyMOL>cz = cmd.get_atom_coords('n. CZ')
 Error: Empty Selection
```

**Comment by jaredsampson** [comment]
This looks great.  Thanks, Jarrett for the fix!
