### ISSUE TITLE
Error launching PyMOLWin.exe with pipeline (-p) command line argument

### ISSUE THREAD

**Issue by vsarpe** [schrodinger/pymol-open-source#75]
I am running the default PyMOL 2.3.3 for Windows.

When I try to launch PyMOL with the `-p` argument (to allow input via STDIN), I get an error message:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\me\PyMOL\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\me\PyMOL\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\me\PyMOL\lib\site-packages\pymol\parser.py", line 529, in stdin_reader
    l = sys.stdin.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
```

I am trying to send commands to PyMOL while it's running from another software. I remember this working in the past but not sure exactly for which version.

Is `-p` still a command line argument? `--help` doesn't seem to work either. Any input on this is appreciated. Thank you.

**Comment by vsarpe** [comment]
Sorry accidentally clicked Close.

**Comment by speleo3** [comment]
Try this:
```
PyMOLWin.exe +2 -p
```
Without the `+2` argument it will launch as a GUI application and disconnect from the console.

These should also work:
```
python.exe -m pymol -p
```
```
Scripts\pymol.exe -p
```

**Comment by vsarpe** [comment]
Thank you @speleo3. Very straightforward.
