### ISSUE TITLE
`pymol2.cmd.get_wizard()` returns `None`

### ISSUE THREAD

**Issue by matteoferla** [schrodinger/pymol-open-source#76]
Is the wizard allowed in multi-instance pymol?

If I do:

    import pymol2

    with pymol2.PyMOL() as p:
        w = p.cmd.wizard("mutagenesis")
        p.cmd.do("refresh_wizard")
        print(p.cmd.get_wizard())

I get `None`, whereas if I do it with `pymol` (or `SingletonPyMOL()` which uses `pymol.cmd` and not `cmd2`) or regular  I get `<pymol.wizard.mutagenesis.Mutagenesis object at 0x7f1a302890f0>`.

It does not cause a segmentation fault (`exit(139)`/`SIGSEGV`(signal 11)),  unlike say accessing a stopped or unstarted or stopping a stopped instance, so is different from the usual issues with pymol2. Hence why I suspect that this is not meant to happen.

**Comment by matteoferla** [comment]
Another one is `str` in alter command.

    import pymol2
    
    with pymol2.SingletonPyMOL() as pymol:
        pymol.cmd.fetch('1ubq')
        pymol.cmd.alter('chain A', 'resi=str(int(resi)-1)')

Works, but with `pymol.PyMOL()` does not.

    Traceback (most recent call last):
      File "", line 1, in <module>
    NameError: name 'str' is not defined

**Comment by speleo3** [comment]
Indeed, the wizard function doesn't automatically forward the `_self` argument. We can fix this once we drop Python 2 support.

As a workaround, this should work:
```python
with pymol2.PyMOL() as p:
    w = pymol.wizarding.wizard("mutagenesis", _self=p.cmd)
    p.cmd.do("refresh_wizard")
    print(p.cmd.get_wizard())
```

You can use the `space` argument with `alter`:
```python
p.cmd.alter('chain A', 'resi=str(int(resi)-1)', space=globals())
```

Or just:
```python
p.cmd.alter('chain A', 'resv -= 1')
```

**Comment by matteoferla** [comment]
Thanks. The latter worked a treat. The former worked with a minor tweak. The `cmd.color` raised a `QuietException`. If caught* it causes no harm:

    import pymol2
    with pymol2.PyMOL() as pymol:
        pymol.cmd.fetch('1ubq')
        pymol.cmd.wizard("mutagenesis", _self=pymol.cmd)
        pymol.cmd.do("refresh_wizard")
        w = pymol.cmd.get_wizard()
        print(w, w is not None)
        w.set_mode('TRP')
        try:
            print(w.do_select(f"A/1/"))
        except pymol.parsing.QuietException:
            pass
        w.apply()
        print('resi 1 is a methionine?', pymol.cmd.select('resi 1 and resn MET') != 0) #no!
        print('resi 1 is a tryptophan?', pymol.cmd.select('resi 1 and resn TRP') != 0) #Yay!

*) Unimportantly, I noticed that `QuietException` subclasses `BaseException` directly and not `Exception`, this [contravenes its PEP](https://docs.python.org/3/library/exceptions.html#BaseException)), there may be a reason for this, but I thought I'd mention it.

**Comment by speleo3** [comment]
Thanks. There was a reason for `QuietException(BaseException)`, but I can't remember what it was :see_no_evil: And I think it's obsolete, we can probably change it now to `QuietException(Exception)`.

**Comment by matteoferla** [comment]
I was mistaken: the wizard does not really work near normal. The coordinates of the mutatated residue are at the origin as opposed to at the location of the original backbone.
![https://www.well.ox.ac.uk/~matteo/M1W.png](https://www.well.ox.ac.uk/~matteo/M1W.png)
