### ISSUE TITLE
Module 'pymol' has no attribute 'Qt'

### ISSUE THREAD

**Issue by pslacerda** [schrodinger/pymol-open-source#79]
I can't import Qt before `finish_launching()`. My script has both a GUI and a `cmd.extend`ed command. I want it to work in library mode but with regular importing.

**Comment by speleo3** [comment]
Hi Pedro - can you be more specific? Something like `import pymol.Qt` or `from pymol.Qt import QtWidgets` works fine for me before calling `finish_launching()`.

**Comment by pslacerda** [comment]
It was my fault, thank you!

**Comment by pslacerda** [comment]
I figured out the problem for future reference.

Once `finish_launching()` is done `pymol.Qt` becomes available importing only `pymol`. In library mode you should import `pymol.Qt` first.
