### ISSUE TITLE
Error while compiling PyMOL on CentOS 6

### ISSUE THREAD

**Issue by smkm** [schrodinger/pymol-open-source#8]
/peopleroot/skim/python3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -Icontrib/champ -I/peopleroot/skim/python3/include/python3.6m -c contrib/champ/feedback2.c -o build/temp.linux-x86_64-3.6/contrib/champ/feedback2.o
    contrib/champ/os_memory.c: In function 'OSMemoryZero':
    contrib/champ/os_memory.c:67:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       while(count&&(((int)p)&mask)) {
                      ^
    contrib/champ/os_memory.c: In function 'OSMemoryHashAdd':
    contrib/champ/os_memory.c:149:8: warning: cast from pointer to integer of different size [-Wpointer-to- int-cast]
       hash=(int)rec;
            ^
    contrib/champ/os_memory.c: In function 'OSMemoryHashRemove':
    contrib/champ/os_memory.c:162:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       hash=(int)rec;
             ^
    /peopleroot/skim/python3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -Icontrib/champ -I/peopleroot/skim/python3/include/python3.6m -c contrib/champ/strblock.c -o build/temp.linux-x86_64-3.6/contrib/champ/strblock.o
    /peopleroot/skim/python3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -Icontrib/champ -I/peopleroot/skim/python3/include/python3.6m -c contrib/champ/vla.c -o build/temp.linux-x86_64-3.6/contrib/champ/vla.o
    gcc -pthread -shared -L/peopleroot/skim/python3/lib -Wl,-rpath=/peopleroot/skim/python3/lib,--no-as-needed -L/peopleroot/skim/python3/lib -Wl,-rpath=/peopleroot/skim/python3/lib,--no-as-needed -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 build/temp.linux-x86_64-3.6/contrib/champ/champ.o build/temp.linux-x86_64-3.6/contrib/champ/champ_module.o build/temp.linux-x86_64-3.6/contrib/champ/chiral.o build/temp.linux-x86_64-3.6/contrib/champ/err2.o build/temp.linux-x86_64-3.6/contrib/champ/feedback2.o build/temp.linux-x86_64-3.6/contrib/champ/list.o build/temp.linux-x86_64-3.6/contrib/champ/os_memory.o build/temp.linux-x86_64-3.6/contrib/champ/sort.o build/temp.linux-x86_64-3.6/contrib/champ/strblock.o build/temp.linux-x86_64-3.6/contrib/champ/vla.o -L/peopleroot/skim/python3/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/chempy/champ/_champ.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: build/temp.linux-x86_64-3.6/contrib/champ/champ.o(.text+0x26): unresolvable H\$爉l$󈊳Ld$䪘HGH򓈉Ո;ÿPxHEItHÿPxHEH{It$H$HlLd$H@xHÿ󿦐H\$爉l$󈊻Ld$䪘HGIӈ芷ÿPhI$HCHÿPhH$IDHlLd$H_ relocation against symbol `PyUnicode_AsUTF8'
    /usr/bin/ld: BFD version 2.20.51.0.2-5.44.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size
    
    /usr/bin/ld: Please report this bug.
    
    collect2: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1

While I was building PyMOL 2.2.0 from the Github open source repository, under Anaconda Python 3.6 on CentOS 6, with all dependencies (I probably didn't make a mistake) installed using Conda, the error same as the above link occurred. 
What should be the problem for the building process?

**Comment by speleo3** [comment]
could be a compiler/linker mismatch. I see `/peopleroot/skim/python3/bin/x86_64-conda_cos6-linux-gnu-cc` and `gcc`, respectively `/usr/bin/ld` in your output.

**Comment by smkm** [comment]
I have resolved the problem by doing the following:
Install all packages from conda stated below: 
```
freeglut                  3.0.0                hf484d3e_5   

freetype                  2.9.1                h8a8886c_1  

gcc_linux-64              7.3.0                h553295d_3   

glew                      2.0.0                h470a237_0    conda-forge 

gxx_linux-64              7.3.0                h553295d_3  

libglu                    9.0.0                hf484d3e_1 

libpng                    1.6.35               hbc83047_0   

libxml2                   2.9.8                h26e45fe_1  

mesa-libgl-devel-cos6-x86_64 11.0.7               h5a2c0ac_0   

mesalib                   17.3.9               hdd5ec5b_0    conda-forge  

pmw                       2.0.1                 py37_1001    conda-forge 

pyqt                      5.9.2            py37h05f1152_2
```

Modify the path of this script to compile since msgpackc and mmtf is not considered crucial unless used and the files still can be exported. Modify if you really need them. 

```
#!/bin/bash -e 

 

prefix=/tempdirtostorepymol/ 

 

# Example for dependencies in non-standard places 

# export PREFIX_PATH="$HOME/extra/glew-2.0.0:$HOME/extra/libpng-1.6.5:/opt/local" 

export CPPFLAGS="-I/pathtopymolopensource/pymol-open-source/glm" 

 

python setup.py build install \ 

    --use-msgpackc=no \ 

    --home=$prefix
```
