### ISSUE TITLE
Windows 10 Pymol crashes on startup

### ISSUE THREAD

**Issue by bzoracler** [schrodinger/pymol-open-source#85]
Pymol was functioning perfectly until earlier today, when I finished installing and running the movie_fade.py script (https://pymolwiki.org/index.php/Movie_fade). I'm not sure if installing this script is related to the problem, but pymol has completely stopped functioning since then. I've tried reinstalling from the open source (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pymol) and also downloading and opening pymol portable. They both crash at the same module loading (grpc), but pymol portable also can't find a heap of modules.

**Attempting to run from pymol Portable view**

![image](https://user-images.githubusercontent.com/50305397/78710417-72a27d80-7969-11ea-8337-c423e92bab48.png)

**Attempting to run from pymol wheel installation view**

![image](https://user-images.githubusercontent.com/50305397/78710678-dcbb2280-7969-11ea-8af6-79bb37d8b8c0.png)

**Comment by speleo3** [comment]
Looks like you added `C:\programdata\anaconda3\lib\site-packages` to the plugin search path. The plugin search path should only contain PyMOL plugins. I suggest that you remove `C:\Users\<username>\.pymolpluginsrc.py`. You can add for example a new empty directory to your plugin search path and then install the `movie_fade.py` script there.

**Comment by bzoracler** [comment]
Thank you, it looks like it's resolved!
