### ISSUE TITLE
GUI for object oriented API

### ISSUE THREAD

**Issue by padix-key** [schrodinger/pymol-open-source#86]
Is there a way to open a GUI from the Python API for `pymol2.PyMOL` objects?

**Comment by speleo3** [comment]
Unfortunately, no. It only provides a low level API which allows you to implement your own GUI. Your GUI has to provide the OpenGL context and the event loop, which may call [pymol2.PyMOL.draw()](https://github.com/schrodinger/pymol-open-source/blob/cfaddbb6801778dd3a786b22a5091b48253e1667/modules/pymol2/__init__.py#L45), like [here](https://github.com/schrodinger/pymol-open-source/blob/cfaddbb6801778dd3a786b22a5091b48253e1667/modules/pmg_qt/pymol_gl_widget.py#L194-L199).

**Comment by padix-key** [comment]
OK, thank you.
