### ISSUE TITLE
shaders disabled on nouveau

### ISSUE THREAD

**Issue by jwhowarth** [schrodinger/pymol-open-source#87]
Testing pymol 2.3.0 on Ubuntu 20.04 under the nouveau drivers using a GTX680, I see...

Detected OpenGL version 4.3. Shaders available.
 Geometry shaders not available
 Detected GLSL version 4.30.
 OpenGL graphics engine:
  GL_VENDOR:   nouveau
  GL_RENDERER: NVE4
  GL_VERSION:  4.3 (Compatibility Profile) Mesa 20.0.4
 Detected blacklisted graphics driver.  Disabling shaders.
 Detected 8 CPU cores.  Enabled multithreaded rendering.
Detected OpenGL version 4.3. Shaders available.
 Geometry shaders not available
 Detected GLSL version 4.30.
 OpenGL graphics engine:
  GL_VENDOR:   nouveau
  GL_RENDERER: NVE4
  GL_VERSION:  4.3 (Compatibility Profile) Mesa 20.0.4
 Detected blacklisted graphics driver.  Disabling shaders.
 Detected 8 CPU cores.  Enabled multithreaded rendering.

Why are shaders disabled for nouveau and is there a way to override that?

**Comment by jwhowarth** [comment]
Manually disabling this in __init__.py...

#    elif (vendor == 'nouveau'
#            or ' R300 ' in vendor # V: X.Org R300 Project, R: Gallium 0.4 on ATI RV370
#            ):
#        if invocation.options.show_splash:
#            print(" Detected blacklisted graphics driver.  Disabling shaders.")
#        cmd.set("use_shaders", 0)

enables the shader support and causes a massive improvement in the performance of the demos in pymol under Ubuntu 20.04. 

Is this blacklisting a legacy change that is no longer relevant to modern nouveau?

ii  xserver-xorg-video-nouveau                 1:1.0.16-1 ii  libdrm-nouveau2:amd64                      2.4.101-1

**Comment by jwhowarth** [comment]
This disabling of shaders on nouveau seems rather ancient, dating back to 1.6.0 and earlier. Is that really still correct on modern Linux?

**Comment by speleo3** [comment]
It's probably not needed anymore. Do you like to send a pull request?

**Comment by jwhowarth** [comment]
Actually, you already did that...

do not blacklist "nouveau" driver
commit af8c2e09c3ff45eaaeaac76a9fb89b9359340336

Any schedule for a 2.4.0 release so that gets pushed out?

**Comment by speleo3** [comment]
We plan to release 2.4.0 in May.
