### ISSUE TITLE
compilation error: layer3/RingFinder.h misses includes

### ISSUE THREAD

**Issue by tbalius** [schrodinger/pymol-open-source#88]
Hi, 

I followed the instructions here:
   https://pymolwiki.org/index.php/Linux_Install#Install_from_source

I encountered a compilation error. 
     layer3/RingFinder.h:45:48: error:
It did not know "size_t". 

I fix this error by adding these to the header file: 
```c++
#include <string>
#include <vector>
#include "os_std.h"
```
Here is the git diff: 
```diff
diff --git a/layer3/RingFinder.h b/layer3/RingFinder.h
index 6c53b14..2d358eb 100644
--- a/layer3/RingFinder.h
+++ b/layer3/RingFinder.h
@@ -1,7 +1,10 @@
#pragma once

+#include <string>
#include <vector>

+#include "os_std.h"
+
struct AtomInfoType;
struct ObjectMolecule;

```
After making this change I was able to compile. 

Take care,

Trent

**Comment by speleo3** [comment]
Thank you, we'll fix this.

For the record: Which Linux distribution (or other OS) is this?

**Comment by speleo3** [comment]
`std::string` is not used in that header, so `#include <string>` should not be needed.

**Comment by tbalius** [comment]
The operating system that I used is CentOS 7.
