### ISSUE TITLE
Issue with transparency after using presets

### ISSUE THREAD

**Issue by DAlvGar** [schrodinger/pymol-open-source#91]
Hi all!

I have a weird behavior that I would like to fix if possible. I am preparing some PSE files that then other people want to costumize further according to their representation preferences. For the PSE preparation I use the preset ligand_sites which is totally fine. However after using the preset, it is no longer possible to adjust the transparency of the surfaces: the ones in the preset or any other surface added afterwards. 

What could be the cause of this issue? Any tips on how to fix it? 

Thank you!

Daniel

**Comment by speleo3** [comment]
The preset sets the `transparency` setting on each atom individually. To set it globally or on an object, clear it on the atoms first:
```python
unset transparency, (*)       ;# clear on atoms
unset transparency, *         ;# clear on objects  
```

**Comment by DAlvGar** [comment]
Thanks a lot @speleo3 ! Just removing the atoms transparencies did the trick. Very helpful!
