### ISSUE TITLE
frame_slider plugin error. please help

### ISSUE THREAD

**Issue by roxiw** [schrodinger/pymol-open-source#92]
Hello. I don't know coding and I really need someone's help. I installed Pymol with anaconda3. I want to install the frame_slider.py so I can visualize my trajectory easier. This is my first attempt to install a plugin in Pymol. I installed the plugin in the /Users/roxie/opt/anaconda3/lib/python3.7/site-packages/pmg_tk/startup 

The first error I get is **2020-05-01 16:16:47.505 python[4349:458625] -[QNSApplication _setup:]: unrecognized selector sent to instance 0x7ff95690a190**

Then if I go to Plugin - Legacy Plugin and Frame Slider I get this error:

```
Traceback (most recent call last):
  File "/Users/roxie/opt/anaconda3/lib/python3.7/site-packages/pmg_tk/startup/frame_slider.py", line 194, in <lambda>
    self.menuBar.addmenuitem('Plugin', 'command', 'Frame Slider', label = 'Frame Slider', command = lambda s=self : FrameSlider(s))
  File "/Users/roxie/opt/anaconda3/lib/python3.7/site-packages/pmg_tk/startup/frame_slider.py", line 55, in __init__
    parent = app.root
  File "/Users/roxie/opt/anaconda3/lib/python3.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 150, in root
    tkinter_init()
  File "/Users/roxie/opt/anaconda3/lib/python3.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 15, in tkinter_init
    raise RuntimeError('tkinter init failed')
RuntimeError: tkinter init failed
```

Can anyone please help me with this problem?

**Comment by speleo3** [comment]
Try this:
```bash
conda install schrodinger::tk
```

**Comment by roxiw** [comment]
Hello,

I tried. It took a lot of time. Found conflicts. But when I tried again in Pymol I got the same errors as before. I am sending a file with the lines from the terminal. It’s quite long. Thanks.

**Comment by speleo3** [comment]
Can you install `schrodinger::pymol` and `schrodinger::tk` in a new environment? Or use our **DMG** bundle from https://pymol.org/#download ?

**Comment by roxiw** [comment]
It didn't work with a new env. Got the same errors when I installed `schrodinger::tk` I installed it again with DMG. It worked now. Thank you very much for the help.
