### ISSUE TITLE
Segmentation fault when clicking the command bar

### ISSUE THREAD

**Issue by tillyboy** [schrodinger/pymol-open-source#94]
I just freshly installed PyMOL and get the following error when I click the command bar:

    /usr/bin/pymol: line 3: 29796 Segmentation fault (core dumped) "/usr/bin/python" "/usr/lib/python3.8/site-packages/pymol/__init__.py" "$@"

This affects only the black command bar at the bottom of the graphics area, not the white one at the bottom of the bottom of the terminal area. So far I have not noticed the problem anywhere with PyMOL. Reinstallation went without error/warnings, problem persists.

The problem to me seems similar to [this issue](https://github.com/schrodinger/pymol-open-source/issues/51).

Info: 

    $ uname -mrs
    Linux 5.6.8-1-MANJARO x86_64
    $ lsb_release -a
    LSB Version: n/a
    Distributor ID: ManjaroLinux
    Description: Manjaro Linux
    Release: 20.0
    Codename: Lysia
    $ pymol --version
    PyMOL 2.3.0 Open-Source
    $ python --version
    Python 3.8.2
    $ python2 --version
    Python 2.7.18

PyQt version is 5.14.2-1

**Comment by speleo3** [comment]
This was fixed in 5d79385a50de11f315942dbe808a94bc8dd3d20c

**Comment by tillyboy** [comment]
@speleo3 if it was fixed, why do I see the issue?

**Comment by speleo3** [comment]
Because you're using v2.3.0 (release Feb 2019). Please use the latest `master` version from this repo.

FYI: We plan to make a v2.4.0 release soon.
