### ISSUE TITLE
Capturing scene pixels without writing image to disk

### ISSUE THREAD

**Issue by AntonioSerrano** [schrodinger/pymol-open-source#95]
So far, I've been able to capture the pixels from the scene in two steps using the png method along with imread:
```
p1.cmd.png(image_path)
img = plt.imread(image_path)
```
Since I have to do this quite often in my program, I'd to capture the pixels in a numpy ndarray avoiding writting the image to disk. Is that possible? Thx.

**Comment by speleo3** [comment]
For the record: Discussion on [pymol-users](https://pymol.org/maillist) mailing list:
https://sourceforge.net/p/pymol/mailman/message/37003576/

Adding a numpy array image export feature should be possible for ray tracing, but may not be possible for OpenGL rendered images (with our current rendering infrastructure).

**Comment by TstewDev** [comment]
Hello @AntonioSerrano, just following up on this to let you know that calling cmd.png with "filename = None" will now return the PNG buffer (e.g. cmd.png(filename = None, width = 200, height = 100)). I'm closing this issue but feel free to reopen it if this fails to meet your needs.
