### ISSUE TITLE
fix pyqt5 sip

### ISSUE THREAD

**Issue by sailfish009** [schrodinger/pymol-open-source#96]
Hi, recently installed pymol on ubuntu 18.04.

when run pymol, show some Qt error, so here is fix:

https://github.com/sailfish009/pymol-open-source/commit/474fc0cba8d4d9b631c58902f790f13e01a36639

**Comment by speleo3** [comment]
This fix doesn't look right, it mixes PyQt4 and PyQt5 imports.

**Comment by sailfish009** [comment]
@speleo3   Yes! indeed. no fix needed.
