### ISSUE TITLE
Rendering Unit Cell in API

### ISSUE THREAD

**Issue by shaychaudhuri** [schrodinger/pymol-open-source#98]
Hi,

I'm trying to generate a series of rendered images using the API. The script works fine but the only thing that it isn't showing in the rendered images is the unit cell. The command I'm using to show the unit cell is `cmd.show(representation='cell')` (the equivalent of `show cell` in the PyMOL program). However, the `cmd` command doesn't appear to work and there is no documentation on how to show the unit cell using the API. Please can this be looked into?

**Comment by speleo3** [comment]
This works for me. Can you provide a complete example?

Please also provide the output of the `diagnostics` command in PyMOL (has details about PyMOL version and operating system).

**Comment by shaychaudhuri** [comment]
> This works for me. Can you provide a complete example?
> 
> Please also provide the output of the `diagnostics` command in PyMOL (has details about PyMOL version and operating system).

Hi, 

This is the `diagnostics` output that I get in PyMOL:

```
PyMOL>diagnostics
PyMOL 2.3.0
build date: Mon Oct 14 10:30:43 2019 +0000
License Information:
Open-Source Build
Operating System:
Linux-3.10.0-1127.el7.x86_64-x86_64-with-centos-7.8.2003-Core
#1 SMP Tue Mar 31 23:36:51 UTC 2020
OpenGL Driver:
VMware, Inc.
llvmpipe (LLVM 7.0, 256 bits)
2.1 Mesa 18.3.4
PyQt4 4.10.1 (Qt 4.8.5)
Python:
2.7.5 (default, Apr  2 2020, 13:16:51)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
prefix=/usr
executable=/usr/bin/python
filesystemencoding=UTF-8
```

Thanks for the help!

**Comment by speleo3** [comment]
Can you try the latest version (2.4)?

**Comment by shaychaudhuri** [comment]
Hi, 

Sorry for the delay in replying, I've been focusing on other work and calculations and have only just gotten round to re-trying to render structures. I've tried the latest version but the unit cell is still not showing with the API code. 

This is one of the structures I'm trying to render ('`structure.pdb`'):

CRYST1    2.526    3.572   40.104  90.00  90.00  90.00 P 1`
MODEL     1`
ATOM      0    C MOL     1      -0.018   2.808   5.068  1.00  0.00           C
ATOM      1    C MOL     1       1.245   1.012   6.314  1.00  0.00           C
ATOM      2    C MOL     1       1.245   1.920   5.067  1.00  0.00           C
ATOM      3    C MOL     1      -0.018   0.143   6.315  1.00  0.00           C
ATOM      4    C MOL     1      -0.017   2.833   7.563  1.00  0.00           C
ATOM      5    C MOL     1       1.245   1.895   7.564  1.00  0.00           C
ATOM      6    O MOL     1      -0.017  -0.218   8.794  1.00  0.00           O
ATOM      7    O MOL     1       1.245   1.373   8.794  1.00  0.00           O
ATOM      8    C MOL     1      -0.018   6.380   5.068  1.00  0.00           C
ATOM      9    C MOL     1       1.245   4.584   6.314  1.00  0.00           C
ATOM     10    C MOL     1       1.245   5.492   5.067  1.00  0.00           C
ATOM     11    C MOL     1      -0.018   3.715   6.315  1.00  0.00           C
ATOM     12    C MOL     1      -0.017   6.405   7.563  1.00  0.00           C
ATOM     13    C MOL     1       1.245   5.467   7.564  1.00  0.00           C
ATOM     14    O MOL     1      -0.017   3.354   8.794  1.00  0.00           O
ATOM     15    O MOL     1       1.245   4.945   8.794  1.00  0.00           O
ATOM     16    C MOL     1       2.508   2.808   5.068  1.00  0.00           C
ATOM     17    C MOL     1       3.771   1.012   6.314  1.00  0.00           C
ATOM     18    C MOL     1       3.771   1.920   5.067  1.00  0.00           C
ATOM     19    C MOL     1       2.508   0.143   6.315  1.00  0.00           C
ATOM     20    C MOL     1       2.509   2.833   7.563  1.00  0.00           C
ATOM     21    C MOL     1       3.771   1.895   7.564  1.00  0.00           C
ATOM     22    O MOL     1       2.509  -0.218   8.794  1.00  0.00           O
ATOM     23    O MOL     1       3.771   1.373   8.794  1.00  0.00           O
ATOM     24    C MOL     1       2.508   6.380   5.068  1.00  0.00           C
ATOM     25    C MOL     1       3.771   4.584   6.314  1.00  0.00           C
ATOM     26    C MOL     1       3.771   5.492   5.067  1.00  0.00           C
ATOM     27    C MOL     1       2.508   3.715   6.315  1.00  0.00           C
ATOM     28    C MOL     1       2.509   6.405   7.563  1.00  0.00           C
ATOM     29    C MOL     1       3.771   5.467   7.564  1.00  0.00           C
ATOM     30    O MOL     1       2.509   3.354   8.794  1.00  0.00           O
ATOM     31    O MOL     1       3.771   4.945   8.794  1.00  0.00           O
ENDMDL

This is my rendering script, `render.py`, which I have been using to render structures. As can be seen on line 6 of the code, I call "`cmd.show(representation='cell')`" but when I run the script, the unit cell does not show.

`from pymol import cmd

#Viewing settings
cmd.load("structure.pdb")
cmd.set('orthoscopic', 1)
cmd.show(representation='cell')

#Ball-and-stick model
cmd.show('spheres')
cmd.set('sphere_scale', 0.33)
cmd.show('sticks')
cmd.set('stick_radius', 0.2)

#Colours
cmd.color('grey', 'name C*')
cmd.set('stick_transparency', 0.05)
cmd.bg_color('white')
cmd.set('ray_opaque_background', 0)
cmd.set('ray_shadow', 0)

#Render image
basename = 'Structure'
cmd.zoom(complete=1)
cmd.ray(1024, 1024)
cmd.png(basename+'_Z'+'.png', dpi=600)

cmd.rotate('y',-90)
cmd.rotate('z',-90)
cmd.ray(1024, 1024)
cmd.zoom(complete=1)
cmd.png(basename+'_X'+'.png', dpi=600)

cmd.rotate('z',-90)
cmd.rotate('x',-90)
cmd.rotate('z', 90)
cmd.ray(1024)
cmd.zoom(complete=1)
cmd.png(basename+'_Y'+'.png', dpi=600)

cmd.quit()
`

**Comment by speleo3** [comment]
Unit cell is clipped off the given example. Adding `cmd.clip("slab", 100)` after `zoom` fixes the issue.
See https://www.mail-archive.com/pymol-users@lists.sourceforge.net/msg15926.html
