### ISSUE TITLE
Doesn't save the plist using a --record {plist} instructruction

### ISSUE THREAD

**Issue by yurivict** [schrodinger/pymol-open-source#99]
Version 2.4.0

```setup.py install --record {plist.txt}``` should save a list of files that it installs.

See documentation: https://setuptools.readthedocs.io/en/latest/easy_install.html

**Comment by speleo3** [comment]
We don't use `setuptools`, we use `distutils`.

**Comment by yurivict** [comment]
That's what I use too. distutils is also supposed to support ```--record {plist.txt}```.

**Comment by speleo3** [comment]
Previous ticket: https://sourceforge.net/p/pymol/bugs/186/

As I wrote there: patches welcome

**Comment by yurivict** [comment]
Sorry, I am only a package maintainer, and I don't have resources to develop patches.

**Comment by JarrettSJohnson** [comment]
Moved to setuptools. Feel free to reopen if needed.
